rasterio/rasterio

rasterio/rio/merge.py
tests/test_rio_merge.py

This fixes two bugs in ```merge```:
* ```verbosity``` was not always defined, and thus broke tests once they were created
* the shape of the destination image was hardcoded to always have 3 bands regardless of input number of bands
This also adds tests for 100% coverage.  Includes a test fixture for generating test data files; we may want to consider this pattern for other tests as well.
I'm getting flakey results from travis-ci for a simple array equality test; some python versions pass sometimes and others do not.  It should be an all or nothing proposition.  All tests pass locally (Linux Mint 17, Python 2.7.6).

Fixed proper handling of verbosity and output shape for rio merge

---

requirements-dev.txt
setup.py

My CentOS 6.6 console, managed by someone else, has setuptools version 0.6.10-3.el6, and runs into trouble Cythonizing from setup.py, since it doesn't generate the .c files:
```
$ python setup.py build_ext --inplace
running build_ext
building 'rasterio._base' extension
creating build
creating build/temp.linux-x86_64-2.6
creating build/temp.linux-x86_64-2.6/rasterio
gcc -pthread -fno-strict-aliasing -O2 -g <snip> -c rasterio/_base.c -o build/temp.linux-x86_64-2.6/rasterio/_base.o
gcc: rasterio/_base.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1
```
Upgrading the setuptools minimum version fixes the issue.
Change Extension import from distutils to setuptools.
Also add "-W all" debug output to setup.py logger

Use setuptools>=0.9.8 since earlier versions don't Cythonize C files

---

rasterio/_base.pyx
tests/test_tags.py

GDALs metadata items are encoded like `"KEY=VALUE"`. Making sure that when there's an equal sign in `VALUE` (like `FOO=BAR`), we get tags like `"KEY": "FOO=BAR"`.

Tag equality

---

rasterio/_base.pyx
rasterio/_drivers.pyx
rasterio/_err.pyx
rasterio/_features.pyx
rasterio/_gdal.pxd
rasterio/_io.pyx
rasterio/_warp.pyx
setup.py

Resolves #257 
This should remove the Cython compile warnings that originate from rasterio.  There are still some that originate from GDAL and Numpy.
Most warnings were due to using ```char *``` when we should have been using ```const char *```.
Others were mostly due to uninitialized variables.
A few were due to multiple declarations of variables in one statement; Cython usually wants them to be on separate lines.

Removed Cython compile warnings

---

rasterio/_example.pyx
rasterio/_features.pyx
rasterio/_warp.pyx

Should get a little speedup there. Also remove bounds check from the _example module.

Remove cython profiling from _features and _warp.

---

docs/cli.rst
rasterio/_features.pyx
rasterio/features.py
rasterio/rio/features.py
rasterio/rio/main.py
tests/conftest.py
tests/test_features_bounds.py
tests/test_rio_features.py

This adds a ```rasterize``` command to ```rio```.  It includes the ability to specify input GeoJSON as an input file or from ```stdin```, ability to rasterize into all bands of an existing raster, ability to set key parameters like transform, coordinate reference system, and data type from a template raster, and specify some of the direct input parameters of rasterio's ```rasterize()``` function like ```default_value``` and ```all_touched```.
See ```docs/cli.rst``` for example usages.
See ```rio rasterize --help``` for full help info (there is a lot).
Things to be aware of during review:
* I pulled methods for calculating bounds from GeoJSON from Fiona, and modified here  to work with FeatureCollections.  We may want to consider making these changes to Fiona if acceptable here.
* …

Added rio-rasterize

---

rasterio/_fill.pyx
rasterio/_gdal.pxd
rasterio/fill.py
rasterio/rasterfill.cpp
setup.py
tests/test_fillnodata.py

I propose this as a successor to #227.
I've copied rasterfill.cpp from GDAL. The original used GeoTIFFs for temp files and I have changed the temp file driver to "MEM", the in-memory dataset driver. We're now making a different tradeoff in our implementation: extra memory on the order of dataset_shape * 3 * dtype_size but no disk I/O (at least until the algorithm is done and you write results to disk).
@snorfalorpagus thanks to your careful Cython coding, it *just worked*. @brendan-ward want to take a look at this, too?

Vendorize rasterfill.cpp

---

rasterio/_gdal.pxd
rasterio/_io.pyx
rasterio/rio/features.py
rasterio/rio/merge.py
rasterio/tool.py
tests/test_band_masks.py
tests/test_read.py
tests/test_tool.py

Behavior is the same as `read()`: accepts `indexes, out window, boundless` args.
Towards a fix of #285

New read_masks() method

---

examples/reproject.py
rasterio/transform.py
tests/test_transform.py

To simplify and clarify the reprojection example.
Closes #286.

Add affine transform factories from_origin, from_bounds

---

rasterio/_base.pyx
rasterio/_io.pyx
rasterio/rio/merge.py
tests/test_coords.py
tests/test_indexing.py
tests/test_rio_merge.py
tests/test_rio_sample.py
tests/test_sampling.py
tests/test_transform.py

Closes #282.
At the heart of this was a subtle indexing error due to calling
round() instead of math.floor(). Fixing that needed a cascade of
fixes to expectated values in various tests.
Finally, core logic in the merge command was rewritten for
correctness and clarity.

Correct indexing and merging

---

rasterio/_features.pyx
rasterio/features.py
tests/test_features_shapes.py
tests/test_features_sieve.py

Resolves #305 
While we technically could probably allow any numeric data type as input to the mask, awkward things happen when casting types to ```uint8``` if values are out of bounds.  To avoid the unexpected, I figured it was better to be strict here, and let the user cast as necessary before calling these functions.
Improved test coverage for these functions.

Updated mask dtype for shapes() and sieve()

---

rasterio/_base.pyx
rasterio/_gdal.pxd
rasterio/rio/features.py
tests/test_crs.py
tests/test_rio_features.py

Resolves #268 
Now raises warning instead of error if bounds are disjunct between geojson input and existing output raster or ```--like``` raster.  
Raises an error if ```--src_crs``` is provided and does not match existing output raster or ```--like``` raster; otherwise it is assumed to match the crs of those.  This allows you to provide GeoJSON in a non-EPSG crs (since ```--src_crs``` is limited to EPSG codes) provided that it matches the existing output raster or ```--like``` raster, rather than always defaulting to ```EPSG:4326```.
Added a few OSR utility functions to check if crs is geographic, projected, or the same between two.  To assist with this, I alphabetized the OSR functions in ```_gdal.pxd```.
While I was at it, I added more tests for ```crs.py```

Updated handling of CRS and bounds mismatches in rio rasterize

---

rasterio/__init__.py

See https://github.com/Toblerity/Fiona/pull/219
To build an executable from a Python script using cx_Freeze, you do something like this:
```
pip3 install cx_Freeze
cxfreeze test.py
dist/./test
```
If we try to do this for a simple script that imports rasterio, it raises an error as not all of the modules used are detected automatically. This can be worked around by manually telling cx_Freeze which modules to import. http://cx-freeze.readthedocs.org/en/latest/faq.html#problems-with-running-frozen-programs
This happens because some of the modules are only called from the Cython extensions, which cx_Freeze can't parse. We could make this easier for the user by making sure all of the modules used are imported from Python space. This shouldn't add any overhead, as the modules are already …

Import all modules from Python space to help cx_Freeze et al.

---

docs/cli.rst
rasterio/_base.pyx
rasterio/_io.pyx
rasterio/features.py
rasterio/rio/features.py
rasterio/rio/main.py
tests/test_features_rasterize.py
tests/test_indexing.py
tests/test_rio_features.py

Resolves #243 
Adds an ```extract``` command to rio which allows you to extract out pixels from a raster using features to either mask in (default) or mask out (using ```--invert```) pixels.
Includes minor refactoring of window handling to consolidate usages.  Note: this is an API change, do to the way default value is set.  Only one test needed to be updated, but this should be noted in the changelog if this PR is accepted.

Added rio extract command

---

rasterio/__init__.py
rasterio/profiles.py
tests/test_profile.py

Goal: reduce boilerplate and promote interoperability and best practices. The `default_gtiff_profile()` function reduces the number of keyword args you'll need to pass to `open()` for creation of new files to 5: `count, width, height, transform, crs`.
```python
>>> import rasterio
>>> rasterio.default_gtiff_profile(count=1, width=1, height=1)
{'count': 1, 'width': 1, 'dtype': 'uint8', 'driver': 'GTiff', 'height': 1, 'interleave': 'band', 'blockxsize': 256, 'tiled': True, 'blockysize': 256, 'nodata': 0, 'compress': 'lzw'}
```
To be used like
```python
with rasterio.open(
'example.tif', 'w',
**rasterio.default_gtiff_profile(
count=1, width=1, height=1, transform=..., crs=...)) as dst:
```
You could also overlay this profile on keyword args taken from another file:
```python
with …
```

Add a default GTiff profile and factory for keyword args

---

docs/cli.rst
rasterio/rio/bands.py
rasterio/rio/calc.py
rasterio/rio/cli.py
rasterio/rio/features.py
rasterio/rio/info.py
rasterio/rio/merge.py
rasterio/rio/rio.py
rasterio/rio/sample.py
tests/test_rio_merge.py
tests/test_rio_rio.py

Standardized snake case to GNU stye flags, added short flags where appropriate, standardized use of 'input' argument, and removed unused imports in rio modules.
Resolves #324 except for parts already handled by #323

Standardized rio flags

---

CHANGES.txt
rasterio/rio/bands.py
rasterio/rio/calc.py
rasterio/rio/cli.py
rasterio/rio/features.py
rasterio/rio/info.py
rasterio/rio/merge.py
tests/test_rio_cli.py
tests/test_rio_merge.py

Plus a function to resolve the standard args and options to a standard `output, [inputs]` pair.
Closes #333.

Add -o/--output option to commands

---

rasterio/_gdal.pxd
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/rio/main.py
setup.py

Defines a "rasterio.rio_commands" entry points and turns all of the existing commands into entry points that are loaded by main.py.
Adds a virtual_file_to_buffer() function to support MBTiles export.
Fixes a bug in reproject().

Making CLI commands pluggable

---

rasterio/rio/main.py

On catching an ImportError, we make a dummy/stub subcommand that sits in the list of subcommands as expected and reports the error there. Example (after breaking, locally, the rio-mbtiles plugin):
```
$ rio --help
Usage: rio [OPTIONS] COMMAND [ARGS]...
Rasterio command line interface.
Options:
-v, --verbose  Increase verbosity.
-q, --quiet    Decrease verbosity.
--version      Show the version and exit.
--help         Show this message and exit.
Commands:
bounds     Write bounding boxes to stdout as GeoJSON.
calc       Raster data calculator.
env        Print information about the rio environment.
info       Print information about a data file.
insp       Open a data file and start an interpreter.
mask       Mask in raster using features.
mbtiles    Warning: plugin module could not be …
```

Handle plugin load errors in a helpful way

---

rasterio/_gdal.pxd
rasterio/_io.pxd
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/warp.py
tests/test_warp.py

Resolves #342 
Fixed bug where we were updating but not correctly persisting warp options.
Refactored and added several things along the way:
* expanded ```io_auto``` to handle a 3rd dimension, and wired this into ```_reproject``` to cut down on the boilerplate code there
* added ```fill``` parameter ```reproject```to initialize the destination (instead of calling it ```nodata```).  Makes explicit that it is set to 0 (which is default from GDAL).  Also doesn't imply masking is to be expected from this (see comments on #342).
* added ```transform_bounds``` to use an edge-densification approach for transforming the bounds of a raster into a new CRS.  Uses same densification default as GDAL.
* added ```calculate_default_transform``` to generate a new transform, width, and height in a way …

Resolved reproject fill value bug, added transform utilities

---

README.rst
setup.py

gdal-config only exists on unix systems.  When building on windows, a call to gdal-config will always fail, and the compilation of the extension modules will subsequently fail.  
This change will look for a gdal-config.txt file first, and if that is not available, hope that we are running on a unix system.  This allows the builder to still specify the library paths so that the extension modules can be compiled successfully on windows.  The format of gdal-config.txt is unchanged (first line: include directories; second line: library directories; third line: gdal data directory).  There is no change in the build process for unix systems (except for possibly making sure that gdal-config.txt does not exist).  On windows, the user will need to create a gdal-config.txt file that contains the …

make setup.py work on all platforms (specifically non-unix platforms).

---

rasterio/__init__.py

@sgillies what do you think about removing the file existence check when reading a file? There are cases where a dataset name accepts a different format than a file path. One example at: http://www.gdal.org/frmt_plmosaic.html.
If the file path doesn't exist, an `IOError` still propagates to the user.

Dataset naming

---

setup.py

This PR makes two changes.
1) get the output of gdal-config directly and parse instead of writing and reading it from a file.
2) Check for the existence of a GDAL_DATA (https://trac.osgeo.org/gdal/wiki/FAQInstallationAndBuilding#WhatisGDAL_DATAenvironmentvariable).
GDAL_DATA is equivalent to gdal-config --datadir, so I check both (as determined by PACKAGE_DATA).
Still need to test the changes, so don't merge yet.  Feedback welcome.

gdal-config and GDAL_DATA

---

rasterio/_base.pyx
tests/test_transform.py

I often find myself computing window corner coordinates when working with rasters and vectors in the same spatial context:
```python
with rio.open(infile) as src:
for _, window in src.block_windows():
((row_min, row_max), (col_min, col_max)) = window
x_min, y_min = (col_min, row_max) * src.affine
x_max, y_max = (col_max, row_min) * src.affine
```
and thought others might be doing the same so I added it as a method to `DatasetReader()`.
Example usage:
```python
import rasterio as rio
with rio.open('tests/data/RGB.byte.tif') as src:
rows, cols = src.shape
ds_window = ((0, rows), (0, cols))
print(src.window_bounds(ds_window))
_, first_window = next(src.block_windows())
print(src.window_bounds(first_window))
```
Output:
```console
(101985.0, 2611485.0, 339315.0, 2826915.0)
(101985.0, …
```

Added DatasetReader.window_bounds() to compute window corner coordinates

---

rasterio/rio/bands.py
rasterio/rio/calc.py
rasterio/rio/features.py
rasterio/rio/info.py
rasterio/rio/merge.py
rasterio/rio/rio.py
rasterio/rio/sample.py
tests/test_rio_calc.py

Click will do this for us. If we raise click.Abort(), we get the proper return value of 1.
Closes #350.

Remove sys.exit() calls.

---

docs/cli.rst

Some of the `rio` commands were missing from the options in the `cli.rst` file. This just updates them to the ones from the help message.
I also took the liberty of removing "new" from the description of rio.

Sync CLI docs with current options

---

rasterio/_features.pxd
rasterio/_io.pyx
requirements-dev.txt
setup.py

Resolves #371 and #276 
Function declarations, including ```except NULL``` need to match between ```.pyx``` and ```.pxd``` files now.
For reasons that are not immediately clear, Cython now returns ```np.dytpe(some_dtype).kind``` as an integer, and does not cast to a ```char```, instead of returning it as a character that matches our dictionary keys for these.  I added the integer codes to the dictionary in addition to the characters.  This same fix is not needed apparently in pure Python code.
I also turned off a couple of the Cython compile time warnings; these didn't appear to be giving us useful information that we could use to cleanup the code.

Upgrade to Cython 0.22

---

rasterio/rio/rio.py
rasterio/tool.py

Allows the use of IPython from `rio insp`, with tab completion, history, pretty-printed dictionaries, and all else that gives you.
Falls back to the standard interpreter if the IPython import fails.

Use IPython for the rio interpreter

---

rasterio/rio/rio.py
rasterio/tool.py
setup.py

Someone can now add bpython if they want to do so. I've switched the default interpreter back to the ordinary Python interpreter. Not that it's better, but it has fewer versioning considerations (see https://github.com/mapbox/rasterio/pull/372#issuecomment-107194069).
In setup.py, I've listed ipython as an 'extra' feature.

Generalize the alt interpreter feature.

---

setup.py

I goofed when suppressing Cython compile-time warnings; those compiler flags do not work for Microsoft's Visual Studio when building on Windows.
This omits those flags if running on Windows.  Maybe not a perfect fit for those compiling with mingw or in Cygwin or somesuch, but the only downside is more compiler warnings (which we had until very recently anyway).

Omit cython extra_compile_args on Windows

---

docs/cli.rst

`rio edit-info --transform` was missing an `input.tif` to operate on. Added `example.tif`.

add missing input to rio edit-info example

---

rasterio/rio/calc.py

This is a possible solution for #380 : Some failing tests when building using Numpy 1.8. After the calculation in snuggs, also the masked values are changed. 
When writing the data set, the changed values were written rather than the nodata values. 
One can argue that this fix should go into snuggs instead, and a check for the numpy version could be added (to avoid large copies when using 1.9), but with this change in place at least all tests return the right result using Numpy 1.8.

Fix calculation with Numpy <1.9

---

rasterio/rio/features.py
rasterio/rio/helpers.py
tests/test_rio_helpers.py
tests/test_rio_info.py

Adds a `--dst_crs` option to `rio-bounds`.
Two questions, both very minor.
* The `dst_crs` cli option is now common between Fiona and Rasterio. How about adding it to cligj?
* `rasterio.warp.transform_bounds` accepts arguments in a different order than `rasterio.warp.transform` and `rasterio.warp.transform_geom`, both accepting `src.crs` and `dst.crs` as the first two arguments. How about doing the same for `transform_bounds`? This would permit:
```
rasterio.warp.transform_bounds(src.crs, dst.crs, *src.bounds)
```
/cc @sgillies @brendan-ward

add dst_crs to rio-bounds

---

rasterio/warp.py
tests/test_warp.py

@sgillies @brendan-ward As promised, here's a PR to make args for `rasterio.warp.transform`s funcs more consistent. `src_crs` and `dst_crs` are always the 1st args.

consistent args throughout transform funcs

---

rasterio/rio/merge.py

rio-merge no longer ignores --driver

---

README.rst
rasterio/_base.pyx
rasterio/rio/bands.py
rasterio/rio/calc.py
rasterio/rio/features.py
rasterio/rio/merge.py
rasterio/rio/options.py
tests/test_meta.py
tests/test_options.py

Closes #379.
@sgillies have a look at #402 before merging.  The bug fix in #401 is also included in this PR so once that is merged I'll pull it back into here to make sure it doesn't cause a conflict.
The `--photometric` flag in `rio stack` could be deprecated in favor of `--co PHOTOMETRIC=...` but I'm guessing its pretty deeply integrated into some pipelines.

Add creation options to CLI commands

---

rasterio/crs.py
rasterio/rio/info.py
tests/test_crs.py
tests/test_rio_info.py

In combination with, eg, `--crs ?`, this will extract the metadata value from another file.
So far, it seems like a value will be required for the options. I think `?` makes a decent placeholder.
This PR also moves validation of the --crs, --transform, and --nodata options to callbacks, simplifying the command's function quite a bit.
Thoughts, @brendan-ward @jacquestardie @geowurster?
See #387.

Add a --like option to rio-edit-info

---

docs/cli.rst
rasterio/crs.py
rasterio/rio/features.py
rasterio/rio/merge.py
rasterio/rio/options.py
rasterio/rio/warp.py
rasterio/warp.py
setup.py
tests/test_crs.py
tests/test_rio_features.py
tests/test_rio_merge.py
tests/test_rio_warp.py
tests/test_warp.py

Partially resolves #264 
```
Usage: rio warp [OPTIONS] INPUT OUTPUT
Warp a raster dataset.
The output is always overwritten.
If a template raster is provided using the --like option, the coordinate
reference system, affine transform, and dimensions of that raster will be
used for the output.  In this case --dst-crs, --bounds, --res, and
--dimensions options are ignored.
If --dimensions are provided, --res and --bounds are ignored.  Resolution
is calculated based on the relationship between the source raster bounds
and dimensions, and may produce rectangular rather than square pixels.
If --bounds are provided, --res is required if --dst-crs is provided
(defaults to source raster resolution otherwise).  Bounds are in the source
coordinate reference system.
Options:
-f, --format, --driver …
```

Initial implementation of rio-warp

---

rasterio/rio/convert.py
tests/test_rio_convert.py

@brendan-ward How about this for a solution to the scaling and range communication issue: we switch to very explicit (explicit is better than implicit) `--scale-ratio` and `--scale-offset` options, exactly as in the GDAL VRT spec? Simplies the code quite a bit, which is good.
This PR is not against master, but against the rio-translate branch, btw. A PR on a PR.
There's still future room for auto linear scaling. I think we could let non-linear scaling be handled by rio-calc.

Switch to --scale-ratio and --scale-offset

---

docs/cli.rst
docs/reproject.rst
rasterio/rio/overview.py

No functional changes in this one, only documentation.
* standardized references to rio commands in cli.rst
* added new example to reproject.rst
* fixed pyramid->overview in rio-overview docstring and cli.rst.

Minor documentation updates

---

README.rst
docs/cli.rst

Updated readme and cli.rst with a brief description on rio plugins.
This is intended to be merged after #426 
This partially resolves #425.  Once this is in, I am planning to update the wiki to point back to these changes and shift the focus there to be a registry of rio plugins.
/cc @geowurster

Added information on rio plugins to docs

---

rasterio/_features.pyx
rasterio/_fill.pyx
rasterio/_warp.pyx
rasterio/dtypes.py
tests/test_dtypes.py

closes #436 
Putting it in ```rasterio.dtypes``` seemed like the most logical place to put it, since we're effectively doing a check for the array's type.  Can easily be moved elsewhere if needed.

Consolidated checks for ndarray type

---

rasterio/enums.py
tests/test_overviews.py

The Resampling.average enum value had a comma after it, which caused
that particular enum to map to a tuple instead of a string.  This broke
the use of the average kernel when making overviews.
This fixes issue #440, I added a test as well.

removed errant comma in enums.py

---

rasterio/rio/convert.py

@sgillies - I was receiving an error when using the new `--rgb` flag. This creation option wasn't being passed to the new file during an invocation of `rio convert`.
If you're inclined to reproduce the problem:
```shell
rio convert RGB.byte.tif --dtype uint16 --scale-ratio 257 RGB.uint16.tif
rio convert RGB.uint16.tif out.tif --rgb
File "/Users/amitkapadia/anaconda/envs/pl/bin/rio", line 9, in <module>
load_entry_point('rasterio==0.25.0', 'console_scripts', 'rio')()
File "/Users/amitkapadia/anaconda/envs/pl/lib/python2.7/site-packages/click/core.py", line 664, in __call__
return self.main(*args, **kwargs)
File "/Users/amitkapadia/anaconda/envs/pl/lib/python2.7/site-packages/click/core.py", line 644, in main
rv = self.invoke(ctx)
File …
```

use creation options when setting rgb

---

.travis.yml
README.rst
requirements-dev.txt

Using these gets the individual rio-mbtiles builds down to 30 seconds and can similarly speed up other plugin builds.
After some false starts and pulled hair, I decided not to do anything about speeding up Rasterio's own builds. Since we need to cythonize and compile source files anyway, the gain from using binary wheels for requirements is relatively small.
NB: between building numpy and rasterio from source, these releases take a while. Around 20 mins each.
This work is ~30% done, not quite ready for review.

Build and release wheels for rasterio and requirements (on: tag)

---

rasterio/tool.py
tests/test_tool.py

Closes #456.
@sgillies @brendan-ward ready for review, especially the color choices.  I chose `gold` as the default for 2d arrays both because it stands out against the grey border and to get away from the default blue.  It's a bit soft since the transparency is set to `50%` so I'm open to other suggestions.
With `rio-insp`:
```console
$ rio insp tests/data/RGB.byte.tif
>>> show_hist(src.read(), bins=256)
```
Directly with Python:
```python
import rasterio
import rasterio.tool
with rasterio.open('tests/data/RGB.byte.tif') as src:
rasterio.tool.show_hist(src.read(), bins=256)
```

Add rasterio.tool.show_hist()

---

tests/test_read_resample.py
tests/test_rio_features.py

See discussion on gdal-dev mailinglist:
https://lists.osgeo.org/pipermail/gdal-dev/2015-August/042380.html
"Changing very slightly the test case should hopefully hide that annoyance."
This closes Bug #229 
I tested on i386 and amd64.

Adjust tests to no longer fail on i386

---

rasterio/_io.pyx
tests/test_read_boundless.py

The overlap calculation logic had a bug when the `window[0][1]` or  `widow[1][1]` was equal to zero. The problem stems from the superfluous `or` statement which, in most cases, did absolutely nothing but in this particular edge case caused an error.
Resolves #476

fix overlap stop equal to zero bug, add tests

---

CHANGES.txt
rasterio/rio/features.py

By using `enumerate()` and the filename. 
Closes #479.
Also got a speedup by pulling base name calculation out of the loop.

Ensure uniqueness of rio-shapes feature ids.

---

rasterio/_base.pyx

The `op` keyword was not being passed to `get_index`, and precision was not available to the `index` method.
I debated whether this was preferable to explicitly setting keyword arguments `op` and `precision` in `index`. Both sides have drawbacks. And, of course, I started this by adding the `get_index` function in the first place. In any case, I'm not sure this is the right way to go, but wanted to make sure the full functionality was available to `index`.

Added kwargs to index method in _base.pyx.

---

.travis.yml

I'm expecting at least one error, see https://github.com/mapbox/rasterio/issues/478.

Add GDAL 2.0.1 to the build matrix

---

.coveragerc
.travis.yml
requirements-dev.txt
setup.cfg
setup.py

Closes #504 
Added extra cythonize arguments, enabled by an environment variable `CYTHON_COVERAGE` set for travis (or local development, if you set that manually).  This requires updated versions of Cython and pytest-cov, so I updated those in `requirements-dev.txt`, and a `.coveragerc` file.
I also dropped `coveralls` from `requirements-dev.txt` since it is used from travis and already being installed there.
While I was at it I moved the functions toward the top of setup.py, and cleaned up `setup.cfg` which wasn't being used previously (had `nose` testing config).  
Expect coverage to drop quite a bit once this goes out, so now we have some new targets to shoot for.

Added Cython coverage reporting

---

docs/windowed-rw.rst
rasterio/__init__.py
rasterio/_io.pyx
tests/test_indexing.py

Closes #496 
Adds functions to `_io.pyx` to assist with calculating the data window, as well as utilities for calculating the union or intersection of windows.
Pending travis, this is ready to go.

Add more window utilities

---

rasterio/rio/info.py

The `rio insp` docstring says 
> IPython will be used as the default interpreter, if available.
~~Let's do that!~~ Let's change the docstring since that's not the case

rm ipython as default from rio insp docstring

---

rasterio/_base.pyx
rasterio/_err.pyx
rasterio/_io.pyx
rasterio/enums.py
tests/test_transform.py

This also adds an enum for GDAL errors, and specifically checks one of those on attempting to read affine.
Warnings could not be tested in this case; the tests pass when run individually, but fail when run as a suite.
I modified @perrygeo 's failing test from `affine_roundtrip` branch for use here.

Added warnings for affine input / output

---

rasterio/_io.pyx
tests/test_read_boundless.py

Closes #532 
In determining where to put the valid data in the output array of a boundless read, this fixes the offsets to be dependent only on the col/row start.
Ready to merge.
/cc @sgillies @dnomadb

Fix boundless offsets

---

rasterio/rio/merge.py

Needed a `\b` for to disable click text wrapping.
@sgillies @brendan-ward @perrygeo 
Malformed:
```
Note: --res changed from 2 parameters in 0.25.   --res 0.1 0.1  => --res
0.1 (square)   --res 0.1 0.2  => --res 0.1 --res 0.2  (rectangular)
```
Fixed:
```
Note: --res changed from 2 parameters in 0.25.
--res 0.1 0.1  => --res 0.1 (square)
--res 0.1 0.2  => --res 0.1 --res 0.2  (rectangular)
```

Tiny formatting fix in rio merge help text

---

rasterio/__init__.py

The new `vfs.py` needs to be imported in __init__ for cx_Freeze/PyInstaller/etc to automatically detect it.

Added vfs to imports in __init__.py

---

docs/features.rst

A silly little thing... for some reason I always go to the online docs when I need to rasterize, and time after time I always forget that I don't want the 0 default for NODATA.  I hope this change jogs my memory next time.  Hopefully others will find this note helpful.

Document rasterize's "fill".

---

rasterio/rio/features.py
tests/test_rio_info.py

Fixes #556 
This PR modifies `rio bounds` to use the `rasterio.warp.transform_bounds` function which densifies the line and considers all 4 corners to ensure that the resulting bbox is actually a bounding rectangle in the output projection.
This image show the old output in green, the new output in red
Also, makes input required to avoid funky exception when not provided.

Use transform_bounds to compute rio bounds

---

rasterio/_io.pyx

The lintian QA tool reported this spelling error for the recent rebuild of the rasterio 0.31.0 Debian package with GDAL 1.11.4 and 2.0.2.

Fix 'tranform' typo, replace with 'transform'.

---

rasterio/tool.py

@sgillies @perrygeo @brendan-ward Ready.
In some environment configurations (primarily Python 2 in a virtualenv?) `matplotlib` can raise a `RuntimeError` on import, but we don't want this to bring down the entire `tools` modules, so converting it to a warning seems like a better move.  This warns with `RuntimeWarning` rather than `ImportWarning` because the latter is [ignored by default](https://docs.python.org/2/library/warnings.html#warning-categories).
**Before:**
```console
$ rio insp ../rasterio/tests/data/RGB.byte.tif --ipython
File "/Users/kwurster/code/benthos-pipeline/venv/bin/rio", line 11, in <module>
sys.exit(main_group())
File "/Users/kwurster/code/benthos-pipeline/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
return …
```

When importing matplotlib, convert a potential RuntimeError to a warning

---

rasterio/tool.py
tests/test_tool.py

When (dataset, bidx) is passed into `rasterio.tool.show`, uses the bounds of the dataset to set the extent accordingly, so that the matplotlib figure shows world coordinates, rather than pixel coordinates. In case of a numpy array, simply uses pixel coordinates.

Use raster bounds to set extent in rasterio.tool.show.

---

rasterio/rio/features.py
rasterio/tools/mask.py
tests/conftest.py
tests/test_tools_mask.py

Before putting together this pull request, I thought I had seen some sort of masking utility, but didn't find it. Now, as I write the summary, I discovered that it is in `rio.features`, rather than `rio.clip` as I had guessed. So maybe if you all are interested in something like this, it will look more like the `rio.features.mask` function than what I've got right now.
Anyway, I've added a function for use in python that applies the geo-JSON-like `shapes` from `rasterio.features.shapes` to a raster as a mask, setting all pixels outside of the region defined by shapes to be no data. I do so in the spirit of @sgillies suggestion to commit early and solicit comments. Aside from the possible DRY issue that I noted above, I'm not so sure about where I've put this function, nor about how I'm …

masking function within rasterio

---

tests/test_crs.py

The WKT string for EPSG:3857 has changed in GDAL 2.1, so make
the test a bit less specific for robustness.

Fix test_write_3857() with GDAL trunk (#548)

---

rasterio/_warp.pyx

In the case where the input / output dataset is a ndarray, the logging
of the CRS is done after CPLFree()ing the string.
Reported by Valgrind with errors like:
==9948== Invalid read of size 2
==9948==    at 0x4C2F7E0: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9948==    by 0x529DAA: PyString_FromString (in /usr/bin/python2.7)
==9948==    by 0x1BFBE155: __pyx_pf_8rasterio_5_warp_4_reproject (_warp.cpp:6248)
==9948==    by 0x1BFBE155: __pyx_pw_8rasterio_5_warp_5_reproject(_object*, _object*, _object*) (_warp.cpp:4776)
==9948==    by 0x49C4D8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==9948==    by 0x4A090B: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==9948==    by 0x499A51: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==9948==    by 0x4A1C99: ??? (in …

Fix 2 use after free in reproject()

---

rasterio/_warp.pyx

Objects factory = new OGRGeometryFactory() and oWarper = new GDALWarpOperation()
need to be explicitly deallocated with del
(see https://github.com/cython/cython/wiki/WrappingCPlusPlus)
Also fixes a few leaks in exception code paths.
Now 'valgrind --leak-check=full --trace-children=yes ~/.local/bin/py.test tests/test_warp.py'
no longer reports memory leaks.

Fix memleaks in _warp._reproject()

---

rasterio/rio/warp.py
rasterio/warp.py

This PR adds 
* `--check-invert-proj` option to rio-warp to set the gdalenv for clipping to valid coordinate region or not
* Temporarily set `--threads` to default to 1 for safety (other threads could get diff envs, see #599)
* removes the drivers context manager within `calculate_default_transform` - gdalenv must now be provided by the caller
Resolves #575

Check invert proj

---

.travis.yml

This is in response to #571.
I also wonder why tests are run on 1.9.2?

bump gdal versions

---

.travis.yml
scripts/travis_gdal_install.sh

This PR incorporates many of the ideas in #605 but enables caching and gdal 2.1
To recap:
* Actually use the build matrix - removing the space in GDALVERSION allows env var to get set properly.
* Build the GDAL versions with proper flags to set hdf5, proj and png deps
* Add the aforementioned deps by apt dev packages
* removes redundant pip install
* Adds GDAL 2.1 to the build matrix
* Adds GDAL 1.10.0 to the build matrix (that's the system version which, ironically, was the only one we were testing previously)
* Adds a test that the correct GDAL is being run, i.e. `gdal-config --version` is equal to $GDALVERSION
* Disables Python 3.3 support to keep the build matrix reasonable. (3.5 is already out so we should be adding that soon)
Cached need to be cleared so if any branches or PRs are …

enable all the gdals, py2.7 and 3.4

---

AUTHORS.txt
rasterio/_base.pxd
rasterio/_base.pyx
rasterio/_err.pyx
rasterio/_fill.pyx
rasterio/_io.pyx
rasterio/_warp.pyx
tests/test_err.py
tests/test_tags.py
tests/test_update.py

It's this @perrygeo @brendan-ward (updated to account for 659e4e4):
```python
try:
with CPLErrors() as cple:
some_gdal_function_that_calls_CPLError()
cple.check() # exception raised from here
except CPLE_SomeError as err:
raise SomeRasterioError(str(err))
```
I'd like to keep GDAL's CPLE_* errors from leaking out of our Cython code, raising exceptions that are designed to work better with Python.
The reason why I'm **not** going to register a Python exception-raising callback with CPL as I mentioned in #600 is that the thread of execution gets lost: we wouldn't be able to handle it and execute clean-up.
Closes #600

New pattern for handling GDAL errors in Cython code

---

rasterio/_base.pyx
rasterio/_warp.pyx
rasterio/errors.py
rasterio/rio/warp.py
tests/test_rio_warp.py
tests/test_warp_transform.py

CRSError is new and derives from ValueError.
Tests added for bad --dst-crs parameters in rio-warp
Closes #595

Catch CRSError in rio-warp and raise BadParameter

---

tests/test_colorinterp.py

Was not relevant since GDAL does the YCbCr conversion internally for GeoTiffs.Users deal in RGB. GDAL_JPEG_TO_RGB only applies to JPEG format.

Remove xfailed YCbCr test

---

rasterio/aws.py

When botocore establishes a session, it tries a number of methods in a specified order. If they fail, they return None. Then, if no session information could be established, the returned session credentials is None instead of a credentials object.
This PR checks the truthiness of `self._creds` to avoid raising an `AttributeError` when accessing properties on init.

allow boto sessions to be falsey

---

rasterio/crs.py
rasterio/rio/warp.py
tests/test_crs.py
tests/test_rio_warp.py

Closes #628
@sgillies @brendan-ward @perrygeo Currently `$ rio warp --dst-crs {}` is valid but produces an output dataset without a CRS.  I modified `rasterio.crs.from_string()` to raise a `ValueError()` if an empty JSON object is decoded for consistency between the library and CLI.
What about `"[]"`?  Currently `from_string()` produces an empty dict, but it seems like this should also raise an exception.  We don't use lists for CRS at all, right?
```python
>>> from rasterio.crs import from_string
>>> print(from_string('[]'))
{}
```
```console
$ rio warp --dst-crs {} tests/data/RGB.byte.tif -o OUT.tif
Usage: rio warp [OPTIONS] INPUTS... OUTPUT
Error: Invalid value for dst_crs: crs is empty JSON
```

An empty JSON object used as a CRS is invalid

---

rasterio/__init__.py
rasterio/_drivers.pyx
rasterio/rio/main.py
tests/test_driver_management.py

Never restore it to the GDAL default. This avoids the situation where GDAL is writing directly to stderr.
Also get in line with best practices for library and application logging: NullHandlers attached in `rasterio/__init__.py` and then overridden in rasterio/rio/main.py.
- http://docs.python-guide.org/en/latest/writing/logging/#logging-in-a-library
- http://docs.python-guide.org/en/latest/writing/logging/#logging-in-an-application
Closes #649

Keep rasterio's cpl error handler in place

---

rasterio/__init__.py
rasterio/_base.pyx
rasterio/_copy.pyx
rasterio/_drivers.pyx
rasterio/_features.pyx
rasterio/_fill.pyx
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/enums.py
rasterio/errors.py
rasterio/features.py
rasterio/merge.py
rasterio/plot.py
rasterio/rio/info.py
rasterio/rio/main.py
rasterio/transform.py
tests/test_driver_management.py

Basically use `logging.getLogger(__name__)` everywhere and configure at the top of the hierarchy.
Fixes a few pep8 nits along the way.

Embracing hierarchy of loggers

---

docs/color.rst
docs/concurrency.rst
docs/features.rst
docs/reproject.rst
docs/windowed-rw.rst
examples/async-rasterio.py
examples/concurrent-cpu-bound.py
examples/decimate.py
examples/rasterize_geometry.py
examples/reproject.py
examples/sieve.py
examples/total.py
rasterio/rio/rasterize.py
tests/conftest.py
tests/test_blocks.py
tests/test_colormap.py
tests/test_png.py
tests/test_read.py
tests/test_revolvingdoor.py
tests/test_rio_features.py
tests/test_rio_merge.py
tests/test_rio_warp.py
tests/test_update.py
tests/test_warp.py
tests/test_write.py

Deleting the methods should be the only remaining change for `1.0` to completely remove `read_band()` and `write_band()`.

Remove references to read/_band() but not the actual methods

---

rasterio/rio/stack.py
tests/test_rio_stack.py

`rio stack` explicitly type-checked for lists. The caused a bug when we started returning indexes as tuples in #655 
This PR makes checks for the Iterable base class and adds a test that the output data's max > 0.

fixes #669

---

rasterio/_io.pyx
tests/test_read_boundless.py

resolve numpy deprection warnings

---

README.rst
docs/cli.rst
docs/cookbook.rst
docs/features.rst
docs/georeferencing.rst
docs/installation.rst
docs/masks.rst
docs/osgeo_gdal_migration.rst
docs/reading.rst
docs/reproject.rst
docs/tags.rst
docs/windowed-rw.rst
docs/working_with_datasets.rst
docs/writing.rst

Refs https://github.com/mapbox/rasterio/issues/589.
This PR includes documentation updates driven largely by [retext-mapbox-standard](https://github.com/mapbox/retext-mapbox-standard) recommendations.

[NOT READY] Documentation polish

---

rasterio/_io.pyx
tests/test_dataset_mask.py
tests/test_env.py

This PR implements a `RasterReader.dataset_mask` method which calculates a per-dataset mask according to a simple heuristic.
resolves #705 and (unrelated except for getting my local tests to pass) fixes #715

per-dataset mask

---

docs/Makefile
requirements-dev.txt

For contributors with write permissions, publishing the latest docs could be streamlined to 
```
cd docs; make publish
```

make publish target to streamline doc deployment

---

rasterio/__init__.py
rasterio/dtypes.py
rasterio/rio/insp.py
rasterio/rio/shapes.py
tests/conftest.py
tests/test_blocks.py
tests/test_copy.py
tests/test_deprecations.py
tests/test_features.py
tests/test_fillnodata.py
tests/test_indexing.py
tests/test_pad.py
tests/test_png.py
tests/test_read.py
tests/test_read_boundless.py
tests/test_read_resample.py
tests/test_rio_convert.py
tests/test_rio_features.py
tests/test_rio_merge.py
tests/test_rio_warp.py
tests/test_update.py
tests/test_warp.py
tests/test_write.py

Fixes the majority of #727 
Not sure if these need to be addressed, but they are not something I wanted to tackle at this time:
./rasterio/_example.c:17132: * import numpy
./rasterio/_example.c:17156: * import numpy
./rasterio/_example.pyx:3:import numpy
I know the sprints don't technically start until the morning, but I will be at work all day, so I started a bit early. I wanted to make sure everything was still set up right on this machine, and figured this was a quick one to do.

Standardize on import numpy as np.

---

setup.py

Setup.py change to
* Move the `extras_req` section into a variable
* add a `plot` extra for matplotlib
* add an `all` extra which collects all the specified extra into a single target so you can do `pip install -e .[all]` instead of `pip install -e .[ipython,s3,plot,test,docs]`

extras for setup.py

---

rasterio/rio/warp.py

Removes dtype and driver refs from rio warp doc

---

rasterio/rio/helpers.py

The FileOverwriteError in rio/helpers.py used incorrect abbrevation (-f)
for --force-overwrite. This change fixes #747, but using the long form
options in the error message.

Corrects error message in rio warp wrt overwrites

---

rasterio/_io.pyx
tests/conftest.py
tests/test_read.py

Closes https://github.com/mapbox/rasterio/issues/706
Ready to go.
This kind of gets into #322 and `src.shape` only containing 2 dimensions, but do we ant to enforce `out_shape[0] == indexes[0]`?  In the case of `out` we have to get the data from one array into the another so they _have_ be the same shape, but in the case of `out_shape` we can rely on `indexes` to provide the first dimension.
`read((1, 3), out_shape=(2, 10, 10))` could be replaced with `read((1, 3), out_shape=(10, 10))`

Add out_shape to read() and read_masks()

---

rasterio/_base.pxd
rasterio/_base.pyx
tests/test_crs.py

resolves #757 
Note: the upshot here is that EPSG codes that GDAL deems invalid, or any other error during OGRSpatialReference creation will now be caught and re-raised as a CRSError.  Not sure if we want that to be more specific.

More tests for CRS conversion to OGRSpatialReference

---

rasterio/_err.pyx
rasterio/_warp.pyx
tests/test_err.py
tests/test_rio_warp.py
tests/test_warp.py

Attempt at #614
So far it's an xfailing test for several (not all) of the resampling methods.
I've also `pass`ed on CPLE errors in warping - this was the behavior as of #657 (see #611 too) but was changed back [here](https://github.com/mapbox/rasterio/commit/12f8fc7e3f73766ee80b8f64813601e56caae618#diff-7519f03c7f3cca2b36a087ca08b1ffd1R570) for reasons that I've since forgotten. Can you refresh my memory on this @sgillies?

Dealing with non-invertable projection errors

---

rasterio/rio/info.py
tests/test_rio_info.py

Adds #586 
It is included as part of the verbose options.
Example: `"colorinterp": ["red", "green", "blue", "alpha"]` from `alpha.tif`

Add color interpretation to rio info.

---

rasterio/rio/rasterize.py
tests/test_crs.py
tests/test_deprecations.py
tests/test_env.py

Increases coverage to 2 missing lines (a defensive except statement that I cannot get to raise)
There are several other partial paths through the code that are untested (29 partial lines). Manually inspecting them did not lead to any red flags so I'll defer them.

a few more tests

---

tests/test_mask_creation.py

sidecar masks work with windows, internal does not - known bug at #781 so let's xfail it.

test windowed masks

---

rasterio/env.py
rasterio/warp.py
tests/test_env.py
tests/test_warp.py

Resolves #613 
By making the default env `CHECK_WITH_INVERT_PROJ=True`, we more closely match the behavior of GDAL (which uses it as a de-facto default in gdalwarp) and we greatly reduce the chances of hitting #614 
This is our first case of explicitly defining a default env variable on behalf of the user. Is this the correct way to implement it @sgillies ? see changes in `rasterio/env.py`

Use CHECK_WITH_INVERT_PROJ=True in default Env

---

docs/writing.rst
rasterio/_io.pyx
tests/test_write.py

This PR blacklists the netCDF driver which has [known problems](https://github.com/mapbox/rasterio/issues/638) with writing via the `IndirectRasterUpdater`.
Also documents the write driver situation.
Fixes #647, fixs #731

Unsupported write drivers

---

rasterio/rio/options.py
rasterio/vfs.py
tests/test_rio_options.py

Fixes #754.  On Windows systems, VFS filepaths are still expecting forward slashes, rather than the currently implemented `os.path.sep`.  This PR does the following:
* adds utility function `abspath_forward_slashes` to forces forward slashes in absolute paths
* changes `file_in_handler` to return forward-slashed filepaths
* fixes tests and removes triple-slashed zip test in `test_rio_options.py`
There may be better ways to fix this, just wanted to get the ball rolling.

Force file paths to be forward slashes even on Windows

---

.travis.yml
CONTRIBUTING.rst
README.rst
docs/installation.rst

The libgdal-dev package depends on its respective libgdal package,
there is no need to install the library package explicitly.
The library package name has changed to reflect changes in the libgdal C++ API,
libgdal1h is now only appropriate for older releases.
libgdal1h is used for GDAL >= 1.10.0, included in Debian jessie and Ubuntu trusty.
libgdal1i is used for GDAL >= 1.11.2, included in Ubuntu vivid, wily, and xenial.
libgdal20 is used for GDAL >= 2.0.0, included in Debian testing & unstable, and Ubuntu yakkety.

Drop mentions of old libgdal1h package.

---

rasterio/rio/warp.py
tests/test_rio_warp.py

This PR resolves #549 with backwards-incompatible changes to rio warp
* removes `--x-dst-bounds` entirely
* new `--bounds` will behave like the old `x-dst-bounds`
* new `--src-bounds` stays the same
Open question: do we want to include a `--dst-bounds` alias to `--bounds`? I know that wasn't part of the original plan but every other option seems to specify `src-` or `dst-` when there could be ambiguity.

removing --x-dst-bounds

---

rasterio/__init__.py
rasterio/_gdal.pxd
rasterio/_warp.pyx
rasterio/rio/warp.py
tests/test_rio_warp.py
tests/test_warp.py

Significant speedups by 1) warping multiple bands in one pass, 2) using the approximate transformer as suggested in #569.
```
(pydotorg35)MapBox-FC:rasterio sean$ time rio warp --threads 4 --dst-crs epsg:3857 ~/work/data/NE2_50M_SR_W/NE2_50M_SR_W.tif -o /tmp/warped.tif
real	0m4.148s
user	0m4.473s
sys	0m1.521s
```
```
(pydotorg35)MapBox-FC:rasterio sean$ time gdalwarp -t_srs epsg:3857 ~/work/data/NE2_50M_SR_W/NE2_50M_SR_W.tif /tmp/gdalwarped.tif -overwrite
Creating output file that is 7284P x 9630L.
Processing input file /Users/sean/work/data/NE2_50M_SR_W/NE2_50M_SR_W.tif.
0...10...20...30...40...50...60...70...80...90...100 - done.
real	0m2.540s
user	0m1.569s
sys	0m0.692s
```

Faster warp

---

rasterio/_err.pyx

The spelling errors was reported by the lintian QA tool for the most recent Debian package build.

Fix 'errror' typo, replace with 'error'.

---

rasterio/rio/warp.py
tests/test_rio_warp.py

Resolves #814 
If this is how we want to handle invalid parameter combinations that were silently ignored previously, there are probably a couple other places that need to be updated to match this too.

Raise exceptions for invalid rio warp parameter combinations

---

rasterio/_base.pyx
rasterio/_warp.pyx

resolves #828 
`rasterio.transform.tastes_like_gdal` is the one, `_base` and `_io` import it
a few trailing whitespace changes while we're at it.

single definition of tastes_like_gdal

---

rasterio/io.py

Caught a typo in `src.xy` method and in the corresponding docstring:
``` python
AttributeError                            Traceback (most recent call last)
<ipython-input-48-170b33479138> in <module>()
----> 1 src.xy(ys, xs, 'ul')
/home/ceholden/conda/envs/yatsm/lib/python2.7/site-packages/rasterio/io.pyc in xy(self, row, col, offset)
47             ``(x, y)``
48         """
---> 49         return xy(self.tranform, row, col, offset=offset)
50 
51     def ul(self, row, col):
AttributeError: 'DatasetReader' object has no attribute 'tranform'
```
Thanks for developing Rasterio -- it's been a joy to use in my work.

Fix 'tranform' typo in doc & method

---

rasterio/_base.pyx
rasterio/_io.pyx

Resolves #514 . There are still several warnings but as noted https://github.com/mapbox/rasterio/issues/514#issuecomment-240137280, those are known issues related to the C code generated by Cython, not related to our pyx code.

cast to avoid cython warnings re: discarding qualifiers

---

rasterio/rio/warp.py
tests/test_rio_warp.py

The previous version had the `--check-invert-proj` option set with `is_flag=True, default=True` which effectively means there's no way to supply a `False`. This PR switches to the `--opt/--no-opt` syntax to make it more explicit

rio warp: fix check-invert-proj option

---

rasterio/_io.pyx
rasterio/windows.py
tests/test_windows.py

Resolves #759.
`Window` extends `tuple` and can be substituted for the old 2-tuples everywhere. Its constructor is `Window(col_off, row_off, num_cols, num_rows)` to help developers coming from GDAL. `Window.from_ranges()` and `Window.from_bounds()` are a pair of classmethods that complement the default constructor.
I've modified the functions of `rasterio.windows` to return instances of `Window` instead of "bare" 2-tuples.
@brendan-ward @perrygeo @geowurster what do you think?

Window class

---

rasterio/rio/overview.py
tests/test_rio_overview.py

Change up the branching logic to allow `--ls` to open in read mode.
Also if neither `--ls`, `--build` or `--rebuild` is specified, raise a UsageError. Alternatively, toying with the idea of making `--ls` the default.
Fixes #885

rio overview --ls opens readonly

---

CHANGES.txt
rasterio/__init__.py
rasterio/warp.py

Made to support multiband warping to or from a GDAL dataset (rather than a ndarray).
The 1.0a2 version bump is tagging along for the ride.

Documentation of the changes to Band

---

rasterio/_base.pyx

Small change to reduce the noise with `INFO` level logging. These EPSG notifications feel more like debugging logs than info.

epsg logging from info to debug

---

rasterio/_drivers.pyx

I've run recently into an incompatibility between rasterio and osgeo.gdal
Since recently in GDAL master, osgeo.gdal bindings are generated with an option
that cause the GIL to be released before going to GDAL native code :
https://trac.osgeo.org/gdal/ticket/6649
I now observe crashes when running the following
```
import rasterio
from osgeo import gdal
gdal.OpenEx('i_dont_exist', gdal.OF_RASTER | gdal.OF_VERBOSE_ERROR)
```
The stack trace is
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe1507401 in __Pyx_PyObject_Call (kw=0x0, arg=0x7fffe177f750, func=0x7ffff67b5cf8) at rasterio/_drivers.c:4620
4620        if (unlikely(Py_EnterRecursiveCall((char*)" while calling a Python object")))
(gdb) bt
#0  0x00007fffe1507401 in __Pyx_PyObject_Call (kw=0x0, arg=0x7fffe177f750, …
```

Declare errorHandler() with gil

---

rasterio/_io.pxd
rasterio/_io.pyx
rasterio/windows.py
tests/test_complex_dtypes.py
tests/test_dtypes.py
tests/test_gdal_raster_io.py
tests/test_warp.py

Towards resolving #900 
It turns out that the problem has nothing to do with warping. It is this: when a ndarray view is passed into dataset's `read()` or `write()` and thereby into the lower level `io` functions, the layout of the underlying buffer is miscommunicated to `GDALRasterIO()` and bytes were scrambled.
This is a show-stopping bug for 1.0a2. I'm doing some refactoring to make the bug easier to fix.

Raster data IO correctness

---

rasterio/plot.py

Fixes #913 
I couldn't demonstrate any performance difference between the methods. There shouldn't be any impacts aside from fixing the nan case.
Leaves unresolved the question of how nan's should be treated in rio info stats or even more fundamentally if we should consider `nan` as a defacto nodata value when doing masked reads. Different questions for another time.

use nanmin/max for histogram range

---

rasterio/rio/info.py

Tiny tweak to make `rio info` output more readable by sorting the keys for consistent order. Was thinking of making this an option but I don't see any downside to hardcoding it.
related to #904

enforce consistent key order in rio info output

---

rasterio/_warp.pyx
rasterio/control.py
rasterio/rio/gcps.py
rasterio/rio/info.py
setup.py
tests/test_rio_gcp.py
tests/test_rio_info.py
tests/test_warp.py

Either simple JSON representation or GeoJSON, one object or seq. With option to round, as in rio-shapes.
This work also caught a bug in transform_geom(), see #922.

Add --gcps to rio-info

---

rasterio/windows.py
tests/test_windows.py

When finding a window for clipping a subset of a raster, it is sometimes useful for the window to evenly split on the borders of the raster's tiles. For example, if a subset is clipped out of a larger raster, if that subset raster will end up being multiplied against or otherwise compared to the larger raster, having the tiles line up makes for a cleaner operation. In addition, if running some kind of block statistics of a larger raster and a subset, having tiles that are equal makes it easier to compare differently shaped, but identically tiled rasters.

Adds function that rounds window to full expanse of intersecting tiles

---

tests/test_warp.py

Adjust warp tests for proj 4.9.3
For our tests parameterized by `CHECK_WITH_INVERT_PROJ`, we are expecting that the extent is far enough outside of the destination projection's valid bounds that it would hit uninvertable coordinatates. `proj` 4.9.3 introduced new transverse mercator calculations which give different results in the out-of-bounds regions. The trick was to find a projection that a) has uninvertable coords for this extent and b) behaves similarly across proj versions. I found that [epsg:26836](http://spatialreference.org/ref/epsg/26836/) fits the bill. There may be better ones to consider.
The densify bounds transformation and all other transforms which don't need to consider out-of-bounds cases, have been switched to [epsg:2163](http://spatialreference.org/ref/epsg/2163/) …

Warp tests

---

rasterio/warp.py
tests/test_warp_transform.py

* Width and height are required.
* Either bounding values *or* ground control points (but not both) must be provided
* Explicit test for gcps with `calculate_default_transform`
Resolves #943

clarify bounds vs gcps in calculate_default_transform

---

.travis.yml
rasterio/gdalextras.pxi

Also adds `rasterio/gdalextras.pxi` to `.gitignore`.

Travis Python 3.6

---

rasterio/_base.pyx

This releases the GIL around `GDALOpen`, allowing multiple/different datasets to be opened concurrently in multiple threads (convenient for loading remote datasets). Prior to this, opening would occur sequentially even when triggered by different threads.

Release GIL when opening datasets

---

rasterio/plot.py

`with_bounds` had been used for (RasterReader, band) arguments, and for
RasterReader arguments when multiband, but was not using with_bounds
when passed a single band RasterReader as its argument.

Use with_bounds for singleband show(RasterReader).

---

rasterio/_base.pyx
rasterio/_crs.pyx
tests/test_crs.py

Allow comparison of null CRS with other CRS. I've reached the point where feedback would be useful. I've removed the ValueError raised from `_osr_from_crs`, and modified the behavior in checking equality of two CRS such that they must both be valid and equal to evaluate as True. I modified one group of tests (whose name I should have changed, I just realized), `test_crs.test_can_create_osr_none_err`, since that is the behavior I explicitly modified. I added a couple of simple tests of CRS comparison. On my system, I'm seeing one test failure, when warping a dataset with no CRS. It seems that a ValueError should now be raised in `reproject` when crs is None, but before I went too far, I thought I'd check in.

Modify behavior of null CRS, WIP (#960).

---

rasterio/rio/calc.py
requirements.txt
setup.py
tests/test_rio_calc.py

Compliment to `snuggs=1.4.1` fix that should address #947
Storing in regular dict or passing via kwargs ignores the order of user input, making (read 1) and (read 2) sometimes act out of order (important for things like subtraction). These changes substitute an `OrderedDict` which should solve the issue. I was able to trigger a failure from the test case I added prior to applying the `OrderedDict` patch, and it passed with the code change. Finally, I specified the version of `snuggs` with the relevant fix as minimum version.
Let me know how it looks. Sorry for the wait!

rio calc: pass snuggs eval kwargs as OrderedDict

---

rasterio/__init__.py

The context managers introduced in https://github.com/mapbox/rasterio/pull/966 will not tear down properly if an exception is raised.  This code snippet exhibits the problem:
```python
import os
import rasterio as rio
assert not os.path.exists('TEST.tif'), "Output 'TEST.tif' already exists."
with rio.open('tests/data/RGB.byte.tif') as src:
profile = src.profile.copy()
try:
with open('TEST.tif', 'wb') as f:
with rio.open(f, 'w', **profile) as dst:
dst.write(src.read())
raise Exception
except:
print(os.path.getsize('TEST.tif'))
with rio.open('TEST.tif') as src:
print(src.count)
```
This is a common pattern for using `@contextmanager` on a function that needs to do some teardown:
```python
@contextmanager
def func():
try:
yield something
finally:
```

Better context manager teardown

---

setup.py

Using `ext_modules.extend`, I got 
```
INFO:root:GDAL API version obtained from gdal-config: 2.1.2
File "setup.py", line 288, in <module>
Extension('rasterio._shim', ['rasterio/_shim21.c'], **ext_options))
TypeError: 'Extension' object is not iterable
```
For adding a single `Extension`, using append works.

append to extensions list

---

tests/test_env.py

For easier offline development.  Running `$ pytest -m 'not network` will skip any test requiring network access.

Flag tests requiring network access

---

.gitignore
rasterio/_env.pxd
rasterio/_env.pyx
rasterio/env.py
setup.py
tests/conftest.py
tests/test_concurrency.py
tests/test_env.py
tests/test_threading.py

Includes the work in PR #993. 
Resolves #996.

Better defined and tested concurrent Envs

---

rasterio/_io.pyx
rasterio/env.py

Previously, creation options were logged with a trailing newline:
```
DEBUG:rasterio._io:Option: ('TILED', b'FALSE')
DEBUG:rasterio._io:Option: ('INTERLEAVE', b'PIXEL')
```
and some of the `Env()` related logging used the root logger rather than the Rasterio logger.
```
DEBUG:root:Starting outermost env
DEBUG:root:Exiting outermost env
```

Cleanup logging

---

docs/topics/masking-by-shapefile.rst
docs/topics/masks.rst
docs/topics/plotting.rst

Ref. Issue #1017 
Fixed images in the following files:
- masks.rst
- masking-by-shapefile.rst
- plotting.rst

Fixed broken image URLs 

---

rasterio/_env.pyx

Better to not have it set than set to a non-existing directory.
The bug described at https://github.com/Toblerity/Fiona/issues/439 can also happen with rasterio depending on how it is installed.

Don’t set PROJ_LIB to a non-existing directory

---

setup.py

When run without a gdal environment, `setup.py` is throwing an exception due to uninitialised variable `gdalversion` instead of printing [the error message below it](https://github.com/mapbox/rasterio/blob/994def271a14126e690a080ead816626a70fdeb0/setup.py#L135).
Full stack trace:
> 
> File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
> yield
> File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\sandbox.py", line 255, in run_setup
> DirectorySandbox(setup_dir).run(runner)
> File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\sandbox.py", line 285, in run
> return func()
> File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\set …

Fix setup.py exception when no gdal is available

---

CHANGES.txt
rasterio/io.py
rasterio/warp.py

Covers most of #1009
Eliminates most of the `Env()` creation within Rasterio, except for `rasterio.open()`, which will be more involved.

Rely on @ensure_env for a GDAL environment

---

.gitignore
tests/test_env.py
tests/test_err.py
tests/test_features.py
tests/test_rio_warp.py
tests/test_tags.py
tests/test_warp.py
tests/test_warp_transform.py

For https://github.com/mapbox/rasterio/issues/1009
As referenced in https://github.com/mapbox/rasterio/issues/1009#issuecomment-293443234.
I also switched the test responsible for writing `test.tif` to the current directory to pytest's `tmpdir` fixture.

Dont instantiate 'rasterio.Env()' in tests unless necessary

---

rasterio/_env.pxd
rasterio/_env.pyx
tests/test_env.py

Otherwise we pay penance to the thread lock gods every time an environment is started.  This slipped through https://github.com/mapbox/rasterio/pull/997.

Actually keep track of whether or not the drivers are registered

---

rasterio/rio/shapes.py

This could previously occur when one or more dimensions was smaller than the sampling factor (e.g. 4800, 1).
```
ERROR:rasterio._gdal:CPLE_AppDefined in Attempt to create 48x0 dataset is illegal,sizes must be larger than zero.
ERROR:rio:Exception caught during processing
File "/usr/local/lib/python2.7/dist-packages/rasterio/rio/shapes.py", line 229, in shapes
**dump_kwds)
File "/usr/local/lib/python2.7/dist-packages/rasterio/rio/helpers.py", line 55, in write_features
features = list(collection())
File "/usr/local/lib/python2.7/dist-packages/rasterio/rio/shapes.py", line 205, in __call__
rasterio.features.shapes(img, **kwargs)):
File "/usr/local/lib/python2.7/dist-packages/rasterio/features.py", line 100, in shapes
for s, v in _shapes(image, mask, …
```

Avoid generating shapes w/ 0-dimension

---

rasterio/_base.pyx
rasterio/_crs.pyx
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/gdal.pxi

Per issue #1021, `OSRRelease()` is safer.

Switch OSRDestroySpatialReference to OSRRelease

---

rasterio/_io.pyx
tests/test_write.py

It looks like the previously implemented data type check was not ever
being entered, due to checking for a 'type' attribute on a string. Since
the _init_dtype attribute is now always a string, remove this check and
related handling, so that now dtypes are checked for validity, providing
a more useful error message in case of an invalid dtype. Fixes #1008.

Fix dtype check in dataset write

---

rasterio/_io.pyx
rasterio/_shim1.pyx
rasterio/_shim21.pyx
rasterio/directives.pxi
tests/conftest.py
tests/test_read_boundless.py

Resolves #1030.
Tests are forthcoming. As is a check that we can revert to `np.empty()` for bounded reads.

Use np.zeros instead of np.empty in read()

---

rasterio/_env.pyx
rasterio/env.py
tests/test_env.py

When setting up an environment, pass in user provided options during the
original environment definition (and driver registration), rather than
defining the environment, and then defining potential driver related
configuration options too late to use them.
I think this addresses #1000 and #1001. At the very least, I was able to
override the default JP2 driver options in a rasterio environment on the
command line on my computer. There are certainly some subtleties
in this process with which I'm not familiar though. I also was not quite
sure what a test of this should look like. The most immediate hurdle was 
my uncertainty in whether there were particular drivers that would be
reasonable to test in a platform independent manner. I didn't see much 
in `test_env` that provided immediate …

Set GDAL config options before driver registration

---

rasterio/io.py

Context: I was trying to create an HGT file using a `MemoryFile` and discovered that it wasn't using `BufferedDatasetWriter` (which it should have given that `Create` isn't supported by `SRTMHGT`).

Choose the correct DatasetWriter in MemoryFile

---

rasterio/_io.pyx
rasterio/io.py

SRTMHGT driver validates filenames, so UUIDs prevent it from working properly. This adds a `filename` arg to appease it by providing filenames that match.

Allow filenames to be provided by MemoryFile

---

CHANGES.txt
rasterio/_env.pyx
rasterio/gdal.pxi
tests/test_env.py

Closes #875 
Looking at the [`osgeo` Python bindings](https://github.com/OSGeo/gdal/blob/trunk/gdal/swig/python/osgeo/gdal.py#L2934) it appears as though they use [`GDALGetCacheMax64()`](http://www.gdal.org/gdal_8h.html#ac06786652e940f0694cf214dfa08b74d).
A couple things:
1. When GDAL is compiled as 32 bit I don't know if `GDAL*CacheMax64()` is defined, but I'm also not sure how to check if an external object exists in a `pxi` file.  There's a check to see if Python is 64 bit, which the config option handlers use to determine with function to call.
2. The `GDALSetCacheMax*()` functions claim to support setting `GDAL_CACHEMAX` with a string like `4%`, but I couldn't get it to work in Rasterio or `osgeo`.  This suggests it is possible though: `GDAL_CACHEMAX=1% CPL_DEBUG=ON gdal_translate …

Special handling for GDAL_CACHEMAX

---

requirements-dev.txt
tests/test_rio_features.py
tests/test_rio_merge.py

Pytest 3.1, released yesterday,  introduces some [new features and changes](https://docs.pytest.org/en/latest/changelog.html#changelog-history) in handling warnings.
For the purposes of rasterio tests, we assumed that some warnings are captured in the result output. This is no longer the case in pytest 3.1.
This PR upgrades pytest to >= 3.1.0 and asserts those warnings using the recommended [`pytest.warns`](https://docs.pytest.org/en/latest/warnings.html#warns)

pytest warnings

---

tests/test_crs.py

These tests cover the case where the CRSs are not exactly equal but equivalent. This doesn't necessarily cover any new code paths in `_crs.pyx`, just tests the expected behavior explicitly.
per https://github.com/mapbox/rasterio/pull/1058#issuecomment-303762545

add tests for OSR equivalence

---

rasterio/dtypes.py
tests/test_dtypes.py

`get_minimum_dtype()` was not returning working properly when numpy arrays with `uint`* dtypes were passed in.
Added tests to prove it and prevent regressions.

Fixed bug in dtypes.get_minimum_dtype()

---

CONTRIBUTING.rst
rasterio/_warp.pyx
rasterio/gdal.pxi
rasterio/vrt.py
tests/test_warpedvrt.py

When working with DEMs, I've discovered that it's necessary to (create and) read from warped VRTs where the pixel dimensions match the world at particular web Mercator zooms, else GDAL interpolation (regardless of resampling method) introduces artifacts that only show up when calculating gradients (generating hillshades), e.g.:
I'm attempting to wrap `GDALCreateWarpedVRT` to achieve this. However, it doesn't include all of the data source / warp option preparation that `GDALAutoCreateWarpedVRT` does, so additional work needs to be done in `create_warp_options`, etc.
This PR looks right, but when I try to use it (`read`ing windows from the VRT), it segfaults within `io_multi_band` (in `shim_rasterioex.pxi`).
I _think_ I may be creating `hTransformArg` incorrectly (in `_warp.pyx`; …

WarpedVRT with target dimensions

---

rasterio/_warp.pyx
rasterio/vrt.py

Switches to using `GDALCreateGenImgProjTransformer3` with explicit source and target CRSes and transformations. This allows source georeferencing information to be provided explicitly if it's not available in the source file(s) for some reason.
(Actual reason: GDAL / rasterio's behavior when reading masks (containing overviews, but not georeferencing, as they're considered sidecars) over HTTP is sub-optimal (results in _many_ more Range requests than not reading the masks), so I'm creating a `WarpedVRT` and reading them as though they're normal sources. I don't know how to effectively describe a repro / identify a cause, so no issue for that.)

Warped vrt source georeferencing

---

rasterio/_base.pxd
rasterio/_base.pyx
rasterio/_crs.pyx
rasterio/_io.pyx
rasterio/_warp.pyx
tests/test_crs.py

I replaced all OSRRelease calls with a call to a wrapper that first checks for NULL, and only passes to OSRRelease if not. I added a test to verify that the previous test of empty CRS does not produce an entry in the log (I'm not that familiar with the details of logging, and basically copied another test of whether values are logged or not, so the purpose of a couple of the lines in the test were not totally clear to me).

Wrap OSRRelease in check for NULL (#1035)

---

docs/topics/masking-by-shapefile.rst

Closes #1095
@perrygeo Didn't you have a linter running against the docs at one point, or was that just docstrings?  I think we were briefly running `doctest` on docstrings but eventually disabled it when the test formatting became painful.  I don't recall if we have ever run anything against the docs though.

Update docs: rasterio.tools.mask.mask() -> rasterio.mask.mask()

---

README.rst

I think the original intent was to insure that homebrew is up to date, not that everything installed by homebrew is upgraded.

Fix 'brew upgrade' -> 'brew update' in README

---

CHANGES.txt
rasterio/io.py
rasterio/merge.py
rasterio/windows.py
tests/test_blocks.py
tests/test_indexing.py
tests/test_io_mixins.py
tests/test_vfs.py

This PR addresses one class of deprecated API usage in the project. We aren't using the deprecated `boundless` keyword argument when calling `windows.from_bounds()` after this.
Resolves #1082
Ping @perrygeo for review.

Eliminate use of deprecated boundless keyword

---

CHANGES.txt
rasterio/_base.pyx
rasterio/block.py
rasterio/errors.py
requirements-dev.txt
requirements.txt
setup.py
tests/test_blocks.py

block() returns the window and size in bytes of a TIFF block. The size is undefined for other formats and will be None.
Resolves #1077 
Ping @perrygeo for review.

Add a block() method to dataset objects.

---

rasterio/_copy.pyx
tests/conftest.py
tests/test_copy.py

Resolves #1107 
We were not closing the destination dataset after copy operation in Cython.  The default setting for the `strict` parameter was also not helping us here; it defaults to allowing incompatible destination rasters to be created silently.  I changed the default so that it raises an exception by default.
We may want to wrap the exception we get back to be return a better Python Exception class instead of `rasterio._err.CPLE_NotSupportedError`
Currently this branch is causing segfaults in a completely unrelated part of `rasterio` on OSX.

Properly close destination dataset after copy operation

---

rasterio/rio/info.py
tests/test_rio_info.py

Resolves #1108 
Dropped exception handling from `rio info` since we weren't doing anything with the exception, and aborting in `click` masked the issue.  This and line 77 are the only changes to `info.py`, not sure why the change in whitespace is showing up as a major change in this PR.
One test case needed to be updated because now an exception is raised.
Also improved basic test of `rio info`

Fix abort in rio info on float.tif and improve tests

---

docs/topics/resampling.rst

We ran into this issue: https://github.com/mapbox/rasterio/issues/860 (using `resample=` instead of `resampling=` and this silently being ignored), but apparently we did this based on a typo in the docs. This PR fixes that.

DOC: wrong keyword in resample example

---

CHANGES.txt
docs/topics/migrating-to-v1.rst
rasterio/io.py

Its functionality is entirely covered by the `xy()` method and deprecation has been warned for a year in preparation for its deletion.
Resolves #1100

Remove deprecated ul() method from TransformMethodsMixin class

---

rasterio/__init__.py
rasterio/_base.pyx
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/io.py

As mentioned in #1046, the intent of this PR is to move the initialization of datasets and their GDAL dataset handles entirely to `__init__()` from `start()` so that we fail sooner and (ideally) never have partially-initialized and useless datasets in our programs.
There's a bit of duplicated code. I feel like a perfect refactoring is blocked by the `BufferedDatasetWriter` class, but don't intend to rewrite that in this PR.
The `__init__()` methods of dataset classes should now do 3 different things in the following order:
1. validation of arguments
2. creation and initialization of a `GDALDatasetH` dataset handle.
3. setting of Python attributes derived from the dataset handle.
I'll ping a couple of you for review when my work is done.

No more work done in dataset start()

---

rasterio/mask.py

The window attributes `num_row`/`num_col` were deprecated in #1074.

Use height/width instead of num_row/num_col in mask

---

.travis.yml
scripts/travis_gdal_install.sh

resolves #1146 
Travis-CI recently moved to Ubuntu 14.04 as the default image, instead of 12.04 (https://blog.travis-ci.com/2017-08-31-trusty-as-default-status)
Unfortunately, this caused negative interactions between `libpng` and the `zlib` that it depends on.
I tried lots of alternatives, like forcing use of 12.04, installing `zlib`, etc.  The most expedient fix ended up being to use GDAL's internal PNG support.
Someone with more experience building GDAL on Ubuntu 14.04 may be able to come up with a better long term solution.

Fix Travis builds on Ubuntu 14.04

---

rasterio/plot.py
tests/test_plot.py

This adds a `normalize` function to `show` so that bands of the raster are normalized between 0 and 1. This makes it possible to visualize them as images. It'd be easy to extend this in the future to other kinds of normalization (e.g. log-spacing), but I don't think it's necessary for this PR.

plot normalization

---

rasterio/plot.py
tests/test_plot.py

I noticed that the function `reshape_as_image` wasn't being called if I explicitly passed 3 bands to my `rio.plot.show` function. This was causing `imshow` to break. This PR adds that in, as well as a test for it. It also removes the indentation on some of the other `with` statements in that block because it seemed like they were inadvertently indented one extra tab, but LMK if that was intentional and I can revert.

fixing read imshow

---

rasterio/features.py
rasterio/mask.py
rasterio/rio/mask.py
tests/test_features.py
tests/test_mask.py
tests/test_rio_features.py

Mask function now returns an `numpy.ndarray` instead of `numpy.ma.MaskedArray`.
I overhauled logic flow in `mask()` so that masked bounds, etc were only evaluated if `clip` is `True`; it was unnecessary otherwise.
I overhauled the tests to make really sure that they were working properly, and to only test a single option at a time.
I also updated the docstring to better match what the function was doing.
`pad` option functionality does not seem to be working properly, and the prior test case did not appear to catch that.  I made one fix, but it looks like our new functionality around windows may be introducing a bug here.  Since that is out of scope of this particular fix, I left that test as an `xfail` instead.
I'd appreciate it if someone more familiar with what the `pad` option is …

Fix mask return type and overhaul tests

---

rasterio/_warp.pyx
rasterio/vrt.py
rasterio/warp.py
requirements-dev.txt
tests/test_warp.py
tests/test_warpedvrt.py

Resolves #1140 by making src/dst_nodata consistent across `WarpedVRT` and `reproject()`. When this PR is merged they will have the same sense, same defaults, same docstrings.

WarpedVRT and reproject nodata alignment

---

rasterio/_fill.pyx
rasterio/fill.py
requirements-dev.txt
tests/test_fillnodata.py
tests/test_rio_calc.py

This PR resolves #1138.
It removes the advice that source nodata values are used, which was not true, and won't be implemented. It also removes support for filling dataset bands in-place, a feature which was not tested, not correctly implemented, and not in line with the rasterio philosophy (separation of raster data I/O from operations on arrays).
If we pass a `MaskedArray` as the sole argument to `fillnodata()`, the inverse of its mask will be filled.

Fix fillnodata docs, intent, and tests

---

.travis.yml
scripts/travis_gdal_install.sh

- I doubt compat with GDAL 1.9 is needed nowadays
- Addition of test against GDAL trunk (with a allow_failures), to detect
either GDAL bugs or integration issues at earliest stage. GDAL is rebuilt
if the revision changed, otherwise the cached build is used

.travis.yml: remove GDAL 1.9 builds, and add GDAL trunk builds

---

rasterio/_warp.pyx

This will make GDALCreateWarpedVRT() to avoid selecting Float64 data type
whereas Byte or UInt16 that have many optimizations are just needed

create_warp_options(): do not set nodata value when there's none

---

rasterio/_warp.pyx
tests/test_warp.py

Resolves #1131 
The test originally failed for me until I removed the unused array from `_warp.pyx`.

Removed unnecessary array causing MemoryError in calculate_default_transform()

---

CHANGES.txt
rasterio/__init__.py
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/io.py
rasterio/windows.py
tests/test_read_boundless.py
tests/test_windows.py

Rasterio has offered "boundless reads" as a feature – you can read an image window (in pixel space) that goes beyond the source raster's rows and columns and rasterio performs VRT-like source reading and compositing. The math has been buggy: at best it doesn't exactly match GDAL's math and, at worst, can drop a line or row of data.
This PR fixes the bug by switching from an approximation of GDAL's VRT logic to the use of a temporary VRT that represents the boundless window. It provides more accurate and reliable results and eliminates 2 chunks of brittle code in _io.pyx.
I'm using a warped VRT because GDAL doesn't surface a non-warped VRT constructor in its C API. As far as I can tell, reprojection is short-circuited when the input and output crs are the same. I think this is good enough …

Switch to warped vrt internally for boundless reads

---

rasterio/merge.py
rasterio/rio/edit_info.py
tests/test_rio_info.py

I want to merge some `float32` files that have `nodata=None` and contain `NaN` for missing values.
However, `merge` does not support `np.nan` as a nodata flag, because it uses comparison to validate the nodata value:
https://github.com/mapbox/rasterio/blob/89538636ff92112848a888e314bea8f457e3a30b/rasterio/merge.py#L117
and to test whether the existing data (`region`) is empty:
https://github.com/mapbox/rasterio/blob/89538636ff92112848a888e314bea8f457e3a30b/rasterio/merge.py#L171
If the `nodata` value is `np.nan`, accept it as valid for floating point data and use `np.isnan` to check whether the `region` is empty.
Also, for floating point data, if `nodata` is `None`, set it to `np.nan` per default. This part is perhaps too auto-magic, one could also leave it up to the user to specify …

merge: treat nodata=None and np.nan in data

---

README.rst

Added a link to bottom of README that links to rasterio page on Libraries.io, which shows the projects that depend on rasterio.
https://libraries.io/pypi/rasterio/usage

Add Libraries.io link to README to show projects that depend on rasterio

---

rasterio/_features.pxd
rasterio/_features.pyx
rasterio/features.py
tests/conftest.py
tests/test_features.py
tests/test_warp.py

Resolves #1172 
This PR helps ensure that we catch invalid geometries sooner, before we pass them to GDAL and get a segfault.
Doing so involved adding a lightweight test of `GeoJSON` validity.  Note: unlike the GeoJSON spec, here an empty `GeometryCollection` is considered invalid.  (technically we don't need to consider it invalid, but then would need a later check that it is non-empty).

Prevent segfaults in rasterize

---

rasterio/io.py
rasterio/transform.py
rasterio/vrt.py
rasterio/windows.py
tests/test_io_mixins.py

The Mixin classes were in io, and imported within the vrt module,
but the io module also imported the vrt module (within _io). This
worked when copy was being imported before io in `__init__`, but removing
that import from `__init__` produced a circular import.
This addresses #1174, and should permit the necessary import removal for #1173 (at least I can remove the copy import from `__init__` without issue on this branch). cc @geowurster

Remove potential circular import path

---

.gitignore
pytest.ini
rasterio/__init__.py
rasterio/_io.pyx
setup.cfg

`pytest` logs can get pretty noisy.  This PR migrates some `UserWarnings` to Rasterio warnings so we can safely ignore _only_ the Rasterio warnings and still be alerted of any other warnings.

Shush test warnings

---

rasterio/_io.pyx
rasterio/_warp.pyx

This way, `WarpedVRT` has an effective CRS of `dst_crs` rather than `None`, enabling boundless reads.
Fixes #1186

Override get_crs() in WarpedVRT to return dst_crs

---

rasterio/_io.pyx
rasterio/features.py
tests/test_features.py

Added checks for height and width > 0 for `InMemoryRaster`.  Resolves #1144.
Turns out this extension class is fairly difficult to test directly.  However, I added additional tests of invalid inputs for `geometry_mask` which test the underlying fix.  
Will look for other places where we should add validation of image shape in the python layer, perhaps in `rasterize`.

Raise error on invalid shape for InMemoryRaster

---

CHANGES.txt
rasterio/__init__.py
rasterio/_base.pyx
rasterio/_io.pyx
rasterio/_shim.pxd
rasterio/_shim1.pyx
rasterio/_shim20.pyx
rasterio/_shim21.pyx
rasterio/errors.py
rasterio/gdal.pxi
rasterio/io.py
tests/test_deprecated.py
tests/test_open_options.py

A WIP toward resolving #1000 and #1158.
TODO:

Switch to GDALOpenEx for fine driver control

---

rasterio/_features.pyx
rasterio/enums.py
rasterio/features.py
tests/conftest.py
tests/test_features.py

This PR exposes the `MERGE_ALG=ADD` option of GDALRasterizeGeometries instead of the default `MERGE_ALG=REPLACE`.

Merging option ADD to the rasterize feature

---

rasterio/features.py

this fixes a small (but annoying) bug in geometry_window().
(annoying because it causes rasterio to thing a shape is out of bounds for a raster when using mask(raster, shapes) when it is not)

fix bug: raster width/height was swapped

---

CHANGES.txt
rasterio/_env.pyx
rasterio/_io.pyx

We had inadvertently copied all exceptions into the logger.

Don't automatically log GDAL exceptions

---

tests/test_rio_edit_info.py

This removes the line creating "NOCI.tif" from `test_rio_edit_info.py`.  This line had no apparent side-effects, and was creating an unversioned, unignored file.

Removed spurious line creating NOCI.tif from test

---

.travis.yml

Released a [few days ago](https://trac.osgeo.org/gdal/wiki/Release/2.2.3-News).

Add GDAL 2.2.3 to the build matrix

---

rasterio/env.py
rasterio/warp.py
tests/conftest.py
tests/test_blocks.py
tests/test_colorinterp.py
tests/test_crs.py
tests/test_env.py
tests/test_memoryfile.py
tests/test_open_options.py
tests/test_read_resample.py
tests/test_rio_edit_info.py
tests/test_rio_info.py
tests/test_rio_mask.py
tests/test_rio_merge.py
tests/test_subdatasets.py
tests/test_update.py
tests/test_warp.py
tests/test_warpedvrt.py

Resolves #1209 
Opted for a very simplistic parsing of GDAL version number and a few helpers wrapped into a class.
Leveraged pytest test skipping using helpers in `conftest.py` to centralize and make more semantic tests that vary based on GDAL version.
There are a couple of `xfail` marked tests that maybe should be skipped instead, I flagged those for consideration.

Make GDAL version checking more consistent

---

tests/test_crs.py
tests/test_features.py
tests/test_memoryfile.py
tests/test_rio_mask.py
tests/test_rio_merge.py
tests/test_warp.py

This skips GDAL version dependent tests instead of xfailing them.
It also removes `xfail` marks from tests that were not failing on any of our Travis builds.
I slightly refactored the testing of the xfailing resampling tests to only xfail those specific methods that were failing.

Reduce xfailing tests

---

.travis.yml
README.rst
docs/installation.rst
setup.py
tests/conftest.py
tests/test_rio_edit_info.py
tests/test_rio_info.py
tests/test_warp.py

This resolves #1218 and starts to pave the way for more standardized handling of functionality with respect to GDAL version by eliminating early versions that do not support full use in `rasterio`.
This PR adds a check to `setup.py` that prevents installation with GDAL < 1.11.  This feels a bit bold to me, but the hope is that it prevents users from encountering errors due to running an unsupported version of GDAL.
This also removes tests for versions < 1.11 that are now no longer needed.

Increase required GDAL to 1.11

---

setup.py

**This PR cannot be merged unless the GDAL trunk tests on Travis pass.**
Closes #1230 
I don't know a lot about compiling C++, but [StackOverflow](https://stackoverflow.com/questions/19246783/are-c11-containers-supported-by-cython) suggests this is all we need to do.  I ran some local tests against a version of GDAL pretty close to trunk and hit some failures, but they may just be GDAL changes.  I'll investigate.

[WIP] Add C++11 flag when compiling against GDAL>=2.3

---

docs/topics/windowed-rw.rst
rasterio/windows.py
tests/conftest.py
tests/test_windows.py

So far, this has mostly added more extensive tests of `Window` class.
This includes a moderate refactor of `Window.from_slices` to add support for `list` as input type, expand validation of inputs, and restructure logic so that it is easier to follow.
Writing good tests for `boundless=True` is still proving difficult; we could probably use a bit more documentation on how to use `boundless` correctly.
The goal of this eventually is to have a solid enough test suite that we are comfortable removing use of epsilon as per #1139

Refactor Window.from_slices

---

docs/topics/plotting.rst
rasterio/_features.pyx
rasterio/features.py
rasterio/mask.py
rasterio/merge.py
rasterio/plot.py
rasterio/rio/blocks.py
rasterio/rio/insp.py
rasterio/rio/merge.py
rasterio/rio/sample.py
rasterio/shutil.pyx
tests/test_rio_blocks.py
tests/test_rio_merge.py

Naming raster / source / dataset

---

rasterio/compat.py
rasterio/enums.py
rasterio/env.py
rasterio/errors.py
rasterio/rio/warp.py
rasterio/warp.py
tests/test_env.py
tests/test_rio_warp.py
tests/test_warp.py

Resolves #1208
This introduces a new decorator for functions to require at least a certain version of GDAL: `@require_gdal_version`, and applied it to `reproject` to ensure that resampling methods not yet supported by the runtime version of GDAL (if <2.0) raise an appropriate exception.  If we like this approach, we can introduce this in other places where we need to guard certain functions, parameters, or parameter values for specific versions of GDAL.
Introduces a new error `GDALVersionError` to indicate cases where the runtime version of GDAL is not sufficient.
Some filtering of the `Resampling` enum is used to limit the choices of resampling methods offered to the user by `rio warp` so that they are only those supported by their runtime version of GDAL.
Added more `reproject` tests to …

New decorator for requiring specific GDAL version

---

tests/README.rst

Fix link to TravisCI CloudFormation IAM template in tests README.

Fix link to TravisCI CloudFormation IAM template

---

docs/api/index.rst
rasterio/_io.pyx
tests/test_boundless_read.py

I'm proposing a new test of boundless reads. The test asserts that a boundless read with no resampling (nearest neighbor, in other words) from our testing dataset gives the same results as a not-boundless read. For example, do boundless read with a window 1 pixel larger on every side. We expect that the interior of this read would be the same as a not-boundless read.
The `WarpedVRT` usage change is adapted from #1238. @ungarj: could you check this out and let me know if it matches your expectations?

Boundless reads that don't alter pixels

---

rasterio/_io.pyx
tests/test_mask_creation.py

Support for windowed mask writes on internal GeoTiff bit masks. Only call `GDALCreateMaskBand` if we don't already have a per_dataset mask.
We have an existing test for this functionality - removed the `xfail` decorator as this should now pass.
resolves #895
cc @sgillies

support writing windowed internal masks

---

rasterio/rio/options.py

Since rasterio.shutil.exists attempts to open files w/ GDAL, it needs to be fed a VFS URI lest e.g. zip files (`zip://archive.zip!image.tif`) will be opened without providing the inner path, resulting in read failures (if multiple files are present, among other reasons).

Construct path before checking for existence

---

rasterio/_base.pyx

This pull request adds an optional parameter `sharing=True|False` to `open` method when used in read-only mode. Default value is `True` meaning that files will be opened with `GDAL_OF_SHARED` flag set (matches existing behaviour), however if user passes in `sharing=False` files will be opened without `GDAL_OF_SHARED` bit set.
Motivation for this feature is to support multi-threaded programs that want to read from the same resource concurrently. According to gdal threading model one has to open new dataset for each concurrent thread accessing the dataset.
**Note**: I have not added any documentation.
closes #1256

Optionally disable sharing on open

---

rasterio/features.py
tests/test_features.py

Resolves #1253 
Apparently, GDAL creates holes where parts of a `GeometryCollection` overlap, whereas it creates no holes when parts are submitted individually.  To avoid holes, we simply extract out the parts of the `GeometryCollection` prior to rasterize.

Flatten GeometryCollection to individual parts to avoid holes in output

---

rasterio/_io.pyx
rasterio/merge.py
rasterio/rio/merge.py
rasterio/rio/options.py
rasterio/rio/stack.py
tests/test_rio_merge.py

Sorry for bombarding you with PRs... 
This one adds the `indexes` parameter to `rasterio.merge.merge`, equivalent to the PR you just merged for `rasterio.mask.mask` (#1225).
I also added the functionality to `rio merge` as a `--bidx` parameter.

add indexes / bidx parameter to merge

---

rasterio/_features.pyx
rasterio/features.py
rasterio/mask.py
tests/conftest.py
tests/test_features.py

This commit proposes a strawman fix for mapbox/rasterio#1240 .
A test is included as well, and it uses new test fixtures to demonstrate the issue.
I believe this is the cleanest way to address the issue, though the transform round-trip is not particularly elegant.
Looking forward to hearing your thoughts!

Address Mask Error with Rotated Datasets

---

CHANGES.txt
docs/topics/virtual-warping.rst
rasterio/_warp.pyx
tests/test_warpedvrt.py

Closes #1198 via some documentation.
I also discovered that when a `WarpedVRT()` is instantiated with `dst_height`, `dst_width`, and `dst_transform` calls `GDALCreateWarpedVRT()`, which does not have a CRS parameter, thus the resulting dataset handle lacks a CRS..  Users interacting with `WarpedVRT.crs` get a cached object, but flushing the data to disk via GDAL's copy mechanism (`rasterio.shutil.copy()`) receives the dataset handle provided by `GDALCreateWarpedVRT()` and creates a new dataset without a CRS.  The solution is to add a CRS to the new dataset handle as soon as it is created.  I also added a test for this specific condition.

WarpedVRT bugfix and recipe for normalizing data against a known grid

---

rasterio/features.py
rasterio/rio/shapes.py

resolves #1282 
This PR moves the rio shapes functionality to a Python generator function.
`rasterio.features.dataset_features` is a generator function for the geojson features themselves.
`rasterio.rio.shape.feature_gen` wraps them in a Collection object, an implementation detail of the `write_features` helper.
TODO
* ~[ ] proper unit tests. The code is currently tested only via the CLI tests.~
@sgillies can you give this a prelim review?

rio shapes functionality as a python function

---

rasterio/__init__.py
tests/test_open.py

This allows to use pathlib.Path objects in rasterio.open(), alongside string paths and file objects, as also suggested in #1016.
Example:
```
with rasterio.open(Path.cwd() / 'myimage.tif') as r:
data = r.read()
```

Support for pathlib.Path in rasterio.open()

---

CHANGES.txt
rasterio/__init__.py
tests/test_blocks.py

closes https://github.com/mapbox/rasterio/issues/1115
This PR removes:
- eval_window
- window_shape
- window_index 
from `rasterio/__init__py`

Remove eval_window() etc from __init__.py

---

rasterio/_io.pyx
tests/test_memoryfile.py

It's turning out to be buggy and we don't need it. Users can convert to `bytes` as we're doing in the tests.

No more bytearray input for MemoryFile

---

rasterio/merge.py

The precision argument was still in the keywords for `merge.merge`, but wasn't being used anywhere.
I had a difficult time devising a test without adding new test fixtures. One possibility that did occur to me was setting a very low precision, attempting a merge, and verifying that it throws an exception when there's a size mismatch. I'd be happy to do so if that seems desirable.
There's potential for more change along these lines, with respect to rounding the window sizes and offsets. However, this particular fix on its own addressed the issue I ran into.

Pass precision to from_bounds in merge

---

rasterio/rio/calc.py
rasterio/rio/helpers.py
rasterio/rio/mask.py
rasterio/rio/merge.py
rasterio/rio/options.py
rasterio/rio/rasterize.py
rasterio/rio/stack.py
rasterio/rio/warp.py
tests/test_rio_helpers.py
tests/test_rio_merge.py
tests/test_rio_rasterize.py

This addresses #1181.
I do not believe -f is actually being used anywhere in the code as short for --force-overwrite. And now the only instances of --force-overwrite are in the CHANGES file.
I just chose a simple issue to get back up and running on this code. Not sure if it needs anything more, but seems to be good.

Refactor --force-overwrite to --overwrite.

---

CHANGES.txt
rasterio/_env.pyx
tests/test_env.py

Also switch to `CPLSetConfigOption` for `GDAL_DATA` instead of modifying process environment.
The `test_env.py` needed its expectations adjusted and I fixed some pep8 nits while I was in there.
Resolves #1337

Check version-dependent GDAL directory for GDAL data

---

rasterio/enums.py

The `quay.io/repository/gdal:trunk` Docker image now includes ZSTD support (after https://github.com/mojodna/docker-gdal/commit/558f134b844ac52697acd8da50a70e979584a9b2).
rasterio can be built against it fairly easily by changing https://github.com/mojodna/marblecutter-tools/blob/master/requirements.txt#L4 and building with `docker-compose build` in a marblecutter-tools working directory.

Add an enum for ZSTD compression

---

CHANGES.txt
rasterio/_features.pyx
rasterio/_io.pxd
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/features.py
rasterio/warp.py

GDAL geotransform arrays are constructed and passed to GDAL functions, but Rasterio functions and methods, even the private ones, always take instances of Affine.
Resolves #796.

GDAL geotransform arrays are never passed to Rasterio funcs

---

CHANGES.txt
rasterio/_crs.pyx
rasterio/_warp.pyx
rasterio/crs.py
tests/test_crs.py
tests/test_rio_warp.py
tests/test_warpedvrt.py

1.0b1 introduced a change in how CRS objects are compared to other objects, removing the ability to compare them to strings. We've restored this, but deprecated such usage: in 1.0 we're going to require tests like `CRS('EPSG:4326') == CRS('EPSG:4326')` and disallow `CRS('EPSG:4326') == 'EPSG:4326'`.
The WarpedVRT class and its tests needed to be updated to the new usage.
I've added a new CRS classmethod, `from_user_input` (analogous to the GDAL API function) that will make a CRS from almost any kind of input you'll see on the command line. It's used in the WarpedVRT constructor.
Moving the classmethods to the base _CRS class seemed appropriate as I was developing the new function.
I've also added a feature to the `from_string` class method: it will now accept WKT strings.

CRS bug fixes, new features, and deprecations

---

rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/rio/insp.py
rasterio/shutil.pyx
rasterio/vrt.py
tests/test_boundless_read.py
tests/test_vrt.py
tests/test_warpedvrt.py

This resolves #1266.
We're no longer using WarpedVRT internally and I've removed some features added to the class that were intended to support boundless reads and haven't been needed otherwise.

VRT XML implementation of boundless reads

---

docs/cli.rst

Related to https://github.com/mapbox/rasterio/issues/1413

Add example of using rio warp for south-up images

---

rasterio/rio/warp.py
tests/test_rio_warp.py

In case of `dst_crs` is not set.

Allow src_bounds to override src.bounds with --dimensions

---

rasterio/_warp.pyx
tests/test_warp.py

This is addressing issue #1350. 
Basically warping for cases other than
- Warping first band
- Warping all bands
didn't work, because of the way warping structure was configured. With this change we actually populate `pan{Src|Dst}Bands` parameters properly.
Also when destination is an `ndarray` and there are multiple bands being processed destination bands are assumed to be `1,2,..N` if the output size matches the number of bands being processed simultaneously. So you can extract say bands `4,7,19` into a `3xHxW` `ndarray`.

Populate `pan{Src|Dst}Bands` indexes when reprojecting

---

rasterio/io.py
tests/test_write.py

Fixes issue #1203. Though likely will be superseded by #265

added ValueError if driver is missing when getting writer for driver

---

CHANGES.txt
rasterio/env.py
rasterio/rio/env.py
rasterio/rio/rasterize.py
tests/test_env.py
tests/test_rio_rasterize.py

This refactor resolves #1423. Summary of changes:
- We have a new session module and an extendable abstraction for cloud API access sessions. Adding support for a new cloud provider means writing a new subclass of `Session` (like `AWSSession`) and then adding a new condition to the `from_path` staticmethod of `Session`.
- With two exceptions, the `Env` class doesn't know about subclasses of `Session` anymore. Except for the special AWS cases (for backwards compatibility) it should only know about abstract Sessions.
- The duty of figuring out which kind of session to use for a given dataset path or identifier now belongs to `Session.from_path`. I expect it could become slightly complex, but at least we're containing the complexity.
The deep nesting of sessions gets a little humorous, I …

Generalize to support cloud providers other than AWS

---

CHANGES.txt
rasterio/_io.pyx
tests/test_boundless_read.py

There seems to be a conflict between VRTs, overviews, and masks, so instead of asking GDAL's VRT driver to do the filling, we ask dataset.read to make a masked array and then call `filled()` on it to collapse it to a filled non-masked array.
Resolves #1471

Really, really resolve #1471

---

rasterio/_io.pyx
rasterio/io.py
tests/test_memoryfile.py

A user pointed out in https://rasterio.groups.io/g/main/message/66 that r and w are too restrictive.

Make default modes r+ and w+ for MemoryFile datasets

---

rasterio/_base.pyx
tests/test_tag_item.py

Allow querying tags for the first overview (`ovr=0`)
addresses #1490

Fix get_tag_item for the `ovr=0` case

---

README.rst

I think this info should be front and center. Would make it easier for Windows users.

Add rasterio option to Windows installation instructions

---

rasterio/enums.py

To support GDAL 2.4.0-dev and the upcoming [Tiff WebP compression](https://github.com/OSGeo/gdal/pull/704)

Add WEBP to the compression enum

---

CHANGES.txt
rasterio/_warp.pyx
tests/test_warpedvrt.py

We've changed the constructor's nodata defaults to use a flag that is neither None nor a float.
Passing `src_nodata=None` and/or `nodata=None` unlocks a missing feature or avoids a bug, depending on how you look at it. Accepting the default preserves the existing behavior, inheritance of the nodata values from the VRT's source dataset.
Resolves #1503

None means none, not default

---

rasterio/plot.py

@sgillies this is a very minor update to the docstring for `plotting_extent()` [as discussed here](https://github.com/mapbox/rasterio/issues/1514):  Please let me know if you'd prefer different text or any changes to what is there.
I looked at your docs and *think* that docs for [this particular function](https://rasterio.readthedocs.io/en/latest/api/rasterio.plot.html?highlight=plotting_extent) are autogenerated from the docstring. If I am not correct I can also update the `.rst` file with just a bit of direction.

Docstring update to plotting_extent - Minor Update 

---

rasterio/windows.py

`floor` and `ceil` don't round to the nearest whole number, but instead to either the preceding or succeeding integer.
Though in making this PR I wonder if there's a reason not to support `round` as well.

Clarify window rounding documentation

---

CHANGES.txt
rasterio/_io.pyx
rasterio/vrt.py
tests/test_vrt.py

Per conversation in https://github.com/OSGeo/gdal/issues/1135, GDAL doesn't read the VRT source dataset of a complex source when the scale ratio is set to 0. This makes a bunch of complicated code in rasterio._io obsolete and reverses a performance regression noted in #1499.

Exploit VRT complex source scale ratio 0 optimization

---

rasterio/_io.pyx

The following simple example fails with rasterio-1.0.12 on 64-bit Python, Windows:
```Python
import rasterio
with rasterio.open('RGB.byte.tif') as src:
r, g, b = src.read()
```
```
File "example.py", line 3, in <module>
r, g, b = src.read()
File "rasterio\_io.pyx", line 339, in rasterio._io.DatasetReaderBase.read
File "rasterio\_io.pyx", line 689, in rasterio._io.DatasetReaderBase._read
ValueError: Buffer dtype mismatch, expected 'Py_ssize_t' but got 'long'
```

Fix "ValueError: Buffer dtype mismatch" on win_amd64

---

CHANGES.txt
rasterio/_base.pxd
rasterio/_base.pyx
rasterio/io.py
rasterio/vrt.py

Prevents bugs when datasets are opened and passed to other functions.

Add anonymous Env in DatasetBase.__enter__ if needed

---

docs/quickstart.rst

band1 is defined earlier in the walkthrough but band_one is not. Calling band_one[row, col] results in an error. Changed band_one to band1.

band_one is not defined in the walkthrough

---

rasterio/_io.pyx

I believe there was a typo preventing drivers lacking the `create` method from storing GCPs. This fixes #1600 .

Include GCPs in BufferedWriter drivers

---

rasterio/__init__.py
rasterio/_base.pyx
rasterio/_io.pyx
rasterio/dtypes.py
tests/test_write.py

Signed 8-bit images are somewhat "second-class" in GDAL, but it can read/write them nevertheless.
Even though GDAL only has unsigned `GDT_Byte` raster data type, signed vs unsigned
images can be differentiated via `PIXELTYPE` property. It is set to `SIGNEDBYTE`
for signed 8-bit file. This is how GDAL's native python binding compute `numpy.dtype` from dataset object:
https://github.com/OSGeo/gdal/blob/90dde4a3fc0d89373a62000ae14e424fc41f7306/gdal/swig/python/osgeo/gdal_array.py#L299-L300
Similarly, on output side, setting option `PIXELTYPE='SIGNEDBYTE'` when creating file with `GDT_Byte` dtype will generate signed int8 image.

Add support for signed 8 bit images

---

rasterio/gdal.pxi

It is not used in and .pyx file, and no longer exists in GDAL 2.5

Remove OSRFixup() from rasterio/gdal.pxi

---

CHANGES.txt
rasterio/crs.py
tests/test_crs.py
tests/test_profile.py

Resolves #1625 
What do you think of this @darrenleeweber? 
I have no plan for long-lived pickles as referred to in https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled:
>  If you plan to have long-lived objects that will see many versions of a class, it may be worthwhile to put a version number in the objects so that suitable conversions can be made by the class’s `__setstate__()` method.
We don't need them for multiprocessing.

WKT based CRS pickle protocol

---

CHANGES.txt
rasterio/_crs.pyx
rasterio/crs.py
rasterio/gdal.pxi
tests/test__crs.py
tests/test_crs.py

What do you think @appanacca? Is getting the name of the linear units enough? There's a Python package named "pint" that provides normalization and unit conversion, so we don't necessarily need to expose the number of metres per unit.

First swing at resolving #1634

---

CHANGES.txt
rasterio/_base.pyx
rasterio/gdal.pxi

This gets us support for uncommon `KEY:VALUE` metadata and makes rasterio more like gdalinfo.

Use CPLParseKeyValue on metadata items

---

CHANGES.txt
rasterio/__init__.py
rasterio/session.py
tests/test_session.py

Even if requests are unsigned.
Resolves #1670

Allow AWS region name to be specified in all cases

---

rasterio/path.py
rasterio/session.py
tests/test_env.py
tests/test_session.py

Refer to #1543 
This PR based on the latest master branch, and add tests code with mock.
Three methods are possible is use:  
1.  Create session by the swiftclient library.
2.  The SWIFT_STORAGE_URL and SWIFT_AUTH_TOKEN (this method is recommended by GDAL docs).  
3.  The SWIFT_AUTH_V1_URL, SWIFT_USER and SWIFT_KEY (This depends on the [swiftclient library](https://github.com/openstack/python-swiftclient)).  
``` python
>>> import rasterio
>>> from rasterio.session import SwiftSession
>>>
>>> fp = 'swift://swift/test_cog.tif'
>>>
>>> def test_open_private_swift_file_session():
... #     1. Create session by the swiftclient library.
...     from swiftclient.client import Connection
...     conn = Connection( authurl='http://127.0.0.1:7777/auth/v1.0',user='test:tester',key='testing')
... …
```

Add support for OpenStack Swift Object Storage(cloud optimized geotiff)  with tests

---

.travis.yml
rasterio/features.py
tests/test_features.py

Resolves #1675 
Instead of raising `ValueError` on first instance of an invalid geometry that a user tries to rasterize, we simply omit them from rasterization and omit warnings instead.  If there are no valid geometries after screening out invalid geometries, then an exception is raised.
This also adds support to the `is_valid_geom` function to work for both GeoJSON and objects with the geo interface.
Note: this also includes an additional flag for the `pip` install used in Travis-CI, to get builds working again.  The same issue is present on other recent builds from master.

Warn on rasterizing invalid / empty geometries instead of failing

---

rasterio/_crs.pyx
rasterio/crs.py
tests/test_crs.py

Added a property to the CRS class that return a tuple with the raster unit and the conversion factor to meters, if the CRS is a projected one.

Get linear units

---

CHANGES.txt
rasterio/_io.pyx
tests/test_dataset.py

Block size guards are not needed for untiled datasets

---

CHANGES.txt
rasterio/_base.pyx
rasterio/errors.py
tests/test_dataset.py

On attempts to modify datasets opened in read-only mode
Resolves #1676

Raise DatasetAttributeError instead of NotImplementedError

---

CHANGES.txt
rasterio/rio/calc.py
tests/test_rio_calc.py

Resolves #1668
The gist: we have a new `--mem-limit` option which defaults to `64` (megabytes). For very large calculations, we divide the work into square-ish regions such that the calculation results of these regions are no larger than the memory limit. For example, to run `rio calc "(asarray (read 1 1), (* (read 1 2) 1.1), (read 1 3))"` (boosts the green band of an RGB image by 10%) on a 7000 x 7000 pixel 3-band uint8 dataset *without* chunking would require `--mem-limit=148`. With the default 64 MB memory limit, the work would be done in 4 chunks.

Perform calculations on blocks determined by a working memory limit option

---

rasterio/mask.py
tests/test_mask.py

This allows users to pad a mask by a variable width instead of force-defaulting to the fixed 0.5 width

Allow for variable-width padding on masks

---

.travis.yml
CHANGES.txt
rasterio/_base.pyx
rasterio/_crs.pyx
rasterio/_shim.pxd
rasterio/_shim1.pyx
rasterio/_shim20.pyx
rasterio/_shim21.pyx
rasterio/_shim30.pyx
rasterio/rio/clip.py
tests/conftest.py
tests/test__crs.py
tests/test_crs.py
tests/test_rio_warp.py
tests/test_warp.py
tests/test_write.py

Had to root through the warping tests quite a bit this afternoon. I think the tests using the old projection for Maine were expecting wrong results from GDAL 2. Here's what the GDAL 2.4 output looked like using PROJ 4.9.3:
Here's the output using GDAL 3.0.1 and PROJ 6.1.1
This second one looks much more like a long/lat box projected to transverse mercator, no?
While focusing on the compatibility issues, I'd lost sight of the improvements offered by the new PROJ. Glad to see this :+1:

Maintain traditional axis order strategy everywhere

---

rasterio/plot.py

The class name is matplotlib.axes and not axis according to [this ](https://matplotlib.org/3.1.1/api/axes_api.html)

Correct rasterio.plot.show doc : matplotlib axes and not axis

---

rasterio/compat.py
rasterio/crs.py
rasterio/rio/stack.py
rasterio/transform.py
rasterio/windows.py

This PR finishes eliminating the remaining python deprecation warnings that were thrown by the `collections` module (see https://github.com/mapbox/rasterio/issues/1742)
https://github.com/mapbox/rasterio/pull/1753 had addressed the `Mapping` class, but the `Iterable` class has the same behavior, so this PR addresses it.

Add collections.Iterable to compat

---

rasterio/session.py
tests/test_session.py

This PR adds an `endpoint_url` keyword argument to the `AWSSession` class, in order to give the possibility to nicely interact with non-AWS S3 endpoints (see [discussion](https://rasterio.groups.io/g/dev/topic/34104027#111)).
I have two questions:
- Should I also expose the keyword argument in `rasterio.Env`, by popping it from `options` (like `region_name` [here](https://github.com/mapbox/rasterio/blob/b0c1989ff90353226eafb1d1c8379948ff0ca461/rasterio/env.py#L173)) for example, or not?
- Should I include some tests for `endpoint_url` in `tests/test_env.py`, or is this single test enough?

Non-AWS S3 endpoint

---

rasterio/rio/overview.py
tests/test_rio_overview.py

This PR resolves #1511 
The `get_maximum_overview_level` function was taken from [rio-cogeo](https://github.com/cogeotiff/rio-cogeo/blob/fdda823e836bc9614f522ced349d5e1281fb8706/rio_cogeo/utils.py#L95-L118).
I have a few points on which I would need some guidance:
- In https://github.com/mapbox/rasterio/issues/1511#issuecomment-439127602 @vincentsarago was saying that he was interested in having the `get_maximum_overview_level` function public, for use in `rio_cogeo`. Is it fine where I have put it in `rasterio.rio.overview`, or does it better belong somewhere else in `rasterio`?
- I have taken the default `minsize=256` of [gdaladdo](https://gdal.org/programs/gdaladdo.html#cmdoption-gdaladdo-minsize), but in `rio_cogeo` @vincentsarago has a default of 512. Which best suits `rasterio`?
- …

Automatic overview level computation

---

CHANGES.txt
rasterio/_base.pyx
rasterio/gdal.pxi
tests/test_tag_ns.py

New PR using @vincentsarago's code from #1740. The name of the method has been changed to `tag_namespaces`. The `get` is superfluous.

Metadata namespaces

---

docs/topics/resampling.rst

Fixes #1732.
As @00krishna pointed out in the issue, the current example in the docs for up-/downsampling is broken. The code has some bugs and is missing the important information how to scale the transform after using decimated read.
Here is a similarly simple example that works.
The approach used here and in the original example (decimated read) is fine for upsampling (increasing resolution by a factor). For downsampling, I would normally want to control the target image `transform`, so I would use a `WarpedVRT` instead to be sure that image size and transform match - unless the image dimensions (height and width) are evenly divisible by the resampling factor.
However, in order not to complicate the docs on this issue too much, I suggest to just show decimated read here. The example …

replace broken resampling example with working one

---

rasterio/rio/clip.py
rasterio/rio/convert.py
tests/test_rio_convert.py

I have noticed that the `--overwrite` option was missing from `rio clip` and `rio convert`, even though they use the `resolve_inout` function internally.
This results in the following oddity:
```
$ rio convert tests/data/RGB.byte.tif t.tif -f JPEG
---> This works fine
$ rio convert tests/data/RGB.byte.tif t.tif -f JPEG
Error: Could not open file : file exists and won't be overwritten without use of the `--overwrite` option.
---> This is normal behavior as well
$ rio convert tests/data/RGB.byte.tif t.tif -f JPEG --overwrite
Usage: rio convert [OPTIONS] INPUTS... OUTPUT
Try "rio convert --help" for help.
Error: no such option: --overwrite
---> This is because @options.overwrite_opt is missing from rio convert
```
I have looked for all `rio` subcommands that used `resolve_inout` but that …

Clip convert overwrite

---

rasterio/rio/calc.py

Quick fix. When we error out in the calc try block e.g. because the user did
--name a test.tif
instead of
--name a=test.tif
the cleanup code will fail since dst and sources are undefined.
:wave: Hi lovely pixel people :hugs:

Fixes calc cleanup hard failures when error occurs

---

tests/test_cli_main.py
tests/test_data_paths.py
tests/test_rio_calc.py
tests/test_rio_convert.py
tests/test_rio_edit_info.py
tests/test_rio_gcp.py
tests/test_rio_info.py
tests/test_rio_main.py
tests/test_rio_merge.py
tests/test_rio_overview.py
tests/test_rio_sample.py
tests/test_rio_stack.py

This PR makes the use of the `runner` test fixture consistent throughout all tests instead of having some tests declare their own `runner = CliRunner()` inside the test function.
(see this comment https://github.com/mapbox/rasterio/pull/1836#issuecomment-559016620 for more info)
I also fixed basic linting warnings (unused imports and unused arguments) on the files that I edited for this PR, I hope you don't mind.

Runner fixture

---

.travis.yml

* GDAL 3.0.1 -> <s>[3.0.3](https://lists.osgeo.org/pipermail/gdal-dev/2020-January/051453.html)</s> [3.0.4](https://lists.osgeo.org/pipermail/gdal-dev/2020-January/051582.html)
* GDAL 2.4.3 -> [2.4.4](https://lists.osgeo.org/pipermail/gdal-dev/2020-January/051452.html)
* PROJ 6.1.1 -> <s>[6.3.0](https://lists.osgeo.org/pipermail/proj/2020-January/009178.html)</s> [6.2.1](https://lists.osgeo.org/pipermail/proj/2019-November/008968.html)

Upgrade Travis CI testing against latest GDAL and PROJ releases

---

rasterio/compat.py
rasterio/errors.py
rasterio/path.py
rasterio/rio/options.py
tests/test_path.py
tests/test_rio_info.py
tests/test_rio_options.py

Resolves #1786
Has a small consequence for the CLI file_in_handler: we can no longer fail early on some kinds of given paths.

Rewrite path parsing logic to handle "SENTINEL2_L1C:" paths

---

rasterio/plot.py

With Python 3.8 the following `SyntaxWarning` is shown:
```
SyntaxWarning: "is" with a literal. Did you mean "=="?
```

Fix SyntaxWarning

---

rasterio/_io.pyx
rasterio/_warp.pyx

GDAL treats signed byte data in a special way, there is only one 8-bit data type GDT_Byte, unsigned by default. To represent signed version one needs to set PIXELTYPE='SIGNEDBYTE'. When int8 support was added in #1595 InMemoryRaster class was not adjusted to support int8 inputs. Calls to GDALCreate need to include options dictionary.
Closes #1878.
There was also missing assignment in `_warp.pyx`, which I think is an omission.

Properly declare int8 pixel types to GDAL

---

docs/topics/resampling.rst

This PR fixes what I think is a mistake in the example given in the resampling documentation: `data.shape` contains `(count, height, width)`, hence my fix.
I also took the opportunity to add sphinx autodoc links to this documentation page to make the navigation easier.

Resampling docs typo

---

rasterio/__init__.py
rasterio/_io.pyx

Match the order of docstring parameters to the argument order. Text otherwise remains the same.

Move docstring for dtype parameter to correct position

---

rasterio/_features.pyx
rasterio/features.py
tests/test_features.py

Resolves #1914
`GeometryCollection` geometries were not previously supported due to an oversight.
This adds support for calculating `bounds()` of a `GeometryCollection` and adds additional validation of the geometry type to catch unsupported types sooner.

Add support for bounds of GeometryCollection

---

CHANGES.txt
rasterio/rio/clip.py
tests/test_rio_convert.py

But still the default.
Resolves #1907
I used https://pypi.org/project/darker/ to reformat only the section of rio/clip.py and its tests that I touched in this PR. Pretty slick tool, that.
I considered the following alternatives for the option name:
* --fill
* --pad
* --generous
* --with-extra
But in the end I decided --with-complement is 1) uncommon, and 2) a pretty good technical description of what's going on. I'm open to other suggestions.

Make rio-clip's intersection-only results optional

---

rasterio/__init__.py

When trying to write a new rasterised image I encountered an error that was really unintuitive. 
Googling ended up making me think I had a bad Conda installation amidst other red herrings.
When picking a driver for writing to a file, if the writer doesn't exist the package reports back this error:
``` python
s = get_writer_for_driver(driver)(path, mode, driver=driver,
TypeError: 'NoneType' object is not callable
```
(This happened for me when trying to re-project a dataset with the AIG driver, didn't realise GDAL didn't have support for writing)
This PR simply adds a None check on the result of get_writer_for_driver(driver) for cases where there isn't a writer for that driver, and throws an error if it doesn't exist.

Adding clarity for cases where driver is not supported by GDAL

---

requirements.txt

This resolves recent travis builds failling due to hypothesis requiring a more recent version of `attrs`.

Update attrs>=19.2.0 (hypothesis 5.12.0 requires attrs >= 19.2.0)

---

tests/test_env.py

Or else it's not excluded and fails to run when there's no network.

Mark test_rio_env_no_credentials as needing network.

---

setup.py

Hi,
This PR fixes use of the rasterio library with Python >= 3.4 and [Poetry](https://python-poetry.org/).
The problem with the existing setup.py is that enum34 ends up being installed for Python >= 3.4, as the [PyPI JSON output](https://pypi.org/pypi/rasterio/1.1.4/json) shows it as a permanent dependency due to the way it's added.
The changes in this commit port setup.py to use [PEP-496](https://www.python.org/dev/peps/pep-0496/) Environment Markers, a standard that is observed by Poetry and other modern Python dependency managers.
If there's anything else you need in order to merge this, please inform and I'll update my PR.
Best regards,
Alex

Specify dependencies using PEP496 Environment Markers

---

CHANGES.txt
rasterio/__init__.py
rasterio/_io.pxd
rasterio/_io.pyx
rasterio/gdal.pxi
rasterio/io.py
tests/test_memoryfile.py

Resolves #1926
The implementation of MemoryFileBase has changed quite a bit: we are eliminating custom code and are relying more on the VSI API.
Also: memory files exist now within a dedicated directory, making it easier to ensure that we're cleaning up auxiliary files.

Allow arbitrary seek to support multi-part writes

---

rasterio/merge.py
rasterio/rio/merge.py
tests/test_rio_merge.py

Hi!
As discussed in the [mailing list](https://rasterio.groups.io/g/dev/topic/73014342#131), this PR adds the ability to override the resampling method used when reading the input files in `rasterio.merge.merge()`.
This is useful for example when giving to the `merge` function a resolution that is different from the input files' resolution.

Add resampling method option to merge

---

rasterio/plot.py

This PR allows the user to pass a custom labels list as an argument to rasterio's show_hist() function.
- hidden inside show_hist(), a default label list is created and passed to the underlying matplotlib's hist() function.
- if a user tries to pass their own label list `show_hist( ... , label=['some', 'labels'] )` then matplotlib complains that `hist() got multiple values for keyword argument "label"`. (see screenshot)
- If no argument is passed to show_hist(): same behavior as previously, a default label list is created by show_hist().
- If show_hist( ... , label=['some', 'labels'] ) is used, then this label list is passed instead to matplotlib's hist() function. (see screenshot: legend on upper right hand corner has custom test1/../test7 labels)
- There does not seem to be any …

Feature show hist labels

---

rasterio/_warp.pyx
tests/test_warp.py

Closes #1957 
There are probably other places this would be useful, but this is the main change I would like at the moment and it keeps the change set pretty small.

ENH: Add support for objects with __array__ in reproject()

---

rasterio/__init__.py

If you look at the docs for [rasterio.open](https://rasterio.readthedocs.io/en/latest/api/rasterio.html#rasterio.open), you'll see that height and width aren't handled properly. It considers width to be the dtype and ignores the "int, optional" afterwards. This PR splits them into separate lines.
Also, it wasn't clear before if width was the number of rows or the number of columns. I assume width is the number of columns, but correct me if I'm wrong.

Docs: fix rasterio.open documentation

---

rasterio/vrt.py

fixed dead url in docs, optionally could switch to the non doxygen docs at https://gdal.org/api/gdalwarp_cpp.html#_CPPv415GDALWarpOptions

Update vrt.py (dead links)

---

CHANGES.txt
rasterio/_base.pyx
rasterio/_err.pxd
rasterio/_err.pyx

Lets us catch RasterioIOError for a quick integrity check.

Wrap calls to GDALChecksumImage so that we can catch GDAL errors

---

rasterio/features.py
tests/test_features.py

related to 1274, a multipolygon was resulting in the same behavior

flatten multipoly to avoid holes in output

---

docs/topics/concurrency.rst
examples/thread_pool_executor.py

This PR closes issue  #1811
I've updated the threadpool example with the code from https://rasterio.groups.io/g/main/topic/28593754. Unfortunately, when I changed the `ThreadPool` into a `ProcessPool` it resulted in a deadlock. I've added the old example to also show an option using `ProcessPoolExecutor`.
I searched around for documentation on the `shared` option in `rasterio.open` and in GDAL. Would it be interesting to mention this option in this section of the docs? I couldn't find very much information on this flag.

docs: Concurrent read/write update 

---

rasterio/session.py

The previous version read the Alibaba OSS (VSI file) file should with `OSS_ACCESS_KEY_ID` and `OSS_SECRET_ACCESS_KEY` parameters. This is not convenient for public data access.
This PR can read the public access data on Alibaba OSS directly without supply `OSS_ACCESS_KEY_ID` and `OSS_SECRET_ACCESS_KEY`.
```python
In [1]: import rasterio
In [2]: from rasterio.windows import Window
In [3]: window = Window(0, 0, 256, 256)
...: fp1 = 'https://sshuair.oss-cn-beijing.aliyuncs.com/test-oss-public.tif'
...: with rasterio.open(fp1) as src:
...:     print(src.profile)
...:     data = src.read(window=window)
...:
{'driver': 'GTiff', 'dtype': 'uint8', 'nodata': None, 'width': 1215, 'height': 994, 'count': 4, 'crs': CRS.from_epsg(4326), 'transform': Affine(5.363604115221975e-06, 0.0, 113.326558602, …
```

fix the Alibaba Cloud OSS public access session

---

docs/installation.rst

The --no-use-wheel option in pip installation has been deprecated in
favor of --no-binary.

Update pip installation instructions

---

rasterio/warp.py
tests/test_warp.py

In exploring adding rpcs to warping functionality, I noticed some pains with reprojecting from gcps. 
In the case `dst_transform=None` and `gcps` are supplied, we should expect `dst_transform` to be calculated from `calculate_default_transform`. There are two distinct cases:
- When reprojecting from a `ndarray`
An `AttributeError` will be raised due to https://github.com/mapbox/rasterio/blob/0e2d9e275ef9a51f962e98884d7eacd0121b2774/rasterio/warp.py#L316 due to passing `src_transform=None` to `array_bounds`
- When reprojecting from a `rasterion.Band`
A `ValueError` will be raised due to guard check in `calculate_default_transform` https://github.com/mapbox/rasterio/blob/0e2d9e275ef9a51f962e98884d7eacd0121b2774/rasterio/warp.py#L456. This occurs because `src_bounds` is populated from …

Enable reproject to better handle computation of dst_transform when reprojecting from gcps

---

docs/topics/georeferencing.rst
docs/topics/reproject.rst

- Fixes subheadings being rendered as separate pages on sidebar
- Fixes reproject example using rpcs to properly use kwargs to pass options to `GDALCreateGenImgProjTransformer2`

Small georeferencing and reproject doc fix

---

CONTRIBUTING.rst
README.rst
docs/installation.rst

From #2037 I felt @awa5114 highlighted some deficiencies in how to install rasterio on windows. I realized that my understanding of setup.py and pip were a bit lacking and after some trial and error I think I have a better picture that I can describe here:
The current windows install from source instructions have two steps:
```
python setup.py build_ext <options>
python setup.py install
```
however this will fail as the install command will run build_ext internally again, knowing nothing about the previously built pyd files under build/ and not having the proper include and library files to compile again. However if install is passed as a second command to setup.py, the optional arguments will be used when install calls build_ext internally. e.g.
```
python setup.py build_ext <options> …
```

Update windows install instructions

---

rasterio/_base.pyx
tests/test_warnings.py

Related:
- https://github.com/mapbox/rasterio/pull/1922#issuecomment-720004720
- https://rasterio.groups.io/g/main/topic/70046907#411
This adds a new private method `DatasetBase._has_gcps_or_rpcs` which does a simple check for gcps or rpcs. This is used in `DatasetBase.read_transform` to decide whether to raise a `NotGeoreferencedWarning`, which now is only raised if a dataset has none of geotransform, gcps, or rpcs.
As mentioned in the first related link, I think the existing warning is a bit misleading. But I could see there being some new confusion if someone is opening up a dataset with only gcps/rpcs and none of the transform related methods seemingly do what they expect. Perhaps, if this is a real issue and not just in my head, it could minimized with more documentation.
Also in the …

Make NotGeoreferencedWarning rarer

---

rasterio/merge.py
tests/test_rio_merge.py

Pathlib is supported in other parts of rasterio ( #1296), but not in merge so I suggest to add it there as well.

Support for pathlib.Path in merge

---

rasterio/_warp.pyx
tests/test_warp.py

Related:
- https://github.com/mapbox/rasterio/issues/410#issuecomment-229665628
- https://gdal.org/api/gdal_alg.html?highlight=genimgprojtransformer2#_CPPv432GDALCreateGenImgProjTransformer212GDALDatasetH12GDALDatasetHPPc
In particular:
> The use case for the *_APPROX_ERROR_* options is when defining an approximate transformer on top of the GenImgProjTransformer globally is not practical. Such a use case is when the source dataset has RPC with a RPC DEM. In such case we don’t want to use the approximate transformer on the RPC transformation, as the RPC DEM generally involves non-linearities that the approximate transformer will not detect. In such case, we must a non-approximated GenImgProjTransformer, but it might be worthwile to use approximate sub- transformers, for example on …

Don't use approximate transformer if using rpcs & passing RPC_DEM kwarg

---

tests/conftest.py
tests/test_overviews.py

Test for upcoming GDAL feature (from 3.3) allowing existing overviews to not be exposed
- see https://github.com/OSGeo/gdal/pull/3181
- see https://rasterio.groups.io/g/main/message/649
The test:
- requires gdal 3.3
- tests whether a dataset can be opened with OVERVIEW_LEVEL=-1
- ensures that opening a dataset with OVERVIEW_LEVEL=-1 ignores the file
overview
- ensures that a decimated read on a dataset opened with
OVERVIEW_LEVEL=1 does not read the file overview

Test option to ignore overviews (OVERVIEW_LEVEL=-1)

---

CHANGES.txt
rasterio/__init__.py
rasterio/merge.py
rasterio/rio/merge.py
tests/test_rio_merge.py

To support resolution of #1867. Note that block-wise merge result writing is not implemented yet, that will be another piece of work. For now, results are still accumulated in one big array.
The new args come from the "tool" interface: https://github.com/mapbox/rasterio/blob/master/rasterio/tools.py#L36-L43.

Add new merge tool arguments

---

rasterio/windows.py

See [here](https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html#rasterio.windows.from_bounds): The parameters were not grouped as intended and might cause some confusion.

Improve documentation rendering in rasterio.windows.from_bounds

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

I figured this would be helpful to redirect traffic.
You can see an example of how it might look here: https://github.com/pyproj4/pyproj/issues/new/choose

Add link to raserio.groups.io for questions when raising issue

---

docs/topics/tags.rst

`rasterio.insp` didn't work for me; `rio insp` did.

Docs: Change `rasterio.insp` to `rio insp`

---

rasterio/fill.py

There is a small typo in rasterio/fill.py.
Should read `maximum` rather than `maxmimum`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, maxmimum -> maximum

---

rasterio/vrt.py
tests/test_warpedvrt.py

closes #2092 
The `WarpedVRT` class implement its own `close` method but was missing the `self._closed = True` as we can find in https://github.com/mapbox/rasterio/blob/17efe94c530b22b6d93fc617117080ad37f897bc/rasterio/_base.pyx#L383-L386
That is said, maybe a better fix will be to get rid of the `close` method definition in `WarpedVRT` and rely on the parent classe (`DatasetBase`) `close` method?
cc @sgillies

make sure the WarpedVRT dataset is marked as closed on ctx exit

---

rasterio/warp.py

Fixed error string spacing in rasterio/warp.py:calculate_default_transform for gcps and rpcs

#2097 fixed error string spacing

---

rasterio/merge.py

In microbenchmark tests, the inplace seems to be slightly faster.
The main win is that we avoid creating allocating a new, potentially large, array every time the function is called

Avoid extra array allocations in copyto functions

---

rasterio/merge.py
rasterio/transform.py
tests/test_rio_merge.py

Addresses #2048. Use machine's epsilon in all cases.
There are some other places in the code base where an epsilon is just defined in a way that might be inaccurate. Possibly might consider defining library-wide constants for epsilon for single and double floating point precision.
For reference, the epsilon values for float32 and float64 are: 2**-23 and 2**-52 respectively.
There are two test failing that I think need to be investigated.
test_merge_rgb
test_merge_tiny_res_bounds (test known to be sensitive to rounding behavior)
ping: @sgillies @tofublock

Use machine epsilon in transform.rowcol

---

rasterio/merge.py
tests/test_rio_merge.py

According the documentation of this function, if `dtype` is None, then the dtype of the first dataset is used. This is stored in `dt`. However, if `dtype` is not None, then `dt = dtype`. Therefore, when checking if `nodataval` is in range, `dt` should be used instead of `dtype`.
If the first dataset has a dtype of `int8` and the `merge(datasets, nodata=9999)` is called, the checks for `nodataval` being in range will use float64, since `np.dtype(None) == np.float64`. But, according to the documentation, `merge` should be default to `int8` as the dtype. In this scenario, `dest` will get filled with a `nodataval` that would be out of range of the dtype.
EDIT: This is a more serious problem than I thought. It could explain some strange values I've seen in past merges. In the scenario above …

Use the right dtype when checking nodataval

---

rasterio/windows.py

* Only check pixel_precision once
* Check operator before getattr
Nothing major in this PR. It strives to make the window rounding functions easier to read.

Improvements to window.round_[offsets/lengths]

---

CHANGES.txt
rasterio/__init__.py
rasterio/merge.py
rasterio/rio/merge.py
rasterio/transform.py
rasterio/windows.py

Follow up to #2106. Restores the previous behavior for the benefit of users who depend on it, but also makes the new better eps default in `rowcol` available in the merge tool and CLI.

Plum the new rowcol precision default all the way up thru rio-merge

---

rasterio/__init__.py
rasterio/transform.py

In transform.xy, lifted the static part of computation outside of the loop.
Also take advantage of the fact that lists we build up will always be exactly the same length, so only check one list to see if we need to unpack the first element or not.

Transform.xy performance improvement

---

rasterio/rio/clip.py

Fixes https://github.com/mapbox/rasterio/issues/2112

Raise an exception while clipping rotated raster with rio clip

---

rasterio/session.py
tests/test_session.py

I have an AWS SSO setup on my machine but if I'm not logged in then `rasterio.open` raises an exception while opening presigned URLs.

Don't create AWSSession for presigned URLs

---

CHANGES.txt
rasterio/__init__.py
rasterio/_loading.py
rasterio/crs.py
rasterio/drivers.py
rasterio/env.py
rasterio/features.py
rasterio/fill.py
rasterio/io.py
rasterio/mask.py
rasterio/merge.py
rasterio/plot.py
rasterio/sample.py
rasterio/session.py
rasterio/tools.py
rasterio/transform.py
rasterio/vrt.py
rasterio/warp.py
rasterio/windows.py

This aims to replicate steps that have been taken in https://github.com/Toblerity/Fiona/pull/875 for Fiona regarding Python >= 3.8 and Windows.
Largely direct adaption of the aforementioned PR, with additional steps taken to add directories to `os.add_dll_directory` from PATH environment variable if they are found to contain a gdal DLL. Although rasterio doesn't currently publish Windows wheels, this would still help users who:
- build their own wheels (and include dlls in `.libs` directory)
- build from source
From https://github.com/mapbox/rasterio/issues/2064 
> Travis CI isn't supporting Python 3.9 for macos yet, I see other projects switching to AppVeyor or GitHub Actions. I think we will eventually have to do so too, and pick up Windows along the way.
so in the future, if Windows …

Load Windows DLL directories for Python >= 3.8

---

pyproject.toml

Forward from #2142
- Closes #1608
- Also related to #1741

DEP: use oldest-supported-numpy in pyproject.toml

---

rasterio/_base.pyx
rasterio/_crs.pyx
rasterio/_env.pxd
rasterio/_env.pyx
rasterio/control.py
rasterio/env.py
rasterio/path.py
rasterio/rio/blocks.py
rasterio/rio/bounds.py
rasterio/rio/options.py
rasterio/rio/shapes.py
rasterio/rpc.py
rasterio/session.py
rasterio/tools.py
rasterio/transform.py
rasterio/windows.py
tests/conftest.py
tests/test_crs.py
tests/test_io_mixins.py
tests/test_warp.py

See this [Q/A](https://stackoverflow.com/questions/4015417/why-do-python-classes-inherit-object) for a background on `class Foo(object):` vs `class Foo:`.
In summary, only Python 2 required inheriting from `object`, but this is no longer necessary with Python 3 (and the docs don't use that style [here](https://docs.python.org/3/tutorial/classes.html), [here](https://docs.python.org/3/howto/descriptor.html), or [here](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html)). This PR keeps the base classes a bit tidier and quicker to identify.
Edits were automated using:
git ls-files -z | xargs -0 sed -i -re 's/class (.*)\(object\):/class \1:/g'

Python3 classes does not need to inherit from object

---

rasterio/_io.pyx
rasterio/enums.py
rasterio/rio/overview.py
tests/test_enums.py
tests/test_overviews.py

closes #2153 
This PR adds a `OverviewResampling` enums to restrict the choice of available resampling values for overviews

add OverviewResampling enums and add RMS to the available resampling choice for overview

---

rasterio/enums.py
rasterio/warp.py

I had a hard time finding the resampling options for warp.reproject in the docs. 
I've tried to make it a bit easier by adding a link from warp.reproject to enums.Resampling, and then adding short descriptions in enums.Resampling from gdalwarp's resampling docs.
I hope this will clarify the warp.reproject resampling parameter options for others too.

Improve warp.reproject and enums.Resampling docs

---

rasterio/_io.pyx
tests/test_dtypes.py

Resolves the deprecation warnings about `np.bool` and `np.int` that are emitted with Numpy 1.20+.
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Resolve numpy deprecation warnings in tests

---

rasterio/coords.py

In Python 3.5+ the `__doc__` attribute is writable (https://bugs.python.org/issue24064)
This removes the need for a BoundingBox subclass and the subsequent dated workaround in #1488. In recent versions of Python (3.7+), `_asdict` returns a regular dictionary instead of OrderedDict.
An alternative formulation for BoundingBox could be:
```python
from typing import NamedTuple, Union
Number = Union[float, int]
class BoundingBox(NamedTuple):
""" <Docstring here> """
left: Number
bottom: Number
right: Number
top: Number
```

Add docstring to BoundingBox and remove subclass.

---

MANIFEST.in

Apparently this causes issues when using compile time environment variables: https://github.com/pyproj4/pyproj/issues/791

Exclude c files from the distribution

---

CHANGES.txt
rasterio/rio/edit_info.py
rasterio/rio/options.py
tests/test_rio_options.py

Click 8.0 made it clear that `None` is really the only marker for options to be ignored that works from version to version.

Eliminate unneeded IgnoreOption

---

docs/topics/switch.rst

Updating the doc section about bands to reflect that `band` objects do exist not in RasterIO and about the difference between them and gdal's

docs/topics/switch.rst - update the section about bands

---

CHANGES.txt
rasterio/_warp.pyx
rasterio/vrt.py
tests/test_warpedvrt.py

These redundant dst_* parameters were deprecated and marked to be removed in 1.1.
As they are duplicates of other parameters - removing them shall make things more clear.

rasterio/_warp.pyx - remove deprecated parameters that were marked to be removed in 1.1

---

rasterio/_warp.pyx
rasterio/gdal.pxi
tests/test_warpedvrt.py

ENH: Add transformer_options to WarpedVRT

---

rasterio/_warp.pyx
tests/test_warpedvrt.py

Noticed this would be good to add as well.
Ideally it should be added to #2195, but it needs #2193 merged in to work properly. This is a temporary PR with all of them together so you can see it. 
The commit of interest says "Pass warp_extras into _calculate_default_transform" and the commit hash is `bae8224`

ENH: WarpedVRT - pass warp_extras into _calculate_default_transform

---

rasterio/enums.py

GDAL [supports](https://gdal.org/drivers/raster/gtiff.html) these compression algorithms now when LERC and ZSTD/DEFLATE are available.
Based on previous PRs adding support for [ZSTD](https://github.com/mapbox/rasterio/commit/ed458b02a55dca6abf28f0844c336005c14a4334) and [LERC](https://github.com/mapbox/rasterio/pull/1412), it's enough to just add the enum values.
Rasterio can already read geotiffs compressed with LERC_ZSTD and LERC_DEFLATE, this PR prevents a value error when accessing `.compression` and lets rasterio write with these algorithms.
```python
>>> with rasterio.open('lerc_zstd.tif') as f:
...     f.read()  # Runs fine
...     f.compression 
ValueError: 'LERC_ZSTD' is not a valid Compression
```

Add LERC_ZSTD & LERC_DEFLATE compression enum values

---

rasterio/_base.pxd
rasterio/_base.pyx
rasterio/_crs.pxd
rasterio/_crs.pyx
rasterio/_env.pxd
rasterio/_env.pyx
rasterio/_err.pxd
rasterio/_err.pyx
rasterio/_features.pxd
rasterio/_features.pyx
rasterio/_fill.pyx
rasterio/_io.pxd
rasterio/_io.pyx
rasterio/_transform.pyx
rasterio/_warp.pxd
rasterio/_warp.pyx
rasterio/gdal.pxi
rasterio/shutil.pyx
setup.py

Saw this:
```
FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: rasterio/rasterio/_example.pyx
```

REF: set language level in cythonize options in setup.py

---

rasterio/__init__.py
rasterio/merge.py
rasterio/shutil.pyx
tests/test_open.py
tests/test_rio_merge.py

Addresses #2229 
A generalization that allows any PathLike object to be passed to `rasterio.open`. PathLike objects implement a special method, `__fspath__` which can be retrieved by `os.fspath`.
At the moment, I've only updated rasterio.open, but there are several other places where we compare with pathlib.Path when we should compare with os.PathLike or call `os.fspath`.

Accept PathLike objects in rasterio.open

---

rasterio/windows.py

The docstring for https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html#rasterio.windows.Window is broken, and the note at the bottom is being interpreted as a list of attributes. Using the [notes](https://numpydoc.readthedocs.io/en/latest/format.html#notes) section should hopefully solve this issue.
@calebrob6

rasterio.windows.Window: fix docstring

---

README.rst

README is RST not markdown, but it looks like the requirements block was written as markdown.

Fixing the requirements code block in README

---

rasterio/_base.pyx

Was working with geotiffs with color tables and noted the incorrect docstring that said `None` would be returned if the band didn't have a colormap. `None` seems to match the GDAL behavior (at least from my old code that used it), but rasterio's `colormap` actually raises a ValueError.
This PR corrects and fills out the rest of the docstring for common use cases.

Fix Dataset colormap docstring to describe NULL color table handling

---

pyproject.toml

Pytest seems to prefer that custom markings be defined in either a pytest.ini or pyproject.toml.
https://docs.pytest.org/en/stable/mark.html

Register custom pytest markings.

---

rasterio/_base.pyx
tests/test_warp_transform.py

Another fix I tried which didn't affect the test suite was to call CPLErrorReset() before OCTTransform(), but that fix is more appropriate. I'm not sure if the intent was for a single failed coordinate to transform to cause the whole call to error out (which is now the case, provided that a CPLError() is emitted, which isn't necessary the case if the same cached OGRCoordinateTransformation object is reused, and in a previous invokation saturated the 20 max error messages), or not

_transform(): correctly check error code of OCTTransform()) (fixes #2282)

---

docs/topics/tags.rst
rasterio/_base.pyx
tests/test_tags.py

Fixes #2220 
Per https://gdal.org/user/raster_data_model.html#xml-domains, metadata domains prefixed by `xml` should not be treated as typical key:value metadata. 
If we detect a domain/namespace prefixed with `xml` we return a dictionary with the domain as key and xml string as value.

handle md domain prefixed by "xml"

---

.travis.yml
CHANGES.txt
rasterio/__init__.py
rasterio/_err.pyx
rasterio/_warp.pyx
rasterio/errors.py
tests/rangehttpserver.py
tests/test_warp.py

We've been hiding these errors and allowing chunks of a warp operation to pass with no data copied to the output.
Note that the error message isn't very detailed. In a lot of cases it's a generic "TIFF read block error" and doesn't surface root causes like server errors.
Without the changes to _warp.pyx, reproject passes with no output copied (out will be all zeros). With the changes, an exception is raised.

Raise WarpOperationError (new) if ChunkAndWarpMulti/Image fail

---

Dockerfile
Makefile
rasterio/_base.pyx
rasterio/_io.pyx

Inspired by #1928.
Instead of having multiple dockerfiles I'd like to try cramming multiple targets into one. The first provides (slightly outdated) dependencies, makes a Python environment at `/venv`, and installs rasterio's dependencies. The second will (when done) build and install the latest PROJ and GDAL. The third installs rasterio and copies rasterio's `tests` directory to `/usr/src/app/tests`.
We can use this to run rio-info in a container.
```
docker run -v /home/seangillies/projects/rasterio/tests/data:/io 647ffce97b32 info /io/RGB.byte.tif
{"bounds": [101985.0, 2611485.0, 339315.0, 2826915.0], "colorinterp": ["red", "green", "blue"], "count": 3, "crs": "EPSG:32618", "descriptions": [null, null, null], "driver": "GTiff", "dtype": "uint8", "height": 718, "indexes": [1, 2, 3], …
```

Dockerfile for local development

---

docs/cli.rst

I'm proposing some intermingled updates to this section:
1. _New gist links for outputs_: the previously-linked mapbox classic style is now deprecated.
2. _Removal of `geojsonio` invocation_: geojson.io does not accept piped `.geojsonl`
3. _Use of the `--collection` flag_: I think it's correct to have geojsonl as the default output for various reasons, but for purposes of displaying the example results I've set the commands to output feature collections, and added a note for clarification.

Update rio shapes cli docs

---

MANIFEST.in

Related to #2130
```bash
tar -tf rasterio-1.3a2.tar.gz  | grep .cpp
```
```
rasterio-1.3a2/rasterio/_fill.cpp
rasterio-1.3a2/rasterio/_pyvsi.cpp
rasterio-1.3a2/rasterio/_warp.cpp
```

BUG: Exclude *.cpp from dist

---

DESIGN.rst

In #2322 I asserted that we needed to document the design of rasterio in prose before starting on type hints. Here's a first draft.
It's incomplete, only covering the design of the opening-a-dataset part of the code. There are other undocumented interfaces, especially around the merge tool and reprojection. I think I may also have confused dispatch with delegation. And I need to make it more clear that this document is aimed at developers and not users.

Draft of project design notes

---

.github/workflows/tests.yaml
requirements-dev.txt

This PR adds GitHub action workflow to test rasterio using official GDAL docker images. 
The main difference with the previous Travis CI is that we are using the official GDAL docker images an thus we can't control the PROJ version. The main advantage is that we don't have to compile GDAL/PROJ which means faster tests.
Matrixes:
- Docker | GDAL=3.4.0 | python=3.8
- Docker | GDAL=3.3.3 | python=3.8
- Docker | GDAL=3.4.0 | python=3.9
- Docker | GDAL=3.3.3 | python=3.9
- Docker | GDAL=3.2.3 | python=3.8
- Docker | GDAL=3.1.3 | python=3.8
- Docker | GDAL=3.2.3 | python=3.7
- Docker | GDAL=3.1.3 | python=3.7
- Conda | macos-latest | python=3.8
- Conda | macos-latest | python=3.9
- Conda | ubuntu-latest | python=3.10

CI: Add GitHub Action Test workflow with conda & gdal docker

---

docs/topics/reproject.rst
rasterio/errors.py
rasterio/warp.py
tests/test_warp.py

closes #2362 
Also fixes a usage issue when passing `src_rpcs` with a dataset that also has gcps

warn when reprojecting with RPCs using a source CRS that is not EPSG:4326

---

CHANGES.txt
rasterio/__init__.py
rasterio/_base.pyx
rasterio/_io.pxd
rasterio/_io.pyx
rasterio/_transform.pyx
rasterio/_warp.pyx
rasterio/env.py
rasterio/io.py
rasterio/transform.py
rasterio/vrt.py
tests/test_memoryfile.py

Resolves #2360.
We already had an optional context manager attached to our dataset objects, see https://github.com/rasterio/rasterio/pull/2371/files#diff-9729b3413c39ccb6eea16562e513703922f21d4d94a3e27980926dd01a0c5068L445. I've replaced it in the `have_vsi_plugin=False` case with an ExitStack. First time I've used ExitStack in the implementation of a library. Seems to do the trick.
As pointed out, this is in some ways an API change, but I consider it most of all a bug fix, and not something that requires a new version.

rasterio.open returns a dataset object for all kinds of input

---

pep-508-install
setup.cfg
setup.py

👋 I'm not sure why but with the old format the `bin` wasn't created anymore 🤷‍♂️ 
Updating the `entry_points` block to the `dict like` format fixed my environment. I have absolutely no idea what changed since last time I did `pip install rasterio`
```
$ python --version
Python 3.8.2
$ pip --version
pip 22.0.3
$ python -c 'import setuptools; print(setuptools.__version__)'
60.5.0
```

move entrypoints to setup.cfg

---

rasterio/crs.py
tests/test_crs.py

This fixes #2394. Catching `OverflowError` in Cython in `crs.pyx` somehow didn't work (`OverflowError` was still raised in Python), so I caught it in Python instead.
The test passes a large enough argument to `from_epsg` to cause an `OverflowError`. Not sure if it's needed.
Edit: sorry about the unrelated removed space on line 578, I have VSCode configured to remove trailing spaces.

Catch overflows in from_epsg and raise CRSError (#2394)

---

rasterio/rpc.py

We have a RPC referenced file from a customer with tags that cause a `ValueError` when calling rasterio `src.rpcs`:
```
$ gdalinfo foo.tif
...
RPC Metadata:
HEIGHT_OFF=482.50 meters
HEIGHT_SCALE=397.45 meters
LAT_OFF=26.80851366 degrees
LAT_SCALE=0.08428740 degrees
...
```
Obviously the units are not expected here but using `gdalwarp` seems to be fault tolerant as it can warp the file correctly.
This PR fixes this behavior but I don't have a small enough example image to add a test case. Is this an issue?

fix RPC metadata parsing

---

rasterio/transform.py
tests/test_transform.py

Fix ignored z values when using transform mixin methods with rpcs

---

rasterio/_io.pyx
rasterio/errors.py
rasterio/io.py
rasterio/rio/options.py
rasterio/rio/sample.py
rasterio/rio/transform.py
tests/test_memoryfile.py

Since Python 3.3,  IO and OS exceptions were re-worked as per [PEP 3151](https://www.python.org/dev/peps/pep-3151/). The new main base class is [OSError](https://docs.python.org/3/library/exceptions.html#OSError), with several other exceptions merged, including IOError (i.e. `assert IOError is OSError`).
This PR changes the old IOError alias to OSError.

Replace IOError alias with OSError

---

CHANGES.txt
Makefile
rasterio/merge.py
rasterio/rio/merge.py
rasterio/transform.py
rasterio/windows.py
tests/test_rio_merge.py

Responsibility is on the caller (merge.merge).
Resolves #2374
The gist of it: https://github.com/rasterio/rasterio/pull/2432/commits/dcc9ef498c10b33231c3b81eecaaed2ccb677840#diff-59130575b4fb2932c957db2922977d7d89afb0b2085357db1a14615a2fcad776R12-R15

No more epsilon usage in transform.rowcol and window.from_bounds

---

CHANGES.txt
Dockerfile
Makefile
rasterio/windows.py
tests/test_windows.py

By subtracting array dimensions from the slice indexes when they are left of the dial (negative).
Resolves #2378

Produce slices that don't erronously select from an array

---

rasterio/sample.py

I have encountered a use case where I am querying millions of points from a raster and realized there was some very low hanging fruit to optimize `sample_gen`. 
With 10 million points query time has dropped from 2m29s (1.2.8) to 28s (with this PR). Moved the masking check out of the loop and allocated the nodata array once. Also chunked the point transformations using rowcol.

Accelerate rasterio.sample.sample_gen

---

rasterio/io.py

There can be cases where the get_writer_for_driver function is reached when a file is being opened, hence adding note about read/write in the ValueError.

Update error message wording if a driver is not found

---

.github/ISSUE_TEMPLATE/bug_report.md
rasterio/__init__.py
rasterio/_env.pyx
rasterio/_show_versions.py
rasterio/gdal.pxi
rasterio/rio/main.py
tests/test__env.py
tests/test_rio_main.py
tests/test_show_versions.py

Closes #2349
```
$ rio --show-versions
rasterio info:
rasterio: 1.3a3
GDAL: 3.4.0
PROJ: 8.2.0
GEOS: 3.10.1
PROJ DATA: ~/miniconda/envs/rio/share/proj
GDAL DATA: ~/miniconda/envs/rio/share/gdal
System:
python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:11)  [GCC 9.4.0]
executable: ~/miniconda/envs/rio/bin/python
machine: Linux-5.13.0-39-generic-x86_64-with-glibc2.31
Python deps:
affine: 2.3.0
attrs: None
certifi: 2021.10.08
click: 8.0.3
cligj: 0.7.2
cython: 0.29.24
numpy: 1.22.2
snuggs: 1.4.7
click-plugins: None
setuptools: 59.4.0
```

ENH: Add show_versions

---

rasterio/merge.py
rasterio/rio/merge.py
tests/test_rio_merge.py

When passing dtype as a parameter in merge, the output file was not compliant with the docstring explicit behavior. This was due to the given dtype being only used for the array, and not updated in the out_profile.

BUG: Fix output file dtype in merge

---

rasterio/_env.pyx

Closes #2455
The CA Bundle path is for wheel distributions. Since those will contain recent versions of GDAL/PROJ, this is a safe change to make.

BUG: Set GDAL/PROJ_CURL_CA_BUNDLE environment

---

CHANGES.txt
rasterio/__init__.py
rasterio/_io.pyx
tests/test_write.py

The write() method can take a masked array. This is new. When it does, and the masked keyword argument is False, we collapse the masked array by calling its filled method with either the dataset's nodata value or (if that is None) the masked array's own fill value.
If the masked keyword argument is True, we call self.write_mask before writing the band data. There is some redundant computation which we can optimize away in the future, but calling write_mask seemed the most reliable approach for now.
Resolves #2347

Accept masked arrays and fill or write a mask

---

.github/ISSUE_TEMPLATE/bug_report.md

I suppose that this is not relevant any more.

Remove outdated note from issue template

---

rasterio/windows.py

Closes #2466.
I think it is fine to just remove `width` and `height`, since ["These parameters are unused"](https://rasterio.readthedocs.io/en/latest/api/rasterio.windows.html#rasterio.windows.from_bounds).
cc @snowman2

Fix RasterioDeprecationWarning issued in WindowMethodsMixin::window()

---

rasterio/plot.py

This PR updates the links to `imshow` and `contour` matplotlib API docs in the `rasterio.plot.show` method's docstring.

DOC: Update matplotlib API doc links in rasterio.plot.show

---

README.rst
setup.py

Noticed that the range of versions supported for rasterio dependencies differs depending on where you look in the docs.

DOC: Consistently document dependency versions

---

CHANGES.txt
rasterio/_io.pyx
tests/test_features.py
tests/test_warp.py

when given non-contigous array on output pass along strides
information to GDAL.
closes #2511 
closes #2509

Pass along strides to GDAL in MemoryDataset #2511

---

docs/topics/switch.rst

The instance is an `Affine` class, and not `Afine`

DOC: Typo in switch.rst Afine -> Affine

---

docs/conf.py
docs/quickstart.rst
docs/topics/masks.rst
docs/topics/migrating-to-v1.rst
docs/topics/plotting.rst
docs/topics/reading.rst
docs/topics/switch.rst
rasterio/__init__.py
rasterio/_features.pyx
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/dtypes.py
rasterio/features.py
rasterio/fill.py
rasterio/mask.py
rasterio/merge.py
rasterio/plot.py

Adds links directly in the types & other references:

DOC: Add intersphinx for matplotlib & numpy

---

rasterio/transform.py
tests/test_transform.py

This pull request fixes an error I'm seeing that seems to be a regression from *v1.2* to *v1.3* or *rasterio*. Apologies if this is the intended behavior, in which case please ignore this pull request.
With the older version the following worked,
```python
>>> rasterio.transform.xy(transform, 0, [1, 2, 3])
```
In this case, the *rows* argument argument would be broadcast to match the length of the *cols* argument. That is, it would be equivalent to,
```python
>>> rasterio.transform.xy(transform, [0, 0, 0], [1, 2, 3])
```
With the newer version I now get the following error,
```python
>>> rasterio.transform.xy(transform, 0, [1, 2, 3])
... Traceback (most recent call last)
...
... TransformError: Invalid inputs 
```
In this pull request I've modified `TransformerBase._ensure_arr_input` to …

Fix broadcasting of coords in `rasterio.transform.xy`

---

rasterio/windows.py
tests/test_windows.py

Supersedes #2262. Updated PR for rasterio 1.3.0.
Cleans up the implementation of get_data_window and extends it to properly handle 1D arrays. The documentation implied that 1D arrays are supported, but constructing a full window assumed 2 dimensions.
Primary wins:
* doesn't create a masked array anymore
* nicer handling of masked array (True maps to valid data)
* Avoid some temporary array allocations and removed unnecessary rollaxis usage.
* Small performance improvement.

get_data_window cleanup

---

rasterio/sample.py

Following up on @sgillies comment here: https://github.com/rasterio/rasterio/pull/2338#discussion_r847710362
Now that 1.3.0 is out, I played around with sorting the points and it resulted in another nice speedup. The test raster is 671MB tiff with a shape of (21058, 22812) pixels.
For comparison:
With 1.3.0 and 100k uniformly random sampling points: 55.8s
With PR and 100k uniformly random sampling points: 13.2s
With 100 points the sorting overhead is more noticeable, though still tolerable:
1.3.0: 6.75ms
PR: 7.38ms
Note that this changes sample_gen to return a list instead of a generator. I think it is important to return points in the same order they were received. An alternative would be to return tuples of the original point and the sampled value (which could be returned in any order) …

Sort pixel locations during sampling

---

rasterio/transform.py
tests/test_transform.py

Related #2555
* broadcast arrays to 1d arrays
* update ensure_arr tests for broadcasting coordinates
* make tests/test_transform.py a staticmethod
* add tests for ensure_arr_input that use zs
* change _ensure_arr_input to return numpy arrays, not lists
* transform ValueError into TransformError

Fix broadcasting of coords in `rasterio.transform.xy` (#2538)

---

rasterio/_io.pyx
tests/test_features.py
tests/test_warp.py

Related #2555
* Pass along strides to GDAL in MemoryDataset #2511
when given non-contigous array on output pass along strides
information to GDAL.
* Add test for #2509
* Update changes.txt

Pass along strides to GDAL in MemoryDataset #2511 (#2512)

---

examples/thread_pool_executor.py

The dictionary was updated but the src (not updated) dictionary was being used. Because of that the iteration wasn't using the blocks

Create destfile with proper dictionary

---

docs/topics/features.rst

Raster data of dtype = int8 leads to an error message from pprint, which requires the data to be one of the following:
int16, int32, uint8, uint16, float32
I added a comment catching this error, which can be solved by casting the data: data = data.astype('int16')

DOC: Add a comment on dtype = int8

---

rasterio/_path.py
tests/test_path.py

BUG: parse path without modifying query

---

rasterio/_base.pyx

Related #2632
Some change made COG preferred over GTiff driver in the defaults in 3.6.0.
This ensures it is consistent moving forward.
Before:
```python
>>> from rasterio.drivers import raster_driver_extensions
>>> raster_driver_extensions()
{'tif': 'COG', 'tiff': 'COG', ...}
```

BUG: ensure default driver for tif to be GTiff

---

rasterio/windows.py
tests/test_windows.py

Closes #2628 
Added an analogous test to the `test_data_window_nodata`, using `nan` instead of 0 as the nodata.

BUG: fix get_data_window for nodata=nan, fixes #2628

---

rasterio/__init__.py

Rasterio might fall back to search the gdal lib in PATH. For the not so unusual case that PATH has an empty element (most likely a trailing ';') the current method would glob for "gdal*.dll" in the current working directory and if found something would try to pass empty string to os.add_dll_directory which raise an error.
Problematic example PATH=C:\WINDOWS\system32;C:\WINDOWS;
I have seen such a trailing PATH separator on a quite clean Windows installation so I assume it is not too uncommon.

Fix possible init crash when Windows PATH has empty entry

---

rasterio/transform.py

Related to #2584
The variable names are incorrect, though they happen to be incorrect in a way that makes everything work. For the `xy` functions, the response order should be `x, y` as is in the docstrings of several of the `xy` functions. This just makes the internal variable naming match what is returned externally for clarity.

REF:transform: Rename variables in TransformerBase.xy for clarity

---

rasterio/session.py
tests/test_session.py

I believe adding `AZURE_STORAGE_ACCESS_KEY` to the credentials in an `AzureSession` follows the authentication logic: use `AZURE_CONNECTION_STRING` if available, use `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_ACCESS_KEY` unless `AZURE_NO_SIGN_REQUEST` is set in which case we only need `AZURE_STORAGE_ACCOUTN`. I assume that we get away without passing any secrets for S3 authentication because `boto` handles it.
resolves #2636

pull AZURE_STORAGE_ACCESS_KEY from env if not provided as arg to AzureSession

---

rasterio/_err.pyx

Closes #2492
Not sure of a great way to test this other than the exploration in the issue. It is for edge cases that shouldn't happen normally.

BUG: Raise exception with debugging information when NULL return

---

rasterio/__init__.py

```
UserWarning: Normalizing '1.3.4dev' to '1.3.4.dev0'
```

MNT: Fix __version__

---

rasterio/_filepath.pyx
rasterio/gdal.pxi

Hi, this is my first time submitting a change request to this project. I've read the `CODE_OF_CONDUCT.md` and I agree to abide by it. Let me know if there is anything else I need to do.
This PR concerns a bug that I discovered while operating on large (larger than 2^31 bytes) GeoTIFF files with Rasterio. If you pass such a file into `rasterio.open` using a file-like object, Rasterio will raise a runtime exception when it tries to read that file past the 2^31 byte mark. From what I can tell, this is because Rasterio holds the file stream position in an `int`, but the actual file stream offset obtained from `tell()` is `long`, so this value ends up getting narrowed.
This behavior will only occur if you pass a Python file-like object to `rasterio.open`, and won't happen if you pass the path …

Avoid narrowing file stream position to `int` inside `filepath_tell`

---

rasterio/_err.pyx

The lintian QA tool reported a spelling error for the Debian package build:
* Unkown -> Unknown

Fix spelling errors.

---

rasterio/session.py
tests/test_session.py

This PR fixes several issues around use of `AWSSession` when accessing public resources (`aws_unsigned=True` case)
1. S3 endpoint configuration was not propagated in the unsigned case
2. Value stored inside `AWS_NO_SIGN_REQUEST` and `AZURE_NO_SIGN_REQUEST` was always parsed as `True`
3. `AWSSession` could not be constructed when `boto3` is missing
4. No way to force `aws_unsigned=False` configuration when `AWS_NO_SIGN_REQUEST=YES` is configured in the environment.
`AWSSession` does more than just credential management for S3 access, so it's needed even when accessing public S3 buckets without relying on environment variables. `boto3` is an optional dependency of `rasterio`, and I think `rasterio` should work without `boto3` when accessing public S3 buckets.
Example of user confusion:
``` …
```

Fixes for unsigned access to S3

---

CHANGES.txt
rasterio/session.py
tests/test_session.py

* Add parse_bool helper method
This is for parsing boolean environment variables
* Fix s3_endpoint config when unsigned
S3 endpoint configuration was not propagated to GDAL when accessing public buckets.
* Allow AWSSession construction without boto3
Should be able to use AWSSession even when boto3 is not installed so long as unsigned access is used.
AWSSession is responsible to configuration of things like region and endpoint url, so it's needed even when accessing public buckets without relying on environment variables. `boto3` dependency is only needed for obtaining credentials though.
* Convert parse_bool test to parametrize for clarity

BUG: Fixes for unsigned access to S3 (#2669)

---

CHANGES.txt
rasterio/rio/blocks.py
rasterio/rio/bounds.py
rasterio/rio/gcps.py
rasterio/rio/helpers.py
rasterio/rio/sample.py
rasterio/rio/shapes.py
rasterio/rio/transform.py

Resolves #818. I've learned some things about Python!
Python ignores SIGPIPE by default. By never catching BrokenPipeError via `except Exception` when, for example, piping the output of rio-shapes to  the Unix head program, we avoid getting an unhandled BrokenPipeError message when the interpreter shuts down (#2689).
I also did a little linting, caught a case of using print instead of click.echo, and reformatted a few blocks that look gross to my black-adjusted eyes.

Handle and silence sigpipe errors

---

tests/test_rio_main.py

Note: This adds the fix test failure https://github.com/rasterio/rasterio/actions/runs/3705505518/jobs/6279503388
```
______________________________ test_gdal_version _______________________________
runner = <click.testing.CliRunner object at 0x7f04c18e4d90>
def test_gdal_version(runner):
result = runner.invoke(main_group, ['--gdal-version'])
assert result.exit_code == 0
>       assert parse(result.output.strip())
tests/test_rio_main.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
testenv/lib/python3.10/site-packages/packaging/version.py:52: in parse
return Version(version)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <[AttributeError("'Version' object has no attribute '_version'") raised in repr()] …
```

TST: Use GDALVersion in test_gdal_version

---

rasterio/_io.pyx
tests/test_write.py

Update write_mask to accept Numpy booleans, to enable writing optimized masked array (mask == mp.ma.nomask)

---

rasterio/dtypes.py

A few minor performance enhancements in dtypes modules
1. Use scalar variants of isinf/isnan in `in_dtype_range`. The scalar versions of these functions are much faster than the ufunc (140ns for scalar vs 950ns for ufunc).
2. Avoid creating array in `get_minimum_dtype`. If passed a non-array, use the builtin min/max to avoid the extra memory/cpu overhead of traversing values 3 times.
```
In [66]: %timeit dtypes.get_minimum_dtype(range(266))
35.3 µs ± 651 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
In [67]: %timeit get_minimum_dtype(range(266))
13.3 µs ± 172 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
3. Use `np.asarray` where possible. Benchmarking on my system showed that calling `np.asarray` was much faster when called with an array (90ns vs 336ns) …

PERF: Minor performance improvements to dtypes

---

CHANGES.txt
rasterio/rio/clip.py
rasterio/rio/warp.py

Was already done for height and width. Additionally, we allow --target-aligned-pixels with --dst-bounds or --src-bounds in rio-warp.
Resolves #1931

Align offsets in rio-clip

---

CHANGES.txt
rasterio/plot.py

Resolves #2017
To test, I got a 4-band PlanetScope scene (from work). It's uint16 data.
```
$ rio insp 20200922_183724_23_106a_3B_AnalyticMS.tif
Rasterio 1.3.5dev Interactive Inspector (Python 3.8.10)     
Type "src.meta", "src.read(1)", or "help(src)" for more information.                                                                                       
>>> data = src.read(out_shape=(src.height/8, src.width/8), masked=True)
>>> show(data[:3], adjust=True)
```
It's a bit dim because there's a linear stretch and some hot spots on the high end throw it off, but it works now and wasn't working before.

Ensure that imshow receives float data when adjust=True

---

tests/conftest.py

The Debian package build failed because pytest fails with an ImportError:
```python
ImportError while loading conftest '/build/rasterio-1.3.5/.pybuild/cpython3_3.10_rasterio/build/tests/conftest.py'.
tests/conftest.py:31: in <module>
not(boto3.Session().get_credentials()),
/usr/lib/python3/dist-packages/boto3/session.py:203: in get_credentials
return self._session.get_credentials()
/usr/lib/python3/dist-packages/botocore/session.py:509: in get_credentials
).load_credentials()
/usr/lib/python3/dist-packages/botocore/credentials.py:2035: in load_credentials
creds = provider.load()
/usr/lib/python3/dist-packages/botocore/credentials.py:1045: in load
metadata = fetcher.retrieve_iam_role_credentials()
/usr/lib/python3/dist-packages/botocore/utils.py:570: in retrieve_iam_role_credentials
token …
```

Fix ImportError with unreachable http_proxy.

---

rasterio/transform.py

I found a need to use other than the default offset setting transform.xy, and didn't readily know the nomenclature for the additional options. This simply adds the available options to the docstring.

Additional info for offset parameter in transform.xy

---

CHANGES.txt
rasterio/_features.pyx

Plus a 30-40% speed gain by using zip.
Resolves #2745.

Dodge empty sequences when computing bounds.

---

CHANGES.txt
tests/test_dataset_mask.py
tests/test_plot.py
tests/test_warp.py

In an attempt to make the tests run more cleanly in a situation like that of #2747, I've eliminated an unnecessary matplotlib import from one test module, switched test_plot.py over to skipping at the module level if matplotlib.pyplot can't be imported, and marked one test in test_warp.py as needing a network.

Solutions for #2747

---

rasterio/merge.py
tests/test_merge.py

During a merge, check that source CRS matches the first raster. Raise an exception when CRS doesn't match. I considered raising a warning instead, but I think a mismatched CRS is grounds to abort the merge operation.
Issue discussed here: https://github.com/rasterio/rasterio/discussions/2682

Raise exception when CRS differs during merge

---

.github/workflows/tests.yaml
tests/test_warp.py

Related: #2772
Backport of:
- https://github.com/rasterio/rasterio/pull/2680
- https://github.com/rasterio/rasterio/pull/2679

MNT: Update warp tests for GDAL 3.6 &  Update GDAL versions in test matrix

---

rasterio/rio/merge.py
tests/test_rio_merge.py

This adds the possibility to switch the strategy used when merging rasters. The underlying functionality already exists in the underlying merge function but is not exposed by the CLI.
If you'd like to have a test for this, I would be happy to provide one, but I did not see any tests so far for the CLI.

ENH: Added option to change merge strategy in CLI

---

tests/test_warp.py

Closes #2789
Differences are related to transform differences, not errors in transform_bounds. Updating to match GDAL/pyproj so tests pass.

TST: Update test_transform_bounds_densify to match GDAL

---

rasterio/transform.py
tests/conftest.py
tests/test_dataset.py
tests/test_transform.py

Fixes #2787.
The method of computing raster bounds in `rasterio.transform.array_bounds` assumes a standard GIS orientation of the image - north down, east right when just viewing the array. If the image is rotated in any way, the returned bounds may be in the wrong order (e.g. `east` is west of `west`), or may be entirely incorrect.
Replace the current implementation with the more general calculation used in DatasetBase.bounds. Add an array of tests to both implementations, passing in various transforms.

BUG: Fix calculation of bounds in transform.array_bounds

---

docs/quickstart.rst

Fix quickstart documentation mixing up column and row position of matrix. Fixes #2582

Fix for issue #2582

---

.github/workflows/tests.yaml

https://github.com/OSGeo/gdal/releases/tag/v3.7.0

CI: Add GDAL 3.7 to the test matrix

---

rasterio/warp.py

Fixes #2295. I implemented the suggested reword of #2295 minus a comma. I thought it read better without the comma following "coordinate reference systems" but can easily add it if preferred.

DOC: Clarify required params of rasterio.warp.calculate_default_transform in docstring

---

rasterio/_io.pyx
rasterio/_warp.pyx

Related to #2575
Originally added in #1959. However, asanyarray is likely more appropriate so masked arrays not converted to regular arrays.

BUG: Use numpy.asanyarray instead of numpy.array(..copy=False)

---

.gitignore
CHANGES.txt
rasterio/_base.pyx
rasterio/_io.pyx
rasterio/features.py
rasterio/gdal.pxi
tests/test_features.py
tests/test_int8.py
tests/test_write.py

Namely #2656 and #2780. No more unnecessary warnings with GDAL 3.7.0!

Int8 related backports from main

---

CHANGES.txt
docs/cli.rst
rasterio/rio/blocks.py

Remove notes about additions before 1.0.
Resolves #2570

Add rio-blocks documentation

---

CHANGES.txt
rasterio/_io.pyx

Also improve the docstring of write_colormap and write_mask.
Resolves #2769

Allow color values greater than 256 in colormaps

---

rasterio/windows.py

Doc is outdated, from before the parameters were removed.

DOC: improve doc for window.round_lengths and round_offsets

---

CHANGES.txt
rasterio/_io.pyx
tests/test_read.py
tests/test_rio_calc.py

Backport of the workaround in #2851

Backport 2851

---

CHANGES.txt
rasterio/rio/warp.py
tests/test_rio_warp.py

Remove redundant file size guards from rio-warp, add --dry-run

---

rasterio/env.py
tests/test_env.py

Addresses #2866 for single-threaded context
* adds simple `rasterio.Env.session_resolution_path` to track how `__init__` resolves sessions and help fix bug for single-threaded context
* adds override flow to `credentialize()` for nested context managers getting parent session context from `self.context_options`
* tests

In nested Env managers make interaction of Env.session consistent for a single thread

---

rasterio/dtypes.py

BUG: Use stdlib math instead of deprecated numpy.math

---

.readthedocs.yaml
docs/environment.yml
readthedocs.yml

Based on shapely's config, which has already been migrated.

Migrate to RTD v2

---

docs/topics/vsi.rst
rasterio/__init__.py
rasterio/_base.pyx
rasterio/_env.pyx
rasterio/_vsiopener.pxd
rasterio/_vsiopener.pyx
rasterio/gdal.pxi
requirements-dev.txt
setup.py
tests/test_filepath.py
tests/test_pyopener.py

Resolves #2888 ~maybe~ definitely.
This PR adds a new `opener` keyword argument to `rasterio.open()`, making an analogy to the `opener` kwarg of Python's builtin `open()`.
The `opener` keyword argument must be a callable which takes a string as its one positional argument and returns a read-only Python file-like object with `read`, `seek`, `tell`, and `close` methods. The `opener` is called by GDAL's virtual filesystem machinery and thus its file-like object serves GDAL's format drivers.
Example usage:
```python
with rasterio.open("zip://*.tif::tests/data/files.zip", opener=fsspec.open) as src:
print(src.profile)
```
When the opener needs extra arguments, one can use `functools.partial`.
```python
from functools import partial
with rasterio.open("dask::s3://bucket/key", …
```

Python file opener VSI plugin

---

.github/workflows/test_gdal_build.yaml
.github/workflows/test_gdal_dispatch.yaml
.github/workflows/test_gdal_latest.yaml

Resolves #2960.
Summary:
* A weekly test against latest GDAL and an on-demand test against the latest GDAL tag (to test pre-releases) share a new reusable workflow (based on previous workflow).
* The on-demand workflow only can only be triggered by the GitHub API if it's in our default branch. Its matrix spans rasterio main and current maint branches.
Thus this PR is aimed at main. We can backport to maint-1.3 after this is merged.
Work on the GDAL side of things is here: https://github.com/OSGeo/gdal/pull/8692.
Any questions @snowman2 @vincentsarago ?

Convert test with latest GDAL into a reusable workflow

---

.github/workflows/test_gdal_tags.yaml

In a nutshell: we ignore non-critical errors and prevent other errors that are entailed by them.

Robustness improvements for workflow that watches GDAL's tags

---

rasterio/_io.pyx

For our use-case of rendering WMS / TMS images at high zoom levels, the clamping of the window read is happening too soon and causes corruption for lower resolution data. 
Here's a small demonstration of the issue. Given this dummy data set, in which we zoom a couple of times to a select few subpixels:
(data_g.png)
```
import rasterio
from rasterio.transform import Affine
with rasterio.open('data_g.png') as src:
box = (72, 90, 74, 88)
for zoom in range(3):
box = (box[0] + 0.25, box[1] - 0.25, box[2] - 0.25, box[3] + 0.25)
src_window = src.window(*box)
print(src_window)
data = src.read(boundless=True, window=src_window, out_shape=(256, 256), resampling=rasterio.enums.Resampling.nearest)
with rasterio.open(f'out{zoom}.png', 'w', width=256, height=256, count=src.count, dtype=src.dtypes[0], …
```

Allow (float) windowed reads smaller than 1.0 to handle extreme zoom use case

---

rasterio/_io.pyx
tests/test_memoryfile.py

Calling file operations on null pointer crashes Python interpreter.
Discovered this when accidentally calling `.seek(0)` on a closed MemoryFile and the Python interpreter segfaulted.

Prevent interpreter segfaults with closed MemoryFile.

---

rasterio/merge.py

This PR ensures that values used for indexing are indeed integers. This sort of defensive behavior appears elsewhere in rasterio, but merge.py simply assumes that the values are integers after rounding.
For examples see:
https://github.com/rasterio/rasterio/blob/main/rasterio/_io.pyx#L596
https://github.com/rasterio/rasterio/blob/main/rasterio/_io.pyx#L829
https://github.com/rasterio/rasterio/blob/main/rasterio/rio/clip.py#L156-L157

Ensure integer values in merge.py

---

CHANGES.txt
rasterio/_io.pyx
rasterio/io.py
tests/test_memoryfile.py

To be like standard Python files. Follow up on #2870.

Operations on closed MemoryFile and ZipMemoryFile raise ValueError

---

rasterio/transform.py

Related to the discussion: https://github.com/rasterio/rasterio/discussions/2935 
* Reason of this change is to gain speed in bulk transforms.
* Replaced the for loop in AffineTransformer._transform  with numpy matrix multiplication
* Reimplemented TransformerBase.xy to take advantage of the above change.
* All tests are running correctly (except S3-related)
* Total test time is reduced by 40%.
Test summary before the changes: (failed tests are due to S3)
6 failed, 2109 passed, 8 skipped, 11 xfailed, 7 xpassed, 298 warnings in 138.78s (0:02:18) 
Test summary after the changes:
6 failed, 2109 passed, 8 skipped, 11 xfailed, 7 xpassed, 298 warnings in 85.06s (0:01:25)

Implemented bulk affine transformations with numpy

---

rasterio/_transform.pyx
rasterio/gdal.pxi
rasterio/transform.py
tests/test_transform.py

Resolves #2982 by adding a boolean option `tps` to the constructor of `GCPTransformer` that switches the behavior to use `GDALTPSTransform` instead of `GDALGCPTransform`.

expose GDALs TPS transformer as an option for GCPTransformer

---

rasterio/mask.py
tests/test_mask.py

This PR removes the check for `crop=True` and `invert=True` in `raster_geometry_mask`.  The enforced mutual exclusivity of crop and invert actually result a frustrating special case, and I think it is best to remove this check completely.
Here is each case considered and its meaning:
1. `crop=False, invert=False`: This is the default state. We get the full dataset where inside the shapes is unmasked (False) and outside the shapes is masked (True). This is used to process pixels inside shape boundaries.
2. `crop=True, invert=False`: This crops the dataset to the extent of the shapes, which is to say the bounding box of the union of the shapes.  Inside the shapes is still unmasked (False) and outside the shapes is masked (True). This is used to process pixels inside shape boundaries while …

Allow crop and invert in raster_geometry_mask

---

CHANGES.txt
rasterio/features.py
tests/test_features.py

Resolves #2743 by [defining an error out of existence](https://wiki.tcl-lang.org/page/Define+Errors+Out+of+Existence).
Also adds an option to *not* skip invalid shapes.

rasterize(): given an empty shapes sequence return an empty or filled array

---

CHANGES.txt
docs/topics/vsi.rst
rasterio/__init__.py
rasterio/_base.pyx
rasterio/_err.pyx
rasterio/_io.pyx
rasterio/_vsiopener.pyx
rasterio/errors.py
rasterio/gdal.pxi
requirements-dev.txt
tests/test_pyopener.py

This depends on PR https://github.com/rasterio/rasterio/pull/2898.
Resolves https://github.com/rasterio/rasterio/issues/2906.
Almost trivial after the work in #2898 😄 I'm going to force push to this PR's branch after #2898 is merged.
What do you think of [3dc1465](https://github.com/rasterio/rasterio/pull/2907/commits/3dc146528a4d3cce3db28409518bd7c504861067) @groutr @snowman2 ?

Support writing to Python files

---

rasterio/plot.py
tests/test_plot.py

As per this [GIS Stack question](https://gis.stackexchange.com/questions/457467/control-the-range-with-show-hist-of-rasterio), it could be useful to allow the caller to supply a `hist_range` argument to `rasterio.plot.show_hist` which would be passed to matplotlib instead of the internally generated range ([plot.py#L266](https://github.com/rasterio/rasterio/blob/main/rasterio/plot.py#L266)).  
The way I've implemented it also avoids `TypeError: matplotlib.axes._axes.Axes.hist() got multiple values for keyword argument 'range'` if a user passes a `range` kwarg to `show_hist`.  The docs were a bit confusing in regards to this as it sounded like all additional kwargs would be passed to the matplotlib Axes.hist method, however range could not.
While putting together a PR for this, I also made …

Add hist_range arg to rasterio.plot.show_hist

---

CHANGES.txt
rasterio/features.py
tests/test_features.py

Gives up output data type cleverness to allow deprecation/elimination of helper functions and removal of complicated tests.
Resolves #3004

Simplify rasterize

---

CHANGES.txt
docs/cli.rst
rasterio/errors.py
rasterio/rio/create.py
rasterio/rio/options.py
setup.cfg
tests/test_rio_create.py
tests/test_rio_shapes.py
tests/test_warnings.py

Resolves #3021.
`rio create` tries harder than other commands to avoid clobbering existing remote objects and datasets. It's a bit complicated. We might want to do the same for other commands at some point.

Add a rio create command.

---

CHANGES.txt
Dockerfile
Makefile
docs/topics/vsi.rst
rasterio/_vsiopener.pxd
rasterio/_vsiopener.pyx
rasterio/gdal.pxi
requirements-dev.txt
tests/test_filepath.py
tests/test_pyopener.py

Towards resolving #3027. Lots of work remains to generalize this beyond paths in the local filesystem, for which this feature isn't actually needed at all. We're only doing so for testing and development.
How far will we generalize this? This kind of I/O plugin is interesting to me, but the main point of it is to support hierarchical storage systems with proprietary authentication and authorization, aka "the Cloud". Sidecar files can't exist without a container, either an actual directory/folder or a shared prefix. Thus it seems fine to require that "filenames" passed to the opener be parseable as URIs and have a path component.
One complication for all this is that sidecar discovery requires either built-in knowledge of possible sidecar extensions for all formats or readir/ls and stat …

Sidecar support for Python openers

---

.github/workflows/tests.yaml
CHANGES.txt
Makefile
pyproject.toml
rasterio/__init__.py
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/rio/main.py
requirements-dev.txt
tests/test_cli_main.py
tests/test_rio_shapes.py
tests/test_warnings.py

Last 1.3 release, to make sure that we have wheels out there that will work with Numpy 2.0.
Note to self: Python 3.8 wheels for the release will have to be built with Numpy<2.

Rel 1.3.10

---

rasterio/_warp.pyx
tests/test_warp.py

Fixes #3051
Using an approximate transformer alongside source_geoloc_array can lead to undesirable artefacts, presumably as it is difficult to fit an approximate function to a dense grid of points.
Disable the use of approximate transformers in this case, as they already are for RPCs.

Don't use approximate transformer with source_geoloc_array

---

setup.py

Reverts #2168 
Follow-up to #3061 
The run-time dependency on setuptools was only added because `pkg_resources` was imported at run-time, but now that these imports have been removed, the package no longer depends on setuptools after installation.
This should be included in the next 1.4 pre-release.

Remove run-time dependency on setuptools

---

rasterio/merge.py

Addresses parts of the issue reported in rasterio/rasterio#3072
This PR fixes a typo in the computation of `max_pixels` in `rasterio.merge.merge()`:
Line 335 of `rasterio.merge.merge` was missing brackets around the denominator and thus computing `max_pixels`too large by a factor of `output_count**2`. This has been fixed.

Fix typo in calculation of `max_pixels` in `rasterio.merge.merge()`

---

.github/workflows/tests.yaml

GHA has changed the macos-latest alias to macos-14 (arm64), hence to get Intel Mac one now needs to explicitly select macos-13. Cf https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

tests.yaml: change macos-latest to macos-13

---

rasterio/merge.py
rasterio/rio/calc.py
rasterio/windows.py
tests/test_merge.py
tests/test_rio_calc.py
tests/test_windows.py

The existing `window_split` function was dependent on the dataset's dimensions and assumed zero offsets for rows and columns. This PR generalizes the function to split any arbitrary source window. This allows any region of interest in a dataset to be subdivided and processed in chunks.
For example:
```
src_win = windows.Window(10, 12, 3, 5)
subdivide(k, 3, 2)
[Window(col_off=10, row_off=12, width=2, height=3),
Window(col_off=12, row_off=12, width=1, height=3),
Window(col_off=10, row_off=15, width=2, height=2),
Window(col_off=12, row_off=15, width=1, height=2)]
```
I've renamed the function from `windows.window_split` to `windows.subdivide` (though happy to revert the name if desired). It seemed strange to prefix the function verb with `window` which sticks out among the other window …

Generalize window_split

---

rasterio/_io.pyx

Error encountered [here](https://github.com/corteva/geocube/actions/runs/9629708861/job/26559455123).
```
../../../micromamba/envs/test/lib/python3.10/site-packages/rasterio/features.py:126: in shapes
for s, v in _shapes(source, mask, connectivity, transform):
rasterio/_features.pyx:77: in _shapes
???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   ValueError: Unable to avoid copy while creating an array as requested.
E   If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
E   For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```

BUG: Use np.asanyarray in MemoryDataset for numpy 2 compat

---

rasterio/_vsiopener.pyx
tests/test_pyopener.py
tests/test_warp.py

Follow up to #3113.
Building overviews with multiple GDAL threads results in a deadlock. There is no such deadlock for multithreaded warping or TIFF decompression.
Implementation of `truncate()` was required by the warper, and probably by other untested features/drivers.

Add tests with multiple GDAL threads and implement truncate

---

rasterio/_vsiopener.pyx
rasterio/abc.py
tests/test_pyopener.py

another take at #2969
GDAL provide a method to fetch [multiple range requests](https://github.com/OSGeo/gdal/blob/dd3396b45944799ed6492267c2754f26f635a7dc/port/cpl_vsil_plugin.cpp#L259-L341) (when supported by the driver) in the VSI plugin. 
Without this, all drivers will make single (non-merged) range requests when using a VSIPlugin, meaning that when using vsi opener, the GTIFF driver will emit a ton of GET requests instead of one `merged` request (see https://github.com/rasterio/rasterio/pull/2969#issuecomment-1814298097, https://github.com/rasterio/rasterio/pull/2969#issuecomment-1830365788)
This PR does:
- add `hasattr(opener, "read_multi_range")` check when registering the Opener object, and add a `VSIFilesystemPluginReadMultiRangeCallback` is found.
- add …

Python file opener VSI plugin: read-multi-range support 

---

rasterio/rio/convert.py

Allows converting large rasters without reading the entire raster into memory.

Add chunking to rio-convert.

---

rasterio/rio/clip.py
tests/test_rio_clip.py

Avoid reading potentially large rasters in rio clip by chunking the read operations. Added a test to for the basic functionality of clip to ensure the content of the clipped region is correct.

Clip rasters in chunks

---

rasterio/transform.py
tests/test_transform.py

This PR changes the return type of `xy()` and `rowcol()` to be numpy arrays instead of coercing to Python lists. 
These functions now use numpy internally to make the computation more efficient when working with lots of points. Returning a numpy array feels much more sensible and makes working with the transformed points easier.

Return numpy arrays from transformations

---

CHANGES.txt
rasterio/_features.pyx
rasterio/features.py
tests/conftest.py
tests/test_features.py

I noticed polygonizing an image of type `float64` isn't supported using `features.shapes`, while `gdal.Polygonize` does.
This PR enables support for the dtypes that were blocked now but do seem to work in practice: `float64`, `int8`.

ENH: enable support for extra dtypes in features.shapes: int8 and float64

---

setup.py

This PR replaces setuptools' deprecated [`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html) module with a simple regular expression to find the first three integers. It should handle (e.g.) "3.6.3RC1" to find (3, 6, 3).
It will clear up this build message:
> <string>:22: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

BLD: remove pkg_resources.parse_version

---

CHANGES.txt
rasterio/_env.pyx
rasterio/env.py
tests/test__env.py
tests/test_data_paths.py
tests/test_env.py

Because header.dxf (for the OGR DXF driver) isn't packaged with wheels anymore. Resolves #3153

Use gdalvrt.xsd as a marker for GDAL's data directory

---

CHANGES.txt
rasterio/_io.pxd
rasterio/_warp.pyx
rasterio/warp.py
tests/test_warp.py

Background: `reproject()` can take an array and return an array. GDAL's warper requires input and output GDALDatasetH, so we construct them using the GDAL "MEM" driver, pointing at the memory location of two arrays.
What this PR does is add alpha bands to those datasets when the inputs and outputs are masked arrays. For input, 3-D array masks are reduced to a 2-D array via `logical_or()` (because GDAL needs a single alpha mask channel). For output, the alpha mask band is repeated over the number of image bands.
I suspect the approach could be made more efficient. Copying is required in some cases because the "MEM" driver needs a precise memory layout.
Resolves #2575.

Use mask as alpha when reprojecting a masked array

---

CHANGES.txt
Dockerfile
pyproject.toml
rasterio/__init__.py
rasterio/_env.pyx
rasterio/_io.pyx
rasterio/_warp.pyx
rasterio/env.py
rasterio/merge.py
tests/test__env.py
tests/test_colormap.py
tests/test_data_paths.py
tests/test_env.py
tests/test_mask_creation.py
tests/test_merge.py
tests/test_rio_merge.py
tests/test_update.py

Nevermind the branch name. This will be 1.3.11.
The numpy project deleted their 2.0.0rc1 PyPI release and thus 1.3.10 can no longer be built from source. This PR lets numpy versions >=2.0.0,<3 be used to build 1.3.11.
Additions: numpy 2.1 and GDAL 3.9 compatibility, plus backports of #3133 and #3140.

Release 1.3.11

---

docs/topics/transforms.rst

Resolves #3040
Detail using a constant height offset via `rpc_height` keyword argument in instantiation of transformer.

docs: :memo: clarify usage of rpc_height in RPCTransformer usage example

---

tests/test_rio_info.py
tests/test_subdatasets.py

Some tests were accidentally skipped even though netCDF driver was installed due to incorrect capitalization. Should be `netCDF` instead of `NetCDF`.
```
SKIPPED [1] tests/test_rio_info.py:397: GDAL not compiled with NetCDF driver.
...
SKIPPED [1] tests/test_subdatasets.py:10: GDAL not compiled with NetCDF driver.
```
Sample Output from `with rasterio.Env() as env: print(env.drivers().keys())`
> dict_keys(['VRT', 'GTI', 'DERIVED', 'GTiff', 'COG', 'NITF', 'RPFTOC', 'ECRGTOC', 'HFA', 'SAR_CEOS', 'CEOS', 'JAXAPALSAR', 'GFF', 'ELAS', 'ESRIC', 'AIG', 'AAIGrid', 'GRASSASCIIGrid', 'ISG', 'SDTS', 'DTED', 'PNG', 'JPEG', 'MEM', 'JDEM', 'GIF', 'BIGGIF', 'ESAT', 'FITS', 'BSB', 'XPM', 'BMP', 'DIMAP', 'AirSAR', 'RS2', 'SAFE', 'PCIDSK', 'PCRaster', 'ILWIS', 'SGI', 'SRTMHGT', 'Leveller', 'Terragen', …

TST: Check for lowerCase netCDF instead of NetCDF

---

tests/test_pyopener.py
tests/test_read_boundless.py

The network marker is already used in other places, but these tests are new.
PS, 1.4.0 is tagged off of a commit that isn't in `main` or `maint-1.4`, and seems to have a duplicate commit (based on its message); not sure if that's intentional or not.

Mark additional tests that use the network

---

.github/workflows/tests.yaml
rasterio/_warp.pyx
tests/test_warp.py

https://github.com/rasterio/rasterio/actions/runs/11349030115/job/31564203380 showed that Rasterio 1.4.1 is not quite ready for GDAL 3.10.
Our `MEM::` dataset gets opened several times in `_reproject()`.

Test maint-1.4 against GDAL 3.10-to-be and add more MEM file checks

---

rasterio/crs.pxd
rasterio/crs.pyx
rasterio/gdal.pxi
tests/test_crs.py
tests/test_rio_edit_info.py

Change to `CRS.__eq__()` is based on #3208.
Several evaluations of `to_epsg()`, which is slow, are replaced by a check of `CRS._epsg`.
A notable change in behavior is that `CRS.from_epsg(4326).to_dict()` no longer returns `{"init": "epsg:4326"}`, but the full PROJ definition. PROJ4 init files aren't quite deprecated yet, but we need to steer users away from this. See https://github.com/rasterio/rasterio/issues/1809#issuecomment-546019513 (which I'll try to replace with a better reference).

Eliminate much to_epsg() usage and speed up __eq__()

---

CHANGES.txt
rasterio/transform.py

The change was caused by replacing `math.floor()` (given floats, returns ints) with `numpy.floor()` (returns floats).

Restore default behavior of rowcol(), returning ints

---

rasterio/__init__.py

It's rarely a good idea now because it reads the entire file into memory.
Resolves #3232.

Add notes about passing open files to rasterio.open()

---

CHANGES.txt
rasterio/merge.py
rasterio/windows.py
tests/test_merge.py
tests/test_rio_merge.py

Standardizing window alignment for use in compositing allows us to avoid large virtual sources and operate on smaller arrays when merging. This improves performance by ~50x for the case of many small datasets merged into one large dataset.
Only one test needed adjustment in the end.
Resolves #3228

Eliminate boundless reads in merge, new compositing implementation

---

.gitignore
rasterio/crs.pxd
rasterio/crs.pyx
rasterio/gdal.pxi
tests/test_crs.py

Following a discussion on the rasterio groups.io email list,
This PR adds a new function `.to_geodetic` that is inspired by pyproj's `.geodetic_crs` function to return the corresponding base geographic CRS for a given CRS. This is helpful for projections that may not use common geographic CRSs and for cases when you want to know what geographic CRS to use for vector features that minimizes the work needed to get to projected coordinates or vice versa.
I went with the name `to_geodetic` for the moment as it is returning a new object that is transformed from the parent object, and reflects the intent imho better than `.geodetic_crs` which reads more as a property of the CRS, but as a new object is created... Anyways I don't hold a strong desire here on the name of the function.
`geodetic` …

Adds CRS.geodetic_crs property

---

CHANGES.txt
rasterio/_fill.pyx
rasterio/fill.py

Part enhancement, part bug fix since we've generally considered missing options to be bugs.
Resolves #3175.

Support all GDALFillNodata() options in rasterio.fill

---

rasterio/features.py

Addresses #3202 .
We know we are generating a mask, and can inform rasterize to use uint8 dtype. Because the return is uint8, we can simply return a boolean view of the array.

Force uint8 dtype for geometry mask

---

rasterio/_features.pyx

This applies the changes made in https://github.com/Toblerity/Fiona/pull/1462 to rasterio's vendored GeomBuilder.

Lift ndim check out of loop in GeomBuilder

---

CHANGES.txt
rasterio/_base.pyx
rasterio/cache.pyx
rasterio/gdal.pxi
setup.py
tests/test_cache.py

I like "invalidate" as a method name. These two methods help solve the problem pointed out in the last sentence of [RFC 9111 Section 4.4](https://httpwg.org/specs/rfc9111.html#invalidation). If you combine Rasterio with, say, uploading files to S3 using boto3, those PUTs don't go through Rasterio's cache and thus can't be smartly invalidated.
Resolves #3275

Introducing cache.invalidate() and invalidate_all()

---

CHANGES.txt
Makefile
rasterio/_base.pyx
rasterio/rio/info.py
rasterio/rio/sample.py
rasterio/rio/warp.py
rasterio/serde.py
tests/test_read.py

Rasterio now defines a `to_json()` function to use with `json.dumps()`. By default it returns its argument. To turn objects like Affine instances into JSON serializable tupes, we register functions with the `to_json()` dispatcher in `rio/info.py`, `rio/sample.py`, and `rio/warp.py`.
I've tested this locally with the main branch of the affine project.
Resolves #3298.

Add support for affine 3.0 Affine class serialization

---

rasterio/fill.py

`**filloptions` kwargs are not passed to `_fillnodata` function, and, so, are never used. 
Is it for some reason or it is just a mistake?

Fix `**filloptions` not being passed to `_fillnodata`

---

rasterio/_warp.pyx
tests/test_warp.py

Masked arrays can have their `mask` attribute set to [`numpy.ma.nomask`](https://numpy.org/doc/stable/reference/maskedarray.baseclass.html#numpy.ma.nomask) to indicate that no values are masked. If I try to reproject such an array using `rasterio.warp.reproject`, I get the following error:
```
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)
```
The error comes from this line: https://github.com/rasterio/rasterio/blob/7adb4f5b32c006067cca2aaa8a4004ed100f994a/rasterio/_warp.pyx#L382
This pull request is an attempt to fix the issue by filling the alpha mask with `255` if the input array's mask is set to the `numpy.ma.nomask` constant.

Fix reproject for masked arrays with numpy.ma.nomask

---

rasterio/_warp.pyx

This PR makes `tolerance` a user-defined argument in `rio.warp.reproject`.
I matched the argument description of `WarpedVRTReaderBase` for consistency:
https://github.com/rasterio/rasterio/blob/b59373148294a6b3a729397c5828e28ab1fd4d53/rasterio/_warp.pyx#L943
Resolves #3324

Modify `tolerance` to be an argument in `rio.warp.reproject`

---

tests/test_warp.py

Plus reformatting of the test module. See https://github.com/OSGeo/gdal/issues/11711. Resolves #3301.

Change nearest neighbor warp expectations at GDAL 3.10.2

---

docs/quickstart.rst

I noticed that the example of creating a raster file in the quickstart documents end up with the creation of a raster with "negative pixel height" ("upside down"). Following the steps in the quickstart docs, and then loading the file shows this in two separate ways: we can examine the bounds directly, and also induce an error by attempting to merge just the single file created:
```python
>>> import rasterio
>>> import numpy as np
>>> x = np.linspace(-4.0, 4.0, 240)
>>> y = np.linspace(-3.0, 3.0, 180)
>>> y = np.linspace(-3.0, 3.0, 180)
>>> X, Y = np.meshgrid(x, y)
>>> Z1 = np.exp(-2 * np.log(2) * ((X - 0.5) ** 2 + (Y - 0.5) ** 2) / 1 ** 2)
>>> Z2 = np.exp(-3 * np.log(2) * ((X + 0.5) ** 2 + (Y + 0.5) ** 2) / 2.5 ** 2)
>>> Z = 10.0 * (Z2 - Z1)
>>> from rasterio.transform import Affine
>>> …
```

Update quickstart example raster creation with correct pixel height (not upside down)

---

docs/conf.py

Resolves the following compatibility warnings/conversions in CI:
```
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
intersphinx inventory has moved: https://gdal.org/objects.inv -> https://gdal.org/en/stable/objects.inv
```

Docs: update conf.py with modern Sphinx syntax

---

rasterio/rio/bounds.py
rasterio/rio/calc.py

When Sphinx sees an asterisk, it assumes you want italics. However, asterisks also appear in code or as math. We need to either convert these to formal code/math or escape the asterisk to prevent the following warnings in RtD CI:
```
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/checkouts/3340/docs/api/rasterio.rio.bounds.rst:4: WARNING: Inline emphasis start-string without end-string. [docutils]
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/checkouts/3340/docs/api/rasterio.rio.calc.rst:19: WARNING: Inline emphasis start-string without end-string. [docutils]
```

Docs: asterisk does not always mean italics

---

rasterio/merge.py

Fixes the formatting of the "pre-defined method" section of the [merge](https://rasterio.readthedocs.io/en/stable/api/rasterio.merge.html#rasterio.merge.merge) docs.

rasterio.merge.merge: fix formatting of pre-defined method docs

---

docs/api/rasterio._loading.rst

`rasterio._loading` appears to be a historical module that was removed. This rst page results in the following warning in RtD CI:
```
WARNING: autodoc: failed to import module '_loading' from module 'rasterio'; the following exception was raised:
['Traceback (most recent call last):\n', '  File "/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3340/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 269, in import_object\n    module = import_module(modname, try_reload=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3340/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 172, in import_module\n    raise ModuleNotFoundError(msg, name=modname)  # NoQA: …
```

Docs: remove docs for rasterio._loading

---

rasterio/plot.py

Fixes the following warnings in RtD CI:
```
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3340/lib/python3.11/site-packages/rasterio/plot.py:docstring of rasterio.plot.contrast_strech:2: WARNING: Block quote ends without a blank line; unexpected unindent. [docutils]
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3340/lib/python3.11/site-packages/rasterio/plot.py:docstring of rasterio.plot.contrast_strech:3: CRITICAL: Unexpected section title or transition.
```
`contrast_stretch` does not appear in the documentation.

rasterio.plot: fix parameters section title

---

rasterio/features.py

Sphinx treats things that end with an underscore as a hyperlink. However, `rasterio.bool_` is an object, not a link. We need to either escape the underscore or convert it to a formal link. This resolves the following warnings in RtD CI:
```
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3340/lib/python3.11/site-packages/rasterio/features.py:docstring of rasterio.features.shapes:: ERROR: Unknown target name: "rasterio.bool". [docutils]
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3340/lib/python3.11/site-packages/rasterio/features.py:docstring of rasterio.features.sieve:: ERROR: Unknown target name: "rasterio.bool". [docutils]
```
You can also check the docs and see the broken link that gets generated.

rasterio.features: rasterio.bool_ is not an rst link

---

docs/api/rasterio._base.rst
docs/api/rasterio._env.rst
docs/api/rasterio._err.rst
docs/api/rasterio._example.rst
docs/api/rasterio._features.rst
docs/api/rasterio._filepath.rst
docs/api/rasterio._fill.rst
docs/api/rasterio._io.rst
docs/api/rasterio._transform.rst
docs/api/rasterio._warp.rst

The following hidden modules have autodoc files, but aren't included in `index.rst`, meaning we waste time on generating webpages but never serve them. This results in the following warning in RtD CI:
```
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/checkouts/3348/docs/api/rasterio._base.rst: WARNING: document isn't included in any toctree [toc.not_included]
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/checkouts/3348/docs/api/rasterio._env.rst: WARNING: document isn't included in any toctree [toc.not_included]
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/checkouts/3348/docs/api/rasterio._err.rst: WARNING: document isn't included in any toctree [toc.not_included]
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/checkouts/3348/docs/api/rasterio …
```

Docs: remove documentation of hidden modules

---

requirements.txt
setup.py

Due to pallets/click#2939, input from a file is broken. This should be fixed by pallets/click#2940, which is scheduled to be in click 8.3.0.

BLD: Avoid click 8.2.*

---

rasterio/enums.py

Resolves the following warnings in RtD CI:
```
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3351/lib/python3.11/site-packages/rasterio/enums.py:docstring of rasterio.enums.Resampling.average:1: WARNING: duplicate object description of rasterio.enums.Resampling.average, other instance in api/rasterio.enums, use :no-index: for one of them
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3351/lib/python3.11/site-packages/rasterio/enums.py:docstring of rasterio.enums.Resampling.bilinear:1: WARNING: duplicate object description of rasterio.enums.Resampling.bilinear, other instance in api/rasterio.enums, use :no-index: for one of them
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3351/lib/python3.11/site-packages/rasterio/enums.py:docstring of …
```

rasterio.enums.Resampling: fix enum docs

---

rasterio/coords.py

Resolves the following warnings in RtD CI:
```
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3350/lib/python3.11/site-packages/rasterio/coords.py:docstring of rasterio.coords.BoundingBox.bottom:1: WARNING: duplicate object description of rasterio.coords.BoundingBox.bottom, other instance in api/rasterio.coords, use :no-index: for one of them
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3350/lib/python3.11/site-packages/rasterio/coords.py:docstring of rasterio.coords.BoundingBox.left:1: WARNING: duplicate object description of rasterio.coords.BoundingBox.left, other instance in api/rasterio.coords, use :no-index: for one of them
/home/docs/checkouts/readthedocs.org/user_builds/rasterio/conda/3350/lib/python3.11/site-packages/rasterio/coords.py:docstring …
```

rasterio.coords.BoundingBox: fix attribute docs

---

rasterio/rio/edit_info.py
rasterio/rio/options.py

According to click upstream [1], `default=False` was not supported with `flag_value='some string'`. Omitting the argument will keep it `None`, which should be about the same as `False`, mostly.
[1] https://github.com/pallets/click/issues/3054#issuecomment-3243872056

Remove default=False for flag_value of str type
