rasterio/rasterio

rasterio/rio/merge.py, tests/test_rio_merge.py
=> Logic and tests for merge without nodata.

rasterio/_base.pyx, tests/test_transform.py
=> Add window_transform method.

CHANGES.txt, docs/cli.rst, rasterio/__init__.py, rasterio/_features.pyx, rasterio/_fill.pyx, rasterio/features.py, rasterio/fill.py, rasterio/rio/calc.py, rasterio/rio/main.py, requirements-dev.txt, requirements.txt, setup.py, tests/test_features_sieve.py, tests/test_rio_calc.py
Towards closing #175.
Usage, for now, like this:
$ rio calc "0.10*{1} + 125" tests/data/shade.tif out.tif
Results in a new hillshade with shade values of 125 instead of 0.
=> rio-calc, take 1

CHANGES.txt, rasterio/_base.pyx, tests/test_meta.py
=> Add missing keywords: blockxsize, blockysize, tiled

rasterio/_fill.pyx, rasterio/fill.py, rasterio/rio/calc.py, tests/test_rio_calc.py
Also add masking option for rio-calc.
Closes #309. Closes #311.
=> Remove in place nodata filling.

rasterio/rio/features.py, rasterio/rio/rio.py, tests/test_rio_features.py
=> Improvements to rio-shapes

benchmarks/calc.sh, rasterio/_io.pyx, rasterio/rio/calc.py, rasterio/rio/features.py, rasterio/rio/info.py, setup.py, tests/test_band_masks.py, tests/test_read.py, tests/test_read_resample.py, tests/test_rio_calc.py, tests/test_rio_features.py, tests/test_tool.py
Closes #300 and also #285 (Mask Quest).
=> Change read's default to masked=False

rasterio/_warp.pyx, tests/test_warp.py
Resolves #336 
Cut out boilerplate in _warp.py for managing ```osr``` objects and replaced with ```_base._osr_from_crs``` which handled that more completely.
Added a few tests to prove that it was working.
=> Added support for EPSG codes to reproject

tests/conftest.py
=> fix link to tests/README

README.rst
I think this covers the remainder of what I had in mind in #361
=> Updated README for Windows builds

rasterio/_base.pyx, tests/test_profile.py
=> Add a .profile property to DatasetReader

rasterio/rio/info.py
updates info printed when using `rio insp`.
=> update rio insp help

docs/cli.rst, rasterio/rio/bands.py, rasterio/rio/convert.py, rasterio/rio/options.py, tests/test_rio_bands.py
Closes #422.
We'll need a new release.
=> Change --photometric=rgb to --rgb

rasterio/rio/main.py, setup.py
@sgillies @brenan-ward ready for review.  See #421 for more info - closes #421.
=> Use click-plugins instead of cligj.plugins

examples/polygonize.py
=> Updated examples/polygonize.py

rasterio/_io.pyx, tests/test_colormap.py
I think I may have made the situation worse in my previous commit to this method.
Closes #395.
@geowurster this is all the way ready. can you review?
=> Warn that alpha may be ignored instead of raising

.travis.yml, rasterio/_base.pyx, rasterio/_gdal.pxd, rasterio/_io.pyx, rasterio/rio/info.py, requirements-dev.txt, tests/test_checksum.py, tests/test_rio_info.py
These are the same integer checksums as in gdal_translate.
Closes #433.
=> Surface GDAL checksum in API and CLI

docs/cli.rst, rasterio/coords.py, rasterio/rio/convert.py, rasterio/rio/features.py, setup.py, tests/test_rio_convert.py
Adds support for ```rio clip``` as per comments in #323
=> Added rio-clip

setup.py, tests/test_rio_convert.py
Fixes bad reference in ```setup.py```
=> Fix reference to rio-clip

.travis.yml
Check this out. I just cut the build times in half :)
I'll merge this as it's a no-brainer.
=> Travis sudo: false

.travis.yml, requirements-dev.txt
Closes #452 
Lets see what Travis thinks ...
=> Cython 0.23.1

rasterio/crs.py, tests/test_crs.py
Also added regression test.
Ready to go, pending Travis.
=> Fixed bug with EPSG contained in a proj4 string

setup.py
=> Add rasterio.tools to install packages.

.travis.yml, scripts/travis_gdal_install.sh
I apologise in advance if this is stepping on any toes, but I went ahead and applied @rbuffat's multiple GDAL testing patch from Toblerity/Fiona#267 to rasterio, just to see if it worked.
This is regarding #482.
=> test on multiple gdal versions, caching the builds

rasterio/_io.pyx, tests/test_blocks.py, tests/test_profile.py
=> Guard against block sizes larger than window sizes

rasterio/errors.py, rasterio/rio/bands.py, rasterio/rio/calc.py, rasterio/rio/features.py, rasterio/rio/helpers.py, rasterio/rio/info.py, rasterio/rio/merge.py, rasterio/rio/options.py, tests/test_rio_features.py, tests/test_rio_helpers.py, tests/test_rio_info.py, tests/test_rio_merge.py, tests/test_rio_options.py
Plus some consolidation of existing options.
Closes #539
=> Add a force_overwrite option

rasterio/_io.pyx, tests/test_warp.py
=> Added support for NaN in warp.

rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/errors.py, tests/test_warp_transform.py
Also rename an error class.
Closes #595
=> Add tests to shake up warp transformer creation

.travis.yml, CHANGES.txt, rasterio/__init__.py, rasterio/_base.pxd, rasterio/_base.pyx, rasterio/_drivers.pyx, rasterio/aws.py, rasterio/five.py, rasterio/rio/helpers.py, rasterio/rio/info.py, rasterio/rio/main.py, rasterio/rio/options.py, rasterio/vfs.py, scripts/travis_gdal_install.sh, tests/test_aws.py, tests/test_driver_management.py, tests/test_rio_info.py, tests/test_vfs.py
Using a context manager for GDAL's /vsis3/ config options.
=> Access to raster datasets on S3

.travis.yml, CHANGES.txt, rasterio/aws.py, rasterio/rio/bands.py, rasterio/rio/features.py, rasterio/rio/info.py, rasterio/rio/main.py, rasterio/rio/sample.py, setup.py, tests/test_aws.py, tests/test_rio_features.py, tests/test_rio_sample.py
It's an optional dependency: `pip install -U rasterio[s3]`
Closes #610
=> Defer to boto3 for credentials

scripts/travis_gdal_install.sh
=> Use the GDAL 2.1beta1

.travis.yml, scripts/travis_gdal_install.sh
=> catch coveralls failures so travis always sees exit code 0

.travis.yml, CHANGES.txt, rasterio/__init__.py, rasterio/_base.pyx, rasterio/_drivers.pyx, rasterio/_gdal.pxd, rasterio/aws.py, rasterio/rio/bounds.py, rasterio/rio/clip.py, rasterio/rio/insp.py, rasterio/rio/main.py, rasterio/rio/sample.py, rasterio/rio/shapes.py, setup.py, tests/test_aws.py, tests/test_deprecations.py, tests/test_rio_convert.py, tests/test_rio_main.py
=> S3 support in the CLI as advertised

rasterio/coords.py, rasterio/crs.py, rasterio/dtypes.py, rasterio/enums.py, rasterio/errors.py, rasterio/features.py, rasterio/fill.py, rasterio/five.py, rasterio/mask.py
Will supersede #627, cleaned up commits with cherry pick. Builds are succeeding on my travis, so should here too.
=> Docstring fix

rasterio/five.py, rasterio/plot.py, rasterio/rio/insp.py, rasterio/rio/main.py, rasterio/tool.py, tests/test_aws.py, tests/test_deprecations.py, tests/test_open.py, tests/test_rio_convert.py, tests/test_rio_features.py, tests/test_rio_info.py, tests/test_rio_merge.py, tests/test_rio_warp.py, tests/test_transform.py
Ongoing work towards 100% coverage
=> Coverage quest

rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/enums.py, rasterio/errors.py, rasterio/rio/overview.py, rasterio/warp.py, tests/test_overviews.py, tests/test_rio_overview.py, tests/test_warp.py
I think this is more like it and pretty close to closing #615. Thoughts @perrygeo @eseglem?
=> One single resampling enum

rasterio/_base.pyx, tests/test_blocks.py, tests/test_nodata.py, tests/test_read.py, tests/test_rio_convert.py, tests/test_update.py, tests/test_write.py
=> return tuples, not lists from DatasetReader

setup.py
@sgillies is this all there is to it?
closes #519
=> only include vendorized rasterfill.cpp if using gdal < 2

docs/resampling.rst
Doc change only. Helps clarify #668 a bit
=> resampling doc

.travis.yml, scripts/travis_gdal_install.sh
Adds Python 3.5 to the matrix and upgrades to the final GDAL 2.1.0 release.
=> Add python 3.5

AUTHORS.txt, CHANGES.txt, README.rst, rasterio/__init__.py
Final touches. After this passes and I merge, I'll tag master as `0.35.0`.
=> Oh three five

rasterio/__init__.py, rasterio/env.py, rasterio/features.py, rasterio/fill.py, rasterio/vfs.py, rasterio/warp.py, tests/test_env.py, tests/test_vfs.py
Closes #694 and #695.
@brendan-ward @geowurster @perrygeo I came to the conclusion that a decorator is the way to go, but I'm open to second opinions.
Work is done. I'd like to get a 0.35.1 release out ASAP.
=> Oh three five fixes

docs/cli.rst, rasterio/_base.pyx, rasterio/rio/main.py
Also change affine module usage to future proof Rasterio.
=> Add plugin instructions to CLI main.py

README.rst
=> Alternative GDAL install instructions for OSX

tests/test_dtypes.py
Haven't been able to figure out #714 yet but this will help should someone pick it up at the sprint
```
$ py.test tests/test_dtypes.py::test_complex
```
=> xfail test for complex dtype

README.rst, docs/concurrency.rst, docs/reproject.rst, examples/async-rasterio.py, examples/concurrent-cpu-bound.py, examples/rasterize_geometry.py, examples/reproject.py, examples/sieve.py, examples/total.py, rasterio/__init__.py, rasterio/_example.pyx, setup.py
=> import numpy as np in docs and examples

CITATION.txt
Added a simple file with citation information, called `CITATION.txt`.
Fixes #654.
=> Added simple CITATION file

tests/test_image_structure.py, tests/test_warp_transform.py
Cherry picked from #768 so these are not held up by the rest of the changes.
=> Rename two tests so they are used.

rasterio/rio/merge.py, tests/test_rio_merge.py
=> Rio merge copy colormap

docs/writing.rst, rasterio/plot.py, tests/test_plot.py
=> Plot extents with array and transform

rasterio/__init__.py
=> bump version to 1.0.dev1

rasterio/__init__.py, rasterio/_io.pyx, rasterio/drivers.py, tests/test_driver_policy.py, tests/test_write.py
Replaces the BAD_WRITE_DRIVERS list in _io.
=> New blacklist policy

rasterio/__init__.py, rasterio/_base.pxd, rasterio/_base.pyx, rasterio/_features.pyx, rasterio/_fill.pyx, rasterio/_gdal.pxd, rasterio/_io.pxd, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/gdal.pxi, rasterio/io.py, rasterio/plot.py, tests/test_read.py, tests/test_write.py
=> New io module

rasterio/_base.pyx, rasterio/profiles.py, rasterio/rio/info.py, tests/test_profile.py
=> New affine/transform safe profile class

rasterio/_base.pyx, rasterio/io.py, rasterio/transform.py, rasterio/windows.py, tests/test_transform.py
=> rowcol and xy functions to take arrays

rasterio/rio/env.py, rasterio/rio/info.py, rasterio/rio/main.py, tests/test_env.py
Tested using a new `--credentials` option for rio-env.
Resolves #838
=> Add a test of AWS profile option

rasterio/rio/blocks.py, rasterio/rio/bounds.py, rasterio/rio/calc.py, rasterio/rio/clip.py, rasterio/rio/convert.py, rasterio/rio/edit_info.py, rasterio/rio/insp.py, rasterio/rio/mask.py, rasterio/rio/merge.py, rasterio/rio/overview.py, rasterio/rio/rasterize.py, rasterio/rio/sample.py, rasterio/rio/shapes.py, rasterio/rio/stack.py, rasterio/rio/transform.py, rasterio/rio/warp.py, tests/test_rio_calc.py, tests/test_rio_convert.py, tests/test_rio_features.py, tests/test_rio_info.py, tests/test_rio_merge.py, tests/test_rio_stack.py, tests/test_rio_warp.py
Migrate all tests over to invoking main_group with a named command.
Resolves #841
=> Get env from main ctx

rasterio/features.py, tests/test_features.py
=> enforce that rasterize out_shape is 2D

rasterio/__init__.py, rasterio/_base.pxd, rasterio/_base.pyx, rasterio/_gdal.pxd, rasterio/_io.pxd, rasterio/_io.pyx, rasterio/io.py, rasterio/rio/edit_info.py, rasterio/rio/info.py, tests/test_descriptions.py, tests/test_rio_info.py, tests/test_units.py
=> Add support for GDAL units

rasterio/_base.pxd, rasterio/_base.pyx, rasterio/_io.pyx, rasterio/rio/edit_info.py, rasterio/rio/info.py, tests/test_descriptions.py, tests/test_rio_info.py
Since a dataset's description isn't modifiable, or even useful, this is more concise and a better fit with `set_units()`.
=> Rename set_band_description to set_description

rasterio/rio/helpers.py, rasterio/rio/options.py, rasterio/warp.py, tests/test_rio_features.py, tests/test_rio_helpers.py
=> -o no longer implicitly overwrites

.travis.yml, docs/index.rst, docs/intro.rst, docs/quickstart.rst, docs/switch.rst
Resolves #866. Currently published at https://mapbox.github.io/rasterio/switch.html.
I'm sure there are some edits to be made, but this is ready for review. @AsgerPetersen, I'd be extra grateful for your comments as developer that goes back and forth between Rasterio and GDAL's Python.
=> Switching from osgeo.gdal

rasterio/sample.py, tests/test_sampling.py
=> support single int for sample indexes

rasterio/env.py
=> turn off implicit jpeg overview in default env

rasterio/_warp.pyx
=> release gil for ChunkAndWarp

rasterio/__init__.py, rasterio/_drivers.pyx, rasterio/_gdal.pxd, rasterio/env.py, rasterio/warp.py, tests/test_env.py
Work in progress.
Closes #876
Closes #902
=> Push and pop error handler within Env context

rasterio/_base.pyx, rasterio/_gdal.pxd, rasterio/_io.pxd, rasterio/_io.pyx, rasterio/gdal.pxi, rasterio/io.py, tests/test_memoryfile.py
=> MemoryFile

rasterio/io.py
=> Import DatasetBase into io.py

rasterio/_gdal.pxd, rasterio/_io.pyx, rasterio/gdal20.pxi, rasterio/gdal21.pxi, rasterio/rio/edit_info.py, rasterio/rio/options.py, setup.py, tests/test_rio_info.py, tests/test_rio_options.py, tests/test_update.py
=> Initial support for GDALDeleteRasterNoDataValue()

rasterio/_warp.pyx
=> delete GDALWarpOperation object

rasterio/__init__.py, tests/test_memoryfile.py
It took me long enough, but now I get what `contextlib.contextmanager` is about :)
Resolves #964
=> Lightweight context managers around file objects and memory files

rasterio/rio/edit_info.py, tests/test_rio_info.py
fixes #970
cc @jacquestardie @sgillies
=> rio edit-info --unset-crs

rasterio/_env.pyx
=> Use stdcall convention for callback on windows

rasterio/_features.pxd, rasterio/_features.pyx, tests/test_warp.py
And a test refactor that makes results less sensitive to GDAL version.
Resolves #1023
=> Add missing builder methods

rasterio/_crs.pyx, tests/test_crs.py
=> Test for empty CRS equality

rasterio/_crs.pyx, tests/test_crs.py
Reverts mapbox/rasterio#1036. Let's have more discussion and consensus on this.
=> Revert "Test for empty CRS equality"

.travis.yml, rasterio/errors.py, rasterio/warp.py, tests/test_warp.py
Released yesterday: http://download.osgeo.org/gdal/2.2.0/
=> Add GDAL 2.2.0 to Travis build matrix

rasterio/_warp.pyx, tests/test_warp.py
=> Add test for fix

rasterio/_crs.pyx, tests/test_crs.py
Closes https://github.com/mapbox/rasterio/issues/869
Can confirm.  Will help those migrating code from `osgeo.gdal`.
=> + CRS.from_wkt()

rasterio/rio/warp.py
This PR implement's gdalwarp's `-tap` option
>  align the coordinates of the extent of the output file to the values of the target resolution, such that the aligned extent includes the minimum extent.
Don't merge yet, No tests. Just getting out there for visibility.
=> [wip] Target align pixels

.gitignore, requirements-dev.txt, requirements.txt
`requirements.txt` and `requirements-dev.txt` were out of sync with each other with respect to versions of some dependencies.  I used the latest from either of the files in this case.
I also sorted the dependencies so that it is easier to compare to two files and ensure parity.
=> Sync versions of dependencies

rasterio/_env.pyx, rasterio/_err.pyx, rasterio/_io.pyx
Also cleaned up an import and removed a Cython warning.
=> Resolve test segfaults on OSX

rasterio/__init__.py, rasterio/_env.pyx, rasterio/env.py, rasterio/rio/env.py, tests/test_env.py
=> Stop open's inner Env from clobbering outer env creds

rasterio/_warp.pyx
Resolves #1166 
Reprojecting an ndarray using GCPs resulted in a black image. Reason for the issue is that the parameter `srcwkt` wasn't properly initialized. I unified the variable initialization and added checks for method results.
=> Fix GCP based reprojection

docs/topics/georeferencing.rst, docs/topics/reproject.rst, tests/test_plot.py
Per deprecation of affine argument.
=> Change a few affine -> transform in tests/docs

rasterio/_io.pyx
This silences deprecation warnings.
=> Use width/height instead of num_cols/num_rows

CHANGES.txt, rasterio/vfs.py, tests/test_vfs.py
=> Support GET parameters in URLs

rasterio/_io.pyx
From https://github.com/mapbox/rasterio/commit/70b2bc9b808dcea41be5ae9168dd83f232a788b2#r26200429
@jdmcbr Switched log message to `DEBUG`.
=> Shush noisy logs

rasterio/mask.py, tests/test_mask.py
=> add indexes parameter to rasterio.mask.mask

rasterio/_features.pyx, rasterio/features.py, tests/test_features.py
=> Use enum for rasterize merge algorithm

examples/sieve.py, examples/total.py
Thanks to @citibeth for pointing out some issues with our examples 👍 
This PR should fix the issues noted in the following issues:
* resolves #1257 
* resolves #1258
=> fix known issues in examples

docs/topics/reproject.rst
This change worked for me. Proposing in case this is the new way and just need to update docs.
=> RESAMPLING -> Resampling

docs/topics/virtual-warping.rst
Add import, fix bounding box output, and fix variable name to write to
file.
=> Update virtual warping example

docs/topics/windowed-rw.rst
Found new api at: https://mapbox.github.io/rasterio/rasterio.windows.html?highlight=transform#rasterio.windows.transform
=> Fix doc regarding api change (rasterio.windows.transform)

CHANGES.txt, rasterio/rio/bounds.py, rasterio/rio/options.py, rasterio/rio/shapes.py, tests/test_rio_shapes.py
=> rio-shapes and rio-bounds print feature sequences by default

CHANGES.txt, rasterio/__init__.py, rasterio/_io.pyx, tests/test_dataset_rw.py
=> Add the missing w+ mode

CHANGES.txt, rasterio/__init__.py
close https://github.com/mapbox/rasterio/issues/1116
=> Remove deprecated r- mode

CHANGES.txt, rasterio/_io.pyx, tests/test_complex_dtypes.py, tests/test_gdal_raster_io.py
Also clean up deprecated usage in Rasterio.
Resolves #1309
=> Warn about deprecation of usage in read_masks

CHANGES.txt, rasterio/_crs.pyx, tests/test_crs.py
closes https://github.com/mapbox/rasterio/issues/1034
This pr mostly re-use code proposed in https://github.com/mapbox/rasterio/pull/1036
cc @sgillies (and @perrygeo because previous work)
=> Empty CRS should be equals

CHANGES.txt, docs/topics/migrating-to-v1.rst, docs/topics/windowed-rw.rst, rasterio/__init__.py, rasterio/_base.pyx, rasterio/_io.pyx, rasterio/features.py, rasterio/profiles.py, rasterio/windows.py, tests/test_band_masks.py, tests/test_blocks.py, tests/test_checksum.py, tests/test_deprecated.py, tests/test_features.py, tests/test_indexing.py, tests/test_io_mixins.py, tests/test_mask_creation.py, tests/test_profile.py, tests/test_windows.py
These are the deprecations we've been warning about for months and many releases.
*except reading from datasets in "w" mode, which will wait one more pre-release or two.
TODO: 
Resolves #1319
=> Remove all deprecated features* and update tests

CHANGES.txt, rasterio/features.py, rasterio/tools.py, tests/test_tools.py
Resolves #1300. There is no tool in here yet. The module serves as a placeholder (as @perrygeo suggested) and an example for future tools.
=> Tools module, class, and tests

setup.py
=> Move -std=c++11 to cpp extension options only

.travis.yml, scripts/travis_gdal_install.sh
=> make build faster or not timing out 

rasterio/_warp.pyx, rasterio/vrt.py, tests/test_warpedvrt.py
This PR adds tests for the `src_crs` and `src_transform` parameters on `WarpedVRT` and adds them to the parameter list in the `WarpedVRT` docstring.
Addresses #859
=> WIP:Document and test src_crs and src_transform on WarpedVRT

rasterio/env.py, rasterio/warp.py, tests/test_env.py, tests/test_warp.py
And more! Check out the monster bug I fixed in `ensure_env` !
=> Resolves #1011

.travis.yml, CHANGES.txt, rasterio/transform.py, rasterio/windows.py, tests/test_features.py, tests/test_windows.py, tests/test_windows_mixins.py
Totally optional. Some more testing may be needed.
~TODO: add more tests.~
Resolves #1139 and #1143
=> precision=None

CHANGES.txt, docs/topics/migrating-to-v1.rst, rasterio/_base.pyx, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/rio/edit_info.py, tests/test_descriptions.py, tests/test_units.py, tests/test_update.py
Resolves #1175 
~Last TODO: check docs and tests for deprecated usage.~ None found.
=> Make descriptions and units properties set-able, warn about deprecation of setters

rasterio/_warp.pyx
```
============================= test session starts =============================
platform win32 -- Python 3.7.0b4, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: D:\Build\rasterio\rasterio-1.0b1, inifile: setup.cfg
plugins: faulthandler-1.5.0, hypothesis-3.56.10, celery-4.1.1
collected 1118 items
tests\test_band.py .                                                     [  0%]
tests\test_band_masks.py ...........                                     [  1%]
tests\test_blocks.py .................                                   [  2%]
tests\test_boundless_read.py .                                           [  2%]
tests\test_checksum.py ......                                            [  3%]
tests\test_cli_main.py ..                                                [  3%] …
```
=> Fix segfault on Windows

rasterio/_features.pyx, rasterio/features.py
In `rasterize`, `_rasterize`.
Resolves #1363
=> str -> MergeAlg in docstrings

rasterio/_io.pyx, tests/test_dataset_mask.py
closes https://github.com/mapbox/rasterio/issues/1298
=> add read_masks's kwargs to dataset_mas method 

CHANGES.txt, rasterio/rio/blocks.py, rasterio/rio/bounds.py, rasterio/rio/clip.py, rasterio/rio/env.py, rasterio/rio/mask.py, rasterio/rio/rasterize.py, rasterio/rio/sample.py, rasterio/rio/shapes.py, rasterio/rio/stack.py, rasterio/rio/transform.py
=> Change all local loggers to getLogger(__name__)

CHANGES.txt, rasterio/_crs.pyx, tests/test_crs.py
This addresses issue #1288.
Please let me know what changes are needed to get this merged in. Thanks!
=> Added CRS epsg property

requirements-dev.txt
=> Use Cython 0.28.3 to get 3.7 support

AUTHORS.txt
Thank you very much for adding me to `AUTHORS.txt` and congratulations for the long awaited rasterio 1.0 release! However, I have a minor nitpick with my name in the list: "Juan Luis" is my first name, and "Cano" my surname :)
=> Add missing last name

rasterio/enums.py
Adding LERC compression enum for when LERC is supported by GDAL.
=> Adding LERC compression enum item

rasterio/_warp.pyx, rasterio/warp.py, tests/test_warp.py
Also set color interpretation and remove nodata on the temp warp output dataset.
Resolves #1415
=> dst_alpha, not dst_alpa

rasterio/warp.py, tests/test_warp.py, tests/test_warp_transform.py
The rationale of this feature is located here: https://rasterio.groups.io/g/main/message/12
=> Add new dimensions parameter to the calculate_default_transform function

rasterio/env.py, rasterio/session.py, tests/test_env.py, tests/test_session.py
=> Move session stuff to a new module

rasterio/_features.pyx, rasterio/features.py, tests/test_features.py, tests/test_warp.py
=> support geometry type LinearRing

rasterio/_features.pyx, rasterio/features.py, tests/test_features.py, tests/test_warp.py
=> Revert "support geometry type LinearRing"

rasterio/_warp.pyx, tests/test_warp.py
Never "cut" points at the antimeridian to avoid the issue reported in #1446.
=> Resolve #1446

CHANGES.txt, rasterio/__init__.py, rasterio/_io.pyx, rasterio/rio/overview.py, tests/test_overviews.py
=> Add missing overview resampling algorithms

rasterio/_io.pxd, rasterio/_io.pyx, rasterio/_warp.pyx
Just tinkering.
Phase 1 of  #816
=> Use InMemoryRaster to remove duplicate code.

rasterio/_io.pxd, rasterio/_io.pyx, rasterio/_warp.pyx
Reverts mapbox/rasterio#1427
I'm going to merge this to maint-1.0 instead.
=> Revert "Use InMemoryRaster to remove duplicate code."

rasterio/rio/main.py, rasterio/session.py, tests/test_session.py
=> --request-pays and --no-sign-requests

rasterio/features.py, tests/test_features.py
=> Avoid losing a row or column in geometry_window()

CHANGES.txt, rasterio/_warp.pyx, tests/test_warp_transform.py
=> Use VRT instead of in-memory raster when calculating transform

CHANGES.txt, rasterio/_io.pyx, rasterio/errors.py, tests/test_overviews.py
=> Add an OverviewCreationError

CHANGES.txt, rasterio/rio/convert.py, rasterio/rio/rasterize.py, rasterio/rio/shapes.py
=> Do not resolve path arguments in rio-convert and rio-shapes

rasterio/coords.py
This PR supersedes https://github.com/mapbox/rasterio/pull/1486
=> Python 3.4.3 compatibility

rasterio/_crs.pyx
Fix for issue https://github.com/mapbox/rasterio/issues/1492
=> Stop support comparison to dict and str for CRS objects

rasterio/__init__.py
There is no `DatasetUpdater` class.
=> Fix docstring

CHANGES.txt, rasterio/features.py, tests/test_features.py
=> Add full support for numpy masked arrays to features.shapes()

rasterio/_base.pxd, rasterio/_base.pyx, rasterio/_io.pyx, rasterio/gdal.pxi, tests/test_env.py
=> Add missing offsets and scales properties

rasterio/_crs.pyx, rasterio/gdal.pxi, tests/test_crs.py
=> added support for ESRI wkt strings

rasterio/_base.pyx, rasterio/_crs.pyx, tests/conftest.py, tests/test_rio_warp.py, tests/test_warp.py
=> modified _osr_from_crs to use CRS.from_user_input

rasterio/_base.pyx, rasterio/_crs.pyx, tests/conftest.py, tests/test_rio_warp.py, tests/test_warp.py
=> Revert "modified _osr_from_crs to use CRS.from_user_input"

.travis.yml, CHANGES.txt, rasterio/__init__.py, rasterio/_base.pyx, rasterio/_crs.pyx, rasterio/_env.pyx, rasterio/env.py, rasterio/rio/env.py, tests/conftest.py, tests/test_crs.py, tests/test_data_paths.py, tests/test_env.py, tests/test_write.py
Here's the PR that does for Rasterio what I proposed in https://github.com/Toblerity/Fiona/issues/673#issuecomment-440723698: patch os.environ after we find GDAL data in a wheel.
=> Patch environ gdal data

scripts/travis_gdal_install.sh
=> Address issue 1556

CHANGES.txt, rasterio/_io.pxd, rasterio/_io.pyx, rasterio/_shim.pxd, rasterio/_shim1.pyx, rasterio/_shim20.pyx, rasterio/shim_rasterioex.pxi, tests/test_warp.py
=> Turn on exceptions and use Py_ssize_t for index arrays

rasterio/merge.py
=> Update rasterio.merge docs

AUTHORS.txt, rasterio/path.py, rasterio/session.py, tests/test_session.py
Adds support for `gs://` paths, which refer to a Google Cloud Storage bucket.
=> Add google cloud storage support

rasterio/_base.pyx, rasterio/_crs.pxd, rasterio/_crs.pyx, rasterio/_err.pxd, rasterio/_err.pyx, rasterio/crs.py, rasterio/gdal.pxi, tests/test_crs.py, tests/test_rio_edit_info.py, tests/test_rio_warp.py
Rewrite of CRS to use _CRS by composition, not inheritance
New OGRErr handling function exc_wrap_ogrerr
=> Rewrite of _CRS to keep an OGRSpatialReferenceH

rasterio/_crs.pyx, rasterio/_env.pyx, rasterio/env.py, tests/test_crs.py, tests/test_env.py
I'm coming to the conclusion that setting GDAL_DATA as early as possible is the one true path to happiness.
=> Patch GDAL_DATA into environment

rasterio/_io.pyx, tests/test_read.py, tests/test_read_dtype.py
=> Add out_dtype parameter to dataset's read()

CHANGES.txt, rasterio/_env.pyx, rasterio/compat.py, rasterio/env.py, rasterio/gdal.pxi, setup.py, tests/test_data_paths.py, tests/test_env.py
If we have them, don't set GDAL_DATA or PROJ_LIB.
Resolves #1631
=> Check for data files at builtin locations

CHANGES.txt
Noticed these typos in the changelog
=> Year typos in the changelog

CHANGES.txt, rasterio/__init__.py, rasterio/crs.py, tests/test_crs.py
Resolves #1684
I referenced copy in the branch name, but that work has already been done.
=> Make CRS hashable, update change log

CHANGES.txt, rasterio/__init__.py, rasterio/env.py, tests/test_env.py
=> Default to DummySession if boto3 can't be imported

CHANGES.txt, rasterio/_io.pyx, tests/test_memoryfile.py, tests/test_write.py
=> Require width/height when opening a MemoryFile in w+ mode

setup.py
GDAL/gdal-config may not be available outside the build chroot.
=> Fix clean target.

CHANGES.txt, rasterio/crs.py, tests/test_crs.py
=> support CRS.from_user_input with other CRS with to_wkt

CHANGES.txt, rasterio/crs.py, tests/test_crs.py
=> return false for comparison with objects incompatible with CRS

.travis.yml, rasterio/__init__.py, rasterio/_base.pyx, rasterio/_features.pyx, rasterio/_io.pxd, rasterio/_io.pyx, rasterio/_shim1.pyx, rasterio/_shim20.pyx, rasterio/_shim21.pyx, rasterio/_shim30.pyx, rasterio/_warp.pxd, rasterio/_warp.pyx, rasterio/features.py, rasterio/gdal.pxi, rasterio/shutil.pyx, tests/conftest.py, tests/test_features.py, tests/test_open_options.py, tests/test_open_sharing.py, tests/test_warpedvrt.py
=> Switch sharing kwarg default to False

rasterio/_env.pyx, rasterio/env.py
=> Check pkg for GDAL and PROJ data before checking API

.travis.yml, CHANGES.txt, rasterio/__init__.py, rasterio/_base.pyx, rasterio/_io.pyx, rasterio/_warp.pxd, rasterio/_warp.pyx, tests/test_warpedvrt.py
Towards resolving #1799
Any chance you could give this a try in the morning @vincentsarago ?
=> Trust in GDAL's reference counting

CHANGES.txt, rasterio/__init__.py, rasterio/_env.pyx, rasterio/_shim.pxd, rasterio/_shim1.pyx, rasterio/_shim20.pyx, rasterio/_shim21.pyx, rasterio/_shim30.pyx, rasterio/env.py, tests/test__env.py, tests/test_env.py
=> PROJ data search path setting for rasterio

CHANGES.txt, rasterio/merge.py, rasterio/rio/merge.py, tests/test_rio_merge.py
=> Increase merge tool's default precision from 7 to 10

CHANGES.txt, rasterio/rio/bounds.py, rasterio/rio/helpers.py, tests/test_rio_bounds.py, tests/test_rio_info.py
This case is covered by the --sequence/--collection switch
Resolves #1807
=> Remove FeatureCollection from output GeoJSON types

CHANGES.txt, rasterio/_io.pyx, tests/test_dataset_mask.py
We'd missed the last band of the dataset in some cases.
=> Fix bug in dataset_mask

CHANGES.txt, rasterio/sample.py, tests/test_warpedvrt.py
=> Fix broken sampling for WarpedVRT datasets

rasterio/_warp.pyx, rasterio/compat.py, tests/test_warp.py
=> optimized transform_geom for repeated transformations with geometry arrays

docs/cli.rst
Minor rearrange of "Mask" docs for consistency.
=> [Docs] Alphabetic order of cli docs

rasterio/_io.pyx
Also clean up code in dataset_mask
=> Don't tamper with alpha values between 0 and 255

CHANGES.txt, rasterio/__init__.py, rasterio/_base.pyx, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/compat.py, rasterio/io.py, rasterio/path.py, rasterio/shutil.pyx, rasterio/vrt.py, tests/test_path.py
=> New Path.as_vsi method to reduce ambiguity

CHANGES.txt, rasterio/__init__.py, rasterio/_io.pyx, rasterio/io.py
=> Tile db inc driver scanning

CHANGES.txt, rasterio/_shim.pxd, rasterio/_shim1.pyx, rasterio/shim_rasterioex.pxi, tests/test_rio_merge.py
=> Fix type mismatch

rasterio/vrt.py, tests/test_boundless_read.py
=> Take into account open options for boundless read

rasterio/env.py, rasterio/warp.py, tests/test_env.py, tests/test_warp.py
=> Remove CHECK_WITH_INVERT_PROJ=YES default

CHANGES.txt, tests/test_crs.py
First time I've tried this. I think it could be more understandable than separate tests? What do you think @vincentsarago ?
=> xfail in the parametrization

rasterio/_features.pyx, rasterio/_warp.pyx, tests/test_warp.py
=> ENH: Add support for objects with __geo_interface__ in transform_geom

rasterio/session.py, tests/test_session.py
=> Guard against unnecessary credentialization

rasterio/crs.py, tests/test_crs.py
=> BUG: CRS.from_string fix for case when WKT contains PROJ string

CHANGES.txt, rasterio/merge.py, rasterio/rio/merge.py, tests/test_rio_merge.py
And use this option in rio-merge.
Resolves #1831
=> Allow merge to open one dataset at a time

rasterio/_crs.pyx, rasterio/crs.py, tests/test_crs.py
=> ENH: Add support for generic SRS authorities

rasterio/_base.pyx, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/errors.py, rasterio/io.py, tests/test_warpedvrt.py
=> Consolidate dataset stop methods and test for issue #2000

rasterio/__init__.py, rasterio/_base.pyx, rasterio/drivers.py, rasterio/rio/calc.py, rasterio/rio/clip.py, rasterio/rio/convert.py, rasterio/rio/mask.py, rasterio/rio/merge.py, rasterio/rio/options.py, rasterio/rio/rasterize.py, rasterio/rio/stack.py, rasterio/rio/warp.py, rasterio/shutil.pyx, tests/test_rio_convert.py, tests/test_shutil.py, tests/test_write.py
=> ENH: Auto-detect driver based on extension

CONTRIBUTING.rst, docs/topics/masks.rst, docs/topics/memory-files.rst, docs/topics/switch.rst, rasterio/_warp.pyx
This PR fixes a few stale links found in the docs and in comments.
=> Fix stale links

.gitignore
Small QOL, add .vscode dir to gitignore
=> add .vscode directory to gitignore

rasterio/enums.py, rasterio/shim_rasterioex.pxi, rasterio/warp.py, tests/test_read_resample.py, tests/test_warp.py
For root mean square / quadratic mean.
Added in GDAL 3.3 per https://github.com/OSGeo/gdal/pull/3210
=> Add a Resampling.rms method

rasterio/rio/main.py
=> Construct AWSSession if --aws-requester-pays option was supplied

setup.py
=> Update setup.py supported python versions

README.rst, rasterio/_base.pyx, rasterio/_crs.pyx, rasterio/_env.pyx, rasterio/_err.pyx, rasterio/_features.pyx, rasterio/_fill.pyx, rasterio/_io.pyx, rasterio/_shim1.pyx, rasterio/_shim20.pyx, rasterio/_shim21.pyx, rasterio/_shim30.pyx, rasterio/_transform.pyx, rasterio/_warp.pyx, rasterio/shutil.pyx, setup.py
=> Use cython's language level 3 and update README and setup.py

rasterio/_env.pyx, rasterio/env.py
=> Search wheel for PROJ data before searching the system

CHANGES.txt, rasterio/features.py, rasterio/mask.py, rasterio/transform.py, rasterio/windows.py, tests/test_features.py, tests/test_windows.py
=> Rewrite of from_bounds and geometry_window

rasterio/session.py, tests/conftest.py, tests/test_rio_info.py, tests/test_session.py
See https://github.com/mapbox/rasterio/pull/1906#issuecomment-780661937
=> Add unsigned Azure requests support

CHANGES.txt, rasterio/_crs.pyx, rasterio/crs.py, rasterio/enums.py, rasterio/gdal.pxi, tests/test__crs.py, tests/test_crs.py
GDAL reference: https://github.com/OSGeo/gdal/blob/ee426e4f522ebaf8ca916113214ec773aaef93f3/gdal/ogr/ogrspatialreference.cpp#L1431
WKT2_2019 reference: https://github.com/OSGeo/PROJ/pull/1585
Related to #2044
=> ENH: Add version to CRS.to_wkt()

rasterio/env.py
Resolves https://github.com/Toblerity/Fiona/issues/1007.
=> use set_gdal_config rather than setting GDAL_DATA

CHANGES.txt, rasterio/merge.py, tests/test_merge.py
=> Fix mask error in min and max merge algorithms

tests/test_rpcs.py
=> don't check ERR_RAND and ERR_BIAS in test_rpcs

CHANGES.txt, rasterio/__init__.py, rasterio/_base.pyx, rasterio/_features.pyx, rasterio/_io.pyx, rasterio/dtypes.py, rasterio/features.py, tests/test_complex_dtypes.py, tests/test_dtypes.py
=> Save GDAL CInt16 data

CHANGES.txt, rasterio/__init__.py, rasterio/windows.py, tests/test_windows.py
Resolves the issue reported in #2177
=> Use default Window constructor instead of Window.from_slices in union()

rasterio/_warp.pyx, tests/test_warpedvrt.py
- pulls gcps/crs from src dataset
- passes gcps/rpcs into _calculate_default_transform if needed
=> ENH: Improve support for gcps/rpcs with WarpedVRT

rasterio/_warp.pyx, rasterio/warp.py, tests/test_warp_transform.py
=> ENH: Add antimeridian support for transform_bounds()

.travis.yml, setup.py
Added the `python setup.py clean` command in the build to make sure it doesn't get broken in the future.
=> BUG: Fix setup.py clean

.travis.yml, setup.py
Reverts mapbox/rasterio#2214.
@snowman2 sorry, but #2214 broke our Travis builds.
=> Revert "BUG: Fix setup.py clean"

rasterio/_base.pyx, rasterio/_io.pyx, rasterio/dtypes.py, rasterio/rio/edit_info.py, tests/test_nodata.py, tests/test_rio_edit_info.py
Closes #2227
@sgillies there are now 3 versions of the function `in_dtype_range`. Do you foresee any problems if we only used the version in `dtypes.py`?
=> BUG: Allow read/write inf as nodata value

rasterio/_crs.pyx, tests/test__crs.py
Fixes https://github.com/mapbox/rasterio/issues/2246
=> Check bool kwargs for CRS.from_dict

README.rst, rasterio/session.py, requirements.txt, tests/test_env.py, tests/test_merge.py, tests/test_rio_info.py, tests/test_warpedvrt.py
=> Use boto3 method to get session credentials

CONTRIBUTING.rst
=> fix link to darker

CHANGES.txt, rasterio/__init__.py, rasterio/transform.py, tests/test_transform.py
=> Branch after testing for __iter__ and open up to all numeric types

rasterio/_io.pyx
Fixes #2297
This PR catches an extra exception, preventing the problem described in the issue mentioned
=> Fix writing file to GCS when using a new prefix

pyproject.toml
=> upgrade cython to allow building against python 3.10

README.rst
Makes it easier to find the package on PyPI and see what the latest version is
=> Readme: Add PyPI badge

CHANGES.txt, rasterio/_env.pyx, rasterio/_err.pyx, rasterio/_warp.pyx, tests/test_err.py
@vincentsarago @rouault does this make sense to you?
Resolves #2353
=> Always check the error stack after calling GDALSuggestedWarpOutput2

CHANGES.txt, rasterio/_warp.pyx, tests/test_warpedvrt.py
=> Scaling on the right of mult preserves origin

rasterio/_warp.pyx, rasterio/gdal.pxi, tests/test_warp.py, tests/test_warp_transform.py
=> REF: Use OCTTransformBounds in transform_bounds

docs/topics/reproject.rst, rasterio/__init__.py, rasterio/_features.pyx
Fixed three dead links, spotted a dead not trivially fixed 410 (mapbox) link. The latter is not really fixed, but I need expertise on how to fix it (if fix it needs).
Fixes #2389
=> Fix invalid URLs

rasterio/rpc.py
Reverts rasterio/rasterio#2419 which I accidentally merged :facepalm:
=> Revert "fix RPC metadata parsing"

rasterio/rpc.py
New PR since I fumbled #2419. Sorry about that @ungarj ! @underchemist can I get a review from you? Aren't the values supposed to be floats? Does GDAL intentionally or only accidentally trim off the units?
=> Fix rpcs parsing

.github/workflows/tests.yaml
☝️ 
The idea is to limit the GH actions run and to also fasten PR that doesn't touch the code itself
=> filter paths to only run tests when code has changed

rasterio/crs.pyx, rasterio/gdal.pxi, tests/test_crs.py
=> ENH: Add CRS.units_factor to return units for both projected and geographic CRS

rasterio/_features.pyx, tests/test_features.py
=> BUG: Prevent core dump with invalid input to rasterize

rasterio/crs.pyx
=> Updates to crs.pyx

CHANGES.txt, rasterio/rio/warp.py, tests/test_rio_warp.py
=> Pass --wo and --to options through to the warper and transformer

rasterio/_base.pxd, rasterio/_base.pyx, rasterio/_env.pyx, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/crs.pyx, rasterio/gdal.pxi, setup.py
=> DEP: Require GDAL 3+

rasterio/__init__.py, rasterio/_base.pyx, rasterio/_env.pyx, rasterio/_io.pyx, rasterio/_version.pxd, rasterio/_version.pyx, rasterio/_warp.pyx, rasterio/crs.pyx, rasterio/env.py, rasterio/gdal.pxi, setup.py, tests/test__version.py
=> ENH: Add PROJ & GEOS version information

CHANGES.txt, rasterio/_base.pyx, rasterio/_io.pyx, rasterio/gdal.pxi, rasterio/rio/info.py, tests/test_dataset.py, tests/test_rio_info.py
=> Add method for getting raster band stats

docs/conf.py, rasterio/warp.py
=> DOC: Add intersphinx with GDAL for rasterio.warp.reproject

.github/workflows/tests.yaml, README.rst, rasterio/_env.pyx, rasterio/_version.pxd, rasterio/_version.pyx, rasterio/crs.pyx, rasterio/gdal.pxi, setup.py
=> DEP: GDAL 3.1+

.github/workflows/tests.yaml, rasterio/__init__.py, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/dtypes.py, rasterio/features.py, rasterio/gdal.pxi, tests/conftest.py, tests/test_dtypes.py, tests/test_features.py, tests/test_write.py
=> Snowman2 int64

.github/workflows/tests.yaml
Conda tests are failing on master. This is either due to a recent update of libgdal (yesterday) or geos (3 days ago).
=> MNT: Fix failing conda tests on master

rasterio/_base.pyx
=> DOC: DatasetBase.descriptions return docstring fix

.travis.yml, docs/faq.rst, rasterio/_env.pyx, rasterio/env.py, rasterio/rio/env.py, setup.py, tests/test_crs.py
=> ENH: Add support for PROJ_DATA environment variable

rasterio/__init__.py
https://github.com/rasterio/rasterio/blob/38ad052cc2ab460d0b632bd2f3d7919e3d96c3c8/rasterio/__init__.py#L75
=> BUG: RasterioDeprecationWarning import missing

.github/workflows/tests.yaml, CHANGES.txt, rasterio/__init__.py, rasterio/sample.py, tests/test_io.py, tests/test_sampling.py
And fix a test filename.
Resolves #2515
=> Allow sample_gen to take ndarrays again.

CHANGES.txt, rasterio/_base.pyx, rasterio/_io.pyx, tests/test_write.py
=> Silence non-informative errors from _delete_dataset_if_exists

rasterio/windows.py, tests/test_windows.py
Related #2555
* Cleaner get_data_window implementation.
* Add tests.
* Separate assertions into distinct tests.
=> get_data_window cleanup (#2510)

rasterio/__init__.py
=> BUG: RasterioDeprecationWarning import missing (#2536)

.travis.yml, docs/faq.rst, rasterio/_env.pyx, rasterio/env.py, rasterio/rio/env.py, setup.py, tests/test_crs.py
=> ENH: Add support for PROJ_DATA environment variable (#2530)

README.rst, docs/api/rasterio.rio.blocks.rst, docs/api/rasterio.rio.bounds.rst, docs/api/rasterio.rio.calc.rst, docs/api/rasterio.rio.clip.rst, docs/api/rasterio.rio.convert.rst, docs/api/rasterio.rio.edit_info.rst, docs/api/rasterio.rio.env.rst, docs/api/rasterio.rio.gcps.rst, docs/api/rasterio.rio.helpers.rst, docs/api/rasterio.rio.info.rst, docs/api/rasterio.rio.insp.rst, docs/api/rasterio.rio.main.rst, docs/api/rasterio.rio.mask.rst, docs/api/rasterio.rio.merge.rst, docs/api/rasterio.rio.options.rst, docs/api/rasterio.rio.overview.rst, docs/api/rasterio.rio.rasterize.rst, docs/api/rasterio.rio.rm.rst, docs/api/rasterio.rio.rst, docs/api/rasterio.rio.sample.rst, docs/api/rasterio.rio.shapes.rst, docs/api/rasterio.rio.stack.rst, docs/api/rasterio.rio.transform.rst, docs/api/rasterio.rio.warp.rst, docs/api/rasterio.rst, docs/conf.py, rasterio/rio/blocks.py, requirements-dev.txt, setup.py
=> DOC: Use sphinx-click for CLI documentation

rasterio/_features.pxd, rasterio/_features.pyx, tests/test_warp.py
=> ENH: Add support for writing GeometryCollection

.github/workflows/tests.yaml
=> CI: Update to GDAL 3.5.2 in tests

tests/test_warp.py
=> TST: Skip test_issue2353bis for GDAL 3.5+

CHANGES.txt, rasterio/_base.pyx, rasterio/_io.pyx, tests/test_dataset.py, tests/test_profile.py
=> Fully support tiled=False and blockysize

tests/test_warp.py
This prevents it conflicting with anything else, as the fixed port that was specified is pretty common.
=> TST: Don't use fixed port for test server

rasterio/__init__.py, rasterio/windows.py, tests/test_warp.py, tests/test_windows.py
=> Backport to maint-1.3

CHANGES.txt, rasterio/__init__.py
=> Update version and change log

tests/conftest.py, tests/test_env.py, tests/test_rio_info.py, tests/test_warpedvrt.py
Closes #2646
EDIT: Using https://registry.opendata.aws/sentinel-2-l2a-cogs/ as suggested by @vincentsarago
=> TST: Update S3 paths

rasterio/features.py
Update documentation as suggested in issue #2665
=> fix #2665: Update documentation on rasterio.features.rasterize

rasterio/_io.pyx, tests/test_profile.py
=> BUG: ignore blockysize when converting untiled to tiled

tests/test_warp.py
=> TST: Update warp tests for GDAL 3.7

docs/installation.rst
=> installation.rst - Update GDAL minimum version 1.11 -> 3.1 as of #2448

tests/test_gdal_raster_io.py, tests/test_rio_merge.py
=> Fix numpy deprecation warning

rasterio/_io.pyx, tests/test_write.py
=> BUG: Update write_mask to accept numpy booleans (#2707)

rasterio/features.py, tests/test_features.py
=> ENH: Added int8 dtype to rasterize

docs/topics/errors.rst
https://github.com/rasterio/rasterio/discussions/2785
=> DOC: Add note about PROJ_DEBUG in debug error documentation

.github/workflows/test_gdal_latest.yaml, .github/workflows/tests.yaml, Dockerfile
=> CI: Use ghcr.io/osgeo/gdal docker image

CHANGES.txt, rasterio/_filepath.pyx, rasterio/io.py, tests/test_filepath.py, tests/test_memoryfile.py, tests/test_warp.py
=> Turn down logging level for non-existing files in the Python file VSI plugin

rasterio/sample.py, tests/conftest.py, tests/test_sampling.py
=> Fix the nodata mask value in sample_gen()

CHANGES.txt, rasterio/_features.pyx, rasterio/features.py, tests/test_features.py
=> Extend sieve's input to allow opened datasets and multiband objects

rasterio/_base.pyx, rasterio/rio/options.py
Needed to use this function but found that it wasn't documented.
=> Document DatasetBase.lnglat

.github/workflows/tests.yaml, pyproject.toml, rasterio/crs.pyx, requirements-dev.txt
=> DEP: pin cython>=3

docs/topics/reproject.rst
=> update docs usage

CHANGES.txt, rasterio/dtypes.py, rasterio/rio/edit_info.py
Also consolidate on one function to test whether a value can be represented using a data type.
Resolves #2927.
=> Lean on numpy for min and max of float data types

.github/workflows/test_gdal_latest.yaml, CHANGES.txt, ci/gdal-compile.sh, tests/test_read_resample.py, tests/test_rio_merge.py
Resolves #2958.
@snowman2 @vincentsarago what do you think about building two "latest" versions of GDAL?
=> Build two branches, master and the latest release branch

CHANGES.txt, rasterio/_warp.pyx
=> Deallocate warp_extras at end of _reproject()

CHANGES.txt, pyproject.toml, rasterio/__init__.py, rasterio/crs.pyx, rasterio/io.py, tests/test_filepath.py
=> Deprecate FilePath and CRS.is_valid

rasterio/io.py, tests/test_memoryfile.py
Ref: https://github.com/rasterio/rasterio/discussions/2860
=> Close derived datasets automatically when MemoryFile is closed

.github/workflows/test_gdal_latest.yaml
Switch from release/3.7 to release/3.8 in the weekly tests.
=> Test against release/3.8

CHANGES.txt, rasterio/plot.py, tests/test_plot.py
=> Change hist_range arg to range

CHANGES.txt, rasterio/_show_versions.py, rasterio/_vendor/snuggs.py, rasterio/rio/calc.py, setup.py, tests/test_rio_calc.py, tests/test_show_versions.py
=> Vendor snuggs

rasterio/features.py
Improves docs for features.geometry_mask()
=> docs: minor docs changes

pyproject.toml, requirements.txt, setup.py
=> DEP: Use numpy in pyproject.toml

CHANGES.txt, rasterio/plot.py, tests/test_plot.py
=> Don't squeeze 2-D arrays when plotting

CHANGES.txt, rasterio/_base.pyx, rasterio/_io.pyx, tests/test_blocks.py, tests/test_dataset.py, tests/test_profile.py, tests/test_rio_convert.py
Resolves #3012
https://en.wikipedia.org/wiki/Junk_DNA
=> Remove "junk DNA" from implementation of is_tiled

.github/workflows/tests.yaml, CHANGES.txt, Makefile, pyproject.toml, rasterio/__init__.py, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/rio/main.py, requirements-dev.txt, tests/test_cli_main.py, tests/test_rio_shapes.py, tests/test_warnings.py
Reverts rasterio/rasterio#3054
=> Revert "Rel 1.3.10"

.github/workflows/tests.yaml
Not sure how much appetite there is for this, given that architecture dependent stuff are rather more GDAL or numpy issues, but here you go if it is useful.
=> CI: add support for OSX arm64

.github/workflows/tests.yaml, CHANGES.txt, Makefile, pyproject.toml, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/rio/main.py, requirements-dev.txt, requirements.txt, setup.py, tests/test_cli_main.py
=> Numpy 2 compatibility

CHANGES.txt, tests/test_transform.py
=> Remove obsolete tests, update change log

rasterio/merge.py, tests/test_merge.py
Addresses #3031 
Improves handling for complex dtypes and nodata values.
=> Better handling for complex values in merge

.github/workflows/tests.yaml, CHANGES.txt, Makefile, pyproject.toml, rasterio/__init__.py, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/merge.py, rasterio/rio/main.py, rasterio/rio/merge.py, requirements-dev.txt, setup.py, tests/test_cli_main.py, tests/test_rio_shapes.py, tests/test_warnings.py
Because I merged #3054 too soon.
@vincentsarago @snowman2 can you re-approve?
=> Rel 1.3.10 take 2

CHANGES.txt, pyproject.toml, rasterio/__init__.py, rasterio/_io.pyx, rasterio/_vsiopener.pyx, rasterio/merge.py, setup.py, tests/test_merge.py
Releasing 1.4a3 from this branch.
=> Update change log and version for 1.4a3

CHANGES.txt, rasterio/rio/calc.py
=> Fix denominator in max_pixels calculation

rasterio/vrt.py
=> Fixed a typo in vrt.py

tests/test_features.py, tests/test_mask_creation.py, tests/test_read.py, tests/test_update.py
A test related to #3074 slipped in, I'll leave it with a xfail mark.
=> Adjust test expectations in light of 3.9.0

CHANGES.txt, rasterio/_env.pyx, rasterio/_vsiopener.pxd, rasterio/_vsiopener.pyx, rasterio/gdal.pxi, setup.py, tests/test_pyopener.py
Resolves #3079. 
See https://github.com/Toblerity/Fiona/pull/1408.
=> Port of Pyopener VSI plugin improvements in Fiona 1.10b2

.github/workflows/tests.yaml, pyproject.toml, requirements.txt
update numpy version requirement to use the official version 2.0.0
=> update update numpy version

docs/topics/concurrency.rst
=> Add an admonition about fork to the concurrency doc

rasterio/errors.py, rasterio/merge.py, tests/test_merge.py
Flipped and upside down sources now trigger this exception.
Resolves #3123
=> Add a new MergeError and use it in the merge tool

CHANGES.txt, rasterio/__init__.py, rasterio/_io.pyx, rasterio/gdal.pxi, rasterio/rio/info.py, tests/data/RGB.byte.tif.aux.xml, tests/test_rio_info.py, tests/test_statistics.py
=> Add stats(), clear_stats(), update_stats(), deprecate statistics()

CHANGES.txt, rasterio/_io.pyx, tests/test_colormap.py
=> Properly set color interpretation after writing a colormap

CHANGES.txt, rasterio/_env.pyx
=> Free string lists in get/set_proj_data_search_path()

CHANGES.txt, rasterio/__init__.py
=> Never pass key if/else without returning

CHANGES.txt, rasterio/enums.py, rasterio/rio/overview.py, tests/test_enums.py, tests/test_overviews.py
=> _OverviewResampling is OverviewResampling

CHANGES.txt, README.rst, rasterio/__init__.py
1.4.0rc1 has been tagged and released.
=> Release 1.4.0rc1

.github/workflows/tests.yaml, docs/installation.rst, rasterio/_filepath.pyx, rasterio/_io.pyx, rasterio/_warp.pyx, rasterio/dtypes.py, rasterio/features.py, requirements.txt, setup.py, tests/conftest.py, tests/test__env.py, tests/test_dtypes.py, tests/test_err.py, tests/test_features.py, tests/test_merge.py, tests/test_overviews.py, tests/test_read_resample.py, tests/test_rpcs.py, tests/test_warp.py, tests/test_warp_transform.py, tests/test_write.py
=> DEP: GDAL 3.5+, numpy 1.24+

CHANGES.txt, rasterio/transform.py
=> Return ints from dataset index()

setup.py
=> Add fsspec to test dependencies

rasterio/transform.py, tests/test_transform.py
And fix a couple other nits.
Resolves #3201
=> Update return values in docstrings

rasterio/_warp.pyx, tests/test_warp.py
=> Reduce destination dimensions in the 1-D case

CHANGES.txt, rasterio/__init__.py
This is the 1.4.2 release PR.
Wheel builds look like they'll be fine: https://github.com/rasterio/rasterio-wheels/actions.
=> Update change log and version for 1.4.2

tests/test_merge.py
=> Add a test for merging WarpedVRTs

rasterio/crs.pyx, tests/test_crs.py
also adds a test, recent versions of Proj include the IAU CRSs so this should work as is
=> adds IAU as known authority to CRS.to_authority

CHANGES.txt, rasterio/crs.pyx, tests/test_crs.py
=> Backport of #3217

rasterio/rio/convert.py, tests/test_rio_convert.py
=> Take into account nodata value in rio convert

CHANGES.txt, rasterio/crs.pyx, tests/test_crs.py, tests/test_write.py
=> Rewrite _matches() to better support to_authority() and to_epsg()

CHANGES.txt, rasterio/crs.pyx, tests/test_crs.py
=> Use to_epsg() in is_epsg_code()

CHANGES.txt, rasterio/_base.pyx, rasterio/enums.py
=> Allow MRF compression to surface in properties

CHANGES.txt, rasterio/__init__.py, tests/test_open.py
=> Prevent rasterio from trying to open a dataset object

CHANGES.txt, rasterio/_io.pyx, tests/test_boundless_read.py
=> Fix erroneous masking of 0-valued data

CHANGES.txt, rasterio/__init__.py, rasterio/_base.pyx, rasterio/_env.pxd, rasterio/_env.pyx, rasterio/_fill.pyx, rasterio/_io.pyx, rasterio/crs.pyx, rasterio/enums.py, rasterio/fill.py, rasterio/merge.py, rasterio/windows.py, tests/test_boundless_read.py, tests/test_crs.py, tests/test_env.py, tests/test_merge.py, tests/test_open.py, tests/test_rio_merge.py, tests/test_write.py
=> Merge 1.4.3

CHANGES.txt, rasterio/_vendor/snuggs.py, tests/test_rio_calc.py
=> Fix parsing of snuggs expressions including "in"

tests/test_warp.py
Change triggered by https://github.com/OSGeo/gdal/commit/b68bf74b6a4cdfd3303dcd8de6c7a25a6f05e67d
=> test_reproject_resampling: Add another value for mode.

rasterio/merge.py
=> Add missing docstring methods in merge.py
